import type { QuizQuestion } from "../quiz-bank";

export const dateQuestions: QuizQuestion[] = [
  // --- HISTOIRE ---
  { id: "date1", type: "date", theme: "Histoire", question: "En quelle année le Titanic a-t-il coulé ?", answer: 1912, points: 100 },
  { id: "date2", type: "date", theme: "Histoire", question: "En quelle année a eu lieu la Révolution Française ?", answer: 1789, points: 100 },
  { id: "date3", type: "date", theme: "Histoire", question: "En quelle année l'homme a-t-il marché sur la Lune ?", answer: 1969, points: 100 },
  { id: "date5", type: "date", theme: "Histoire", question: "En quelle année s'est terminée la Seconde Guerre mondiale ?", answer: 1945, points: 100 },
  { id: "date6", type: "date", theme: "Histoire", question: "En quelle année a eu lieu la chute du mur de Berlin ?", answer: 1989, points: 100 },
  { id: "date8", type: "date", theme: "Histoire", question: "En quelle année Christophe Colomb a-t-il découvert l'Amérique ?", answer: 1492, points: 100 },
  { id: "date11", type: "date", theme: "Histoire", question: "En quelle année l'Euro a-t-il été mis en circulation ?", answer: 2002, points: 100 },
  { id: "date13", type: "date", theme: "Histoire", question: "En quelle année a eu lieu l'attentat des tours jumelles (9/11) ?", answer: 2001, points: 80 },
  { id: "date14", type: "date", theme: "Histoire", question: "En quelle année Napoléon Ier est-il mort à Sainte-Hélène ?", answer: 1821, points: 150 },
  { id: "date15", type: "date", theme: "Histoire", question: "En quelle année a été signée la Déclaration d'Indépendance des USA ?", answer: 1776, points: 130 },
  { id: "date16", type: "date", theme: "Histoire", question: "En quelle année a été inaugurée la Tour Eiffel ?", answer: 1889, points: 120 },
  { id: "date18", type: "date", theme: "Histoire", question: "En quelle année s'est terminé le règne de Louis XIV ?", answer: 1715, points: 180 },
  { id: "date19", type: "date", theme: "Histoire", question: "En quelle année l'Algérie est-elle devenue indépendante ?", answer: 1962, points: 150 },
  { id: "date22", type: "date", theme: "Histoire", question: "En quelle année l'esclavage a-t-il été définitivement aboli en France ?", answer: 1848, points: 180 },
  { id: "date24", type: "date", theme: "Histoire", question: "En quelle année l'URSS a-t-elle été dissoute ?", answer: 1991, points: 140 },
  { id: "date25", type: "date", theme: "Histoire", question: "En quelle année a eu lieu le premier vol des frères Wright ?", answer: 1903, points: 180 },
  { id: "date26", type: "date", theme: "Histoire", question: "En quelle année Nelson Mandela a-t-il été libéré de prison ?", answer: 1990, points: 150 },
  { id: "date27", type: "date", theme: "Histoire", question: "En quelle année a débuté la guerre du Vietnam ?", answer: 1955, points: 190 },
  { id: "date28", type: "date", theme: "Histoire", question: "En quelle année a été fondé l'empire romain ?", answer: -27, points: 250 },
  { id: "date29", type: "date", theme: "Histoire", question: "En quelle année a commencé la construction de la pyramide de Khéops (environ) ?", answer: -2560, points: 280 },
  { id: "date30", type: "date", theme: "Histoire", question: "En quelle année l'esclavage a-t-il été aboli aux États-Unis ?", answer: 1865, points: 170 },
  { id: "date31", type: "date", theme: "Histoire", question: "En quelle année a été fondée l'ONU ?", answer: 1945, points: 100 },
  { id: "date34", type: "date", theme: "Histoire", question: "En quelle année s'est terminé l'Empire Romain d'Occident ?", answer: 476, points: 230 },
  { id: "date35", type: "date", theme: "Histoire", question: "En quelle année a été lancé le premier satellite artificiel, Spoutnik ?", answer: 1957, points: 150 },
  { id: "date40", type: "date", theme: "Histoire", question: "En quelle année a commencé la Première Guerre mondiale ?", answer: 1914, points: 100 },
  { id: "date41", type: "date", theme: "Histoire", question: "En quelle année a eu lieu le sacre de Charlemagne comme empereur d'Occident ?", answer: 800, points: 220 },
  { id: "date42", type: "date", theme: "Histoire", question: "En quelle année Jeanne d'Arc a-t-elle été brûlée à Rouen ?", answer: 1431, points: 200 },
  { id: "date43", type: "date", theme: "Histoire", question: "En quelle année a été signé l'édit de Nantes par Henri IV ?", answer: 1598, points: 220 },
  { id: "date44", type: "date", theme: "Histoire", question: "En quelle année Louis XVI a-t-il été guillotiné ?", answer: 1793, points: 130 },
  { id: "date45", type: "date", theme: "Histoire", question: "En quelle année Napoléon Bonaparte est-il devenu empereur des Français ?", answer: 1804, points: 150 },
  { id: "date46", type: "date", theme: "Histoire", question: "En quelle année a eu lieu la bataille de Waterloo ?", answer: 1815, points: 150 },
  { id: "date47", type: "date", theme: "Histoire", question: "En quelle année a eu lieu la Première croisade (prise de Jérusalem) ?", answer: 1099, points: 240 },
  { id: "date48", type: "date", theme: "Histoire", question: "En quelle année a été prise la Bastille à Paris ?", answer: 1789, points: 100 },
  { id: "date49", type: "date", theme: "Histoire", question: "En quelle année a débuté la guerre de Cent Ans ?", answer: 1337, points: 220 },
  { id: "date50", type: "date", theme: "Histoire", question: "En quelle année a pris fin la guerre de Cent Ans ?", answer: 1453, points: 220 },
  { id: "date51", type: "date", theme: "Histoire", question: "En quelle année a été signé le traité de Versailles mettant officiellement fin à la Première Guerre mondiale ?", answer: 1919, points: 150 },
  { id: "date52", type: "date", theme: "Histoire", question: "En quelle année a eu lieu le krach boursier de Wall Street, dit 'jeudi noir' ?", answer: 1929, points: 150 },
  { id: "date53", type: "date", theme: "Histoire", question: "En quelle année le général de Gaulle a-t-il lancé son célèbre appel du 18 juin ?", answer: 1940, points: 120 },
  { id: "date54", type: "date", theme: "Histoire", question: "En quelle année la Ve République française a-t-elle été fondée ?", answer: 1958, points: 140 },
  { id: "date55", type: "date", theme: "Histoire", question: "En quelle année Gandhi a-t-il été assassiné ?", answer: 1948, points: 180 },
  { id: "date56", type: "date", theme: "Histoire", question: "En quelle année les femmes ont-elles obtenu le droit de vote en France ?", answer: 1944, points: 160 },
  { id: "date57", type: "date", theme: "Histoire", question: "En quelle année Hiroshima a-t-elle été frappée par la première bombe atomique ?", answer: 1945, points: 120 },
  { id: "date58", type: "date", theme: "Histoire", question: "En quelle année la Corée du Sud et la Corée du Nord ont-elles été officiellement séparées ?", answer: 1953, points: 180 },
  { id: "date59", type: "date", theme: "Histoire", question: "En quelle année la crise des missiles de Cuba a-t-elle eu lieu ?", answer: 1962, points: 180 },
  { id: "date60", type: "date", theme: "Histoire", question: "En quelle année Martin Luther King a-t-il prononcé son discours 'I have a dream' ?", answer: 1963, points: 130 },
  { id: "date61", type: "date", theme: "Histoire", question: "En quelle année l'Inde est-elle devenue indépendante du Royaume-Uni ?", answer: 1947, points: 170 },

  // --- CULTURE G ---
  { id: "date4", type: "date", theme: "Culture G", question: "En quelle année est sorti le tout premier iPhone ?", answer: 2007, points: 80 },
  { id: "date7", type: "date", theme: "Culture G", question: "En quelle année est sorti le premier film Star Wars au cinéma ?", answer: 1977, points: 100 },
  { id: "date9", type: "date", theme: "Culture G", question: "En quelle année la France a-t-elle gagné sa première Coupe du Monde de foot ?", answer: 1998, points: 80 },
  { id: "date10", type: "date", theme: "Culture G", question: "En quelle année a été lancée la console PlayStation 1 en Europe ?", answer: 1995, points: 120 },
  { id: "date12", type: "date", theme: "Culture G", question: "En quelle année Facebook a-t-il été créé ?", answer: 2004, points: 80 },
  { id: "date17", type: "date", theme: "Culture G", question: "En quelle année a été lancé le premier iPhone ?", answer: 2007, points: 80 },
  { id: "date20", type: "date", theme: "Culture G", question: "En quelle année est mort Michael Jackson ?", answer: 2009, points: 80 },
  { id: "date21", type: "date", theme: "Culture G", question: "En quelle année a été inventé le World Wide Web (Web) ?", answer: 1989, points: 150 },
  { id: "date62", type: "date", theme: "Culture G", question: "En quelle année est sorti le film 'Le Seigneur des Anneaux : La Communauté de l'Anneau' ?", answer: 2001, points: 120 },
  { id: "date63", type: "date", theme: "Culture G", question: "En quelle année le premier film 'Harry Potter à l'école des sorciers' est-il sorti au cinéma ?", answer: 2001, points: 120 },
  { id: "date64", type: "date", theme: "Culture G", question: "En quelle année la chaîne YouTube a-t-elle été créée ?", answer: 2005, points: 100 },
  { id: "date65", type: "date", theme: "Culture G", question: "En quelle année Google a-t-il été fondé ?", answer: 1998, points: 100 },
  { id: "date66", type: "date", theme: "Culture G", question: "En quelle année le premier film 'Jurassic Park' est-il sorti ?", answer: 1993, points: 120 },
  { id: "date67", type: "date", theme: "Culture G", question: "En quelle année la série télévisée 'Friends' a-t-elle commencé à être diffusée ?", answer: 1994, points: 110 },
  { id: "date68", type: "date", theme: "Culture G", question: "En quelle année la première saison de 'Game of Thrones' a-t-elle été diffusée ?", answer: 2011, points: 100 },
  { id: "date69", type: "date", theme: "Culture G", question: "En quelle année est sorti le film d'animation 'Le Roi Lion' ?", answer: 1994, points: 100 },
  { id: "date70", type: "date", theme: "Culture G", question: "En quelle année a eu lieu la première édition de l'Eurovision ?", answer: 1956, points: 190 },
  { id: "date71", type: "date", theme: "Culture G", question: "En quelle année a été créé le jeu vidéo 'Minecraft' (version officielle) ?", answer: 2011, points: 120 },
  { id: "date72", type: "date", theme: "Culture G", question: "En quelle année est sorti le premier film 'Avengers' au cinéma ?", answer: 2012, points: 100 },
  { id: "date73", type: "date", theme: "Culture G", question: "En quelle année la série animée 'Pokémon' a-t-elle débuté au Japon ?", answer: 1997, points: 140 },
  { id: "date74", type: "date", theme: "Culture G", question: "En quelle année 'La Reine des neiges' (Frozen) est-il sorti au cinéma ?", answer: 2013, points: 90 },
  { id: "date75", type: "date", theme: "Culture G", question: "En quelle année le tout premier album des Beatles est-il sorti ?", answer: 1963, points: 180 },

  // --- SCIENCES ---
  { id: "date23", type: "date", theme: "Sciences", question: "En quelle année a été lancé le télescope spatial Hubble ?", answer: 1990, points: 150 },
  { id: "date32", type: "date", theme: "Sciences", question: "En quelle année Einstein a-t-il publié la théorie de la relativité générale ?", answer: 1915, points: 180 },
  { id: "date33", type: "date", theme: "Sciences", question: "En quelle année a eu lieu la première transplantation cardiaque ?", answer: 1967, points: 200 },
  { id: "date36", type: "date", theme: "Sciences", question: "En quelle année la structure de l'ADN a-t-elle été découverte ?", answer: 1953, points: 190 },
  { id: "date37", type: "date", theme: "Sciences", question: "En quelle année a été découvert le vaccin contre la polio ?", answer: 1955, points: 190 },
  { id: "date38", type: "date", theme: "Sciences", question: "En quelle année a été découvert le boson de Higgs ?", answer: 2012, points: 180 },
  { id: "date39", type: "date", theme: "Sciences", question: "En quelle année a été découvert le virus du SIDA ?", answer: 1983, points: 150 },
  { id: "date76", type: "date", theme: "Sciences", question: "En quelle année Isaac Newton a-t-il publié les 'Principia Mathematica' ?", answer: 1687, points: 250 },
  { id: "date77", type: "date", theme: "Sciences", question: "En quelle année Louis Pasteur a-t-il mis au point le vaccin contre la rage ?", answer: 1885, points: 210 },
  { id: "date78", type: "date", theme: "Sciences", question: "En quelle année Marie Curie a-t-elle reçu son premier prix Nobel ?", answer: 1903, points: 170 },
  { id: "date79", type: "date", theme: "Sciences", question: "En quelle année Alexander Fleming a-t-il découvert la pénicilline ?", answer: 1928, points: 170 },
  { id: "date80", type: "date", theme: "Sciences", question: "En quelle année Yuri Gagarine est-il devenu le premier homme dans l'espace ?", answer: 1961, points: 120 },
  { id: "date81", type: "date", theme: "Sciences", question: "En quelle année le premier téléphone portable commercial a-t-il été lancé ?", answer: 1983, points: 180 },
  { id: "date82", type: "date", theme: "Sciences", question: "En quelle année a été créé le premier ordinateur personnel IBM PC ?", answer: 1981, points: 180 },
  { id: "date83", type: "date", theme: "Sciences", question: "En quelle année le premier courriel (email) a-t-il été envoyé ?", answer: 1971, points: 230 },
  { id: "date84", type: "date", theme: "Sciences", question: "En quelle année le CERN a-t-announced la première observation du boson de Higgs ?", answer: 2012, points: 180 },
  { id: "date85", type: "date", theme: "Sciences", question: "En quelle année le premier vaccin contre la COVID-19 a-t-il commencé à être administré ?", answer: 2020, points: 80 },

  // --- SPORT ---
  { id: "date-sp1", type: "date", theme: "Sport", question: "En quelle année ont eu lieu les Jeux Olympiques d'été à Pékin ?", answer: 2008, points: 120 },
  { id: "date-sp2", type: "date", theme: "Sport", question: "En quelle année l'équipe de France de football a gagné sa deuxième étoile (Coupe du monde) ?", answer: 2018, points: 60 },
  { id: "date-sp3", type: "date", theme: "Sport", question: "En quelle année ont eu lieu les premiers Jeux Olympiques de l'ère moderne (à Athènes) ?", answer: 1896, points: 210 },
  { id: "date-sp4", type: "date", theme: "Sport", question: "En quelle année a eu lieu la toute première édition du Tour de France cycliste ?", answer: 1903, points: 200 },
  { id: "date-sp5", type: "date", theme: "Sport", question: "En quelle année l'équipe de France a-t-elle remporté sa PREMIÈRE Coupe du Monde de football ?", answer: 1998, points: 60 },
  { id: "date-sp6", type: "date", theme: "Sport", question: "En quelle année la ligue américaine de basket-ball (NBA) a-t-elle été créée ?", answer: 1946, points: 200 },
  { id: "date-sp7", type: "date", theme: "Sport", question: "En quelle année Usain Bolt a-t-il pulvérisé le record du monde du 100m en 9.58 secondes ?", answer: 2009, points: 120 },
  { id: "date-sp8", type: "date", theme: "Sport", question: "En quelle année la France a-t-elle organisé la Coupe du Monde de football pour la première fois ?", answer: 1938, points: 190 },
  { id: "date-sp9", type: "date", theme: "Sport", question: "En quelle année Pelé a-t-il remporté sa première Coupe du Monde avec le Brésil ?", answer: 1958, points: 160 },
  { id: "date-sp10", type: "date", theme: "Sport", question: "En quelle année Michael Jordan a-t-il remporté son dernier titre NBA avec les Bulls ?", answer: 1998, points: 140 },
  { id: "date-sp11", type: "date", theme: "Sport", question: "En quelle année Roger Federer a-t-il gagné son premier tournoi de Wimbledon ?", answer: 2003, points: 130 },
  { id: "date-sp12", type: "date", theme: "Sport", question: "En quelle année Serena Williams a-t-elle remporté son premier titre du Grand Chelem en simple ?", answer: 1999, points: 180 },
  { id: "date-sp13", type: "date", theme: "Sport", question: "En quelle année Zinedine Zidane a-t-il inscrit son célèbre coup de tête en finale de Coupe du Monde ?", answer: 2006, points: 80 },
  { id: "date-sp14", type: "date", theme: "Sport", question: "En quelle année Lionel Messi a-t-il remporté sa première Coupe du Monde avec l'Argentine ?", answer: 2022, points: 60 },
  { id: "date-sp15", type: "date", theme: "Sport", question: "En quelle année a eu lieu la première Coupe du Monde de football ?", answer: 1930, points: 180 },

  // --- DESSIN ANIMÉ ---
  { id: "date-da1", type: "date", theme: "Dessin animé", question: "En quelle année est sorti le tout premier film d'animation 'Toy Story' ?", answer: 1995, points: 150 },
  { id: "date-da2", type: "date", theme: "Dessin animé", question: "En quelle année Mickey Mouse a-t-il fait sa toute première apparition à l'écran ?", answer: 1928, points: 140 },
  { id: "date-da3", type: "date", theme: "Dessin animé", question: "En quelle année est sorti 'Blanche-Neige', le tout premier long métrage d'animation Disney ?", answer: 1937, points: 150 },
  { id: "date-da4", type: "date", theme: "Dessin animé", question: "En quelle année a été diffusé le tout premier épisode régulier des Simpson aux États-Unis ?", answer: 1989, points: 140 },
  { id: "date-da5", type: "date", theme: "Dessin animé", question: "En quelle année est sorti au cinéma le premier film 'Shrek' ?", answer: 2001, points: 100 },
  { id: "date-da6", type: "date", theme: "Dessin animé", question: "En quelle année le célèbre manga 'Dragon Ball' a-t-il été publié pour la toute première fois ?", answer: 1984, points: 170 },
  { id: "date-da7", type: "date", theme: "Dessin animé", question: "En quelle année est sorti le magnifique chef-d'œuvre de Ghibli 'Le Voyage de Chihiro' ?", answer: 2001, points: 150 },
  { id: "date-da8", type: "date", theme: "Dessin animé", question: "En quelle année est sorti 'Le Roi Lion' au cinéma ?", answer: 1994, points: 100 },
  { id: "date-da9", type: "date", theme: "Dessin animé", question: "En quelle année 'La Petite Sirène' de Disney est-il sorti ?", answer: 1989, points: 140 },
  { id: "date-da10", type: "date", theme: "Dessin animé", question: "En quelle année 'Aladdin' de Disney est-il sorti au cinéma ?", answer: 1992, points: 130 },
  { id: "date-da11", type: "date", theme: "Dessin animé", question: "En quelle année est sorti 'Monstres & Cie' ?", answer: 2001, points: 110 },
  { id: "date-da12", type: "date", theme: "Dessin animé", question: "En quelle année est sorti le film d'animation 'Ratatouille' ?", answer: 2007, points: 100 },
  { id: "date-da13", type: "date", theme: "Dessin animé", question: "En quelle année le film 'Vice-Versa' (Inside Out) est-il sorti ?", answer: 2015, points: 100 },
  { id: "date-da14", type: "date", theme: "Dessin animé", question: "En quelle année 'Les Indestructibles' est-il sorti au cinéma ?", answer: 2004, points: 100 },
  { id: "date-da15", type: "date", theme: "Dessin animé", question: "En quelle année est sorti le film d'animation 'Coco' ?", answer: 2017, points: 100 },

  // --- MYTHOLOGIE ---
  { id: "date-my1", type: "date", theme: "Mythologie", question: "En quelle année (approx.) a été rédigée l'Iliade d'Homère ?", answer: -750, points: 240 },
  { id: "date-my2", type: "date", theme: "Mythologie", question: "En quelle année (approx.) a été rédigée l'Odyssée ?", answer: -720, points: 240 },
  { id: "date-my3", type: "date", theme: "Mythologie", question: "En quelle année (approx.) la guerre de Troie est-elle censée avoir eu lieu ?", answer: -1200, points: 280 },
  { id: "date-my4", type: "date", theme: "Mythologie", question: "En quelle année (approx.) Rome aurait-elle été fondée selon la légende de Romulus et Rémus ?", answer: -753, points: 210 },
  { id: "date-my5", type: "date", theme: "Mythologie", question: "En quelle année (approx.) Hésiode a-t-il écrit la Théogonie ?", answer: -700, points: 250 },
  { id: "date-my6", type: "date", theme: "Mythologie", question: "En quelle année (approx.) ont été construits les premiers temples dédiés à Zeus à Olympie ?", answer: -600, points: 230 },
  { id: "date-my7", type: "date", theme: "Mythologie", question: "En quelle année (approx.) les Jeux Olympiques antiques ont-ils été instaurés en l'honneur de Zeus ?", answer: -776, points: 220 },
  { id: "date-my8", type: "date", theme: "Mythologie", question: "En quelle année (approx.) a été écrite la légende de Gilgamesh ?", answer: -2100, points: 280 },
  { id: "date-my9", type: "date", theme: "Mythologie", question: "En quelle année (approx.) la mythologie nordique a-t-elle été retranscrite dans l’Edda poétique ?", answer: 1200, points: 210 },
  { id: "date-my10", type: "date", theme: "Mythologie", question: "En quelle année (approx.) Snorri Sturluson a-t-il écrit l’Edda en prose ?", answer: 1220, points: 210 },
  { id: "date-my11", type: "date", theme: "Mythologie", question: "En quelle année (approx.) la guerre de Troie se serait-elle terminée ?", answer: -1180, points: 260 },
  { id: "date-my12", type: "date", theme: "Mythologie", question: "En quelle année (approx.) Homère aurait-il vécu ?", answer: -800, points: 220 },
  { id: "date-my13", type: "date", theme: "Mythologie", question: "En quelle année (approx.) ont été instaurés les mystères d'Éleusis ?", answer: -600, points: 250 },
  { id: "date-my14", type: "date", theme: "Mythologie", question: "En quelle année (approx.) les premiers récits de mythologie égyptienne ont-ils été écrits ?", answer: -2600, points: 300 },
  { id: "date-my15", type: "date", theme: "Mythologie", question: "En quelle année (approx.) a été compilée l’Edda poétique ?", answer: 1270, points: 220 },
  { id: "date-my16", type: "date", theme: "Mythologie", question: "En quelle année (approx.) a été écrit le mythe de Persée et Méduse ?", answer: -700, points: 240 },
  { id: "date-my17", type: "date", theme: "Mythologie", question: "En quelle année (approx.) le culte de Dionysos s’est-il développé en Grèce ?", answer: -800, points: 240 },
  { id: "date-my18", type: "date", theme: "Mythologie", question: "En quelle année (approx.) le mythe du Ragnarök a-t-il été écrit ?", answer: 1200, points: 230 },
  { id: "date-my19", type: "date", theme: "Mythologie", question: "En quelle année (approx.) les premières pyramides liées à Osiris ont-elles été construites ?", answer: -2600, points: 300 },
  { id: "date-my20", type: "date", theme: "Mythologie", question: "En quelle année (approx.) le mythe d’Ulysse a-t-il été raconté pour la première fois ?", answer: -700, points: 240 },

  // --- MUSIQUE ---
  { id: "date-mu1", type: "date", theme: "Musique", question: "En quelle année est mort Jean-Sébastien Bach ?", answer: 1750, points: 150 },
  { id: "date-mu2", type: "date", theme: "Musique", question: "En quelle année Wolfgang Amadeus Mozart est-il décédé ?", answer: 1791, points: 150 },
  { id: "date-mu3", type: "date", theme: "Musique", question: "En quelle année la 9ème symphonie de Beethoven a-t-elle été jouée pour la première fois ?", answer: 1824, points: 180 },
  { id: "date-mu4", type: "date", theme: "Musique", question: "En quelle année Adolphe Sax a-t-il déposé le brevet du saxophone ?", answer: 1846, points: 180 },
  { id: "date-mu5", type: "date", theme: "Musique", question: "En quelle année Frédéric Chopin est-il mort à Paris ?", answer: 1849, points: 150 },
  { id: "date-mu6", type: "date", theme: "Musique", question: "En quelle année Thomas Edison a-t-il inventé le phonographe ?", answer: 1877, points: 180 },
  { id: "date-mu7", type: "date", theme: "Musique", question: "En quelle année a eu lieu la première du 'Sacre du printemps' de Stravinsky ?", answer: 1913, points: 200 },
  { id: "date-mu8", type: "date", theme: "Musique", question: "En quelle année a eu lieu la toute première édition du Concours Eurovision de la chanson ?", answer: 1956, points: 200 },
  { id: "date-mu9", type: "date", theme: "Musique", question: "En quelle année le groupe The Rolling Stones s'est-il formé ?", answer: 1962, points: 150 },
  { id: "date-mu10", type: "date", theme: "Musique", question: "En quelle année Édith Piaf est-elle décédée ?", answer: 1963, points: 120 },
  { id: "date-mu11", type: "date", theme: "Musique", question: "En quelle année s'est tenu le festival de Woodstock ?", answer: 1969, points: 100 },
  { id: "date-mu12", type: "date", theme: "Musique", question: "En quelle année les Beatles ont-ils officiellement annoncé leur séparation ?", answer: 1970, points: 100 },
  { id: "date-mu13", type: "date", theme: "Musique", question: "En quelle année Jimi Hendrix est-il décédé à l'âge de 27 ans ?", answer: 1970, points: 140 },
  { id: "date-mu14", type: "date", theme: "Musique", question: "En quelle année Serge Gainsbourg a-t-il sorti l'album 'Histoire de Melody Nelson' ?", answer: 1971, points: 190 },
  { id: "date-mu15", type: "date", theme: "Musique", question: "En quelle année est sorti l'album culte 'The Dark Side of the Moon' de Pink Floyd ?", answer: 1973, points: 130 },
  { id: "date-mu16", type: "date", theme: "Musique", question: "En quelle année le groupe ABBA a-t-il remporté l'Eurovision avec le titre 'Waterloo' ?", answer: 1974, points: 120 },
  { id: "date-mu17", type: "date", theme: "Musique", question: "En quelle année Queen a-t-il sorti le morceau 'Bohemian Rhapsody' ?", answer: 1975, points: 120 },
  { id: "date-mu18", type: "date", theme: "Musique", question: "En quelle année est sorti le premier album des Ramones, marquant les débuts du punk ?", answer: 1976, points: 180 },
  { id: "date-mu19", type: "date", theme: "Musique", question: "En quelle année Elvis Presley est-il mort dans sa demeure de Graceland ?", answer: 1977, points: 100 },
  { id: "date-mu20", type: "date", theme: "Musique", question: "En quelle année est décédé Claude François ?", answer: 1978, points: 100 },
  { id: "date-mu21", type: "date", theme: "Musique", question: "En quelle année Sony a-t-il commercialisé le tout premier Walkman ?", answer: 1979, points: 150 },
  { id: "date-mu22", type: "date", theme: "Musique", question: "En quelle année John Lennon a-t-il été assassiné à New York ?", answer: 1980, points: 110 },
  { id: "date-mu23", type: "date", theme: "Musique", question: "En quelle année la chaîne musicale MTV a-t-elle été lancée ?", answer: 1981, points: 120 },
  { id: "date-mu24", type: "date", theme: "Musique", question: "En quelle année Michael Jackson a-t-il sorti l'album 'Thriller' ?", answer: 1982, points: 80 },
  { id: "date-mu25", type: "date", theme: "Musique", question: "En quelle année le format Disque Compact (CD) a-t-il été lancé sur le marché ?", answer: 1982, points: 140 },
  { id: "date-mu26", type: "date", theme: "Musique", question: "En quelle année Prince a-t-il sorti le film et l'album 'Purple Rain' ?", answer: 1984, points: 120 },
  { id: "date-mu27", type: "date", theme: "Musique", question: "En quelle année s'est déroulé le double concert caritatif 'Live Aid' ?", answer: 1985, points: 150 },
  { id: "date-mu28", type: "date", theme: "Musique", question: "En quelle année Daniel Balavoine est-il décédé lors du Paris-Dakar ?", answer: 1986, points: 140 },
  { id: "date-mu29", type: "date", theme: "Musique", question: "En quelle année est sorti l'album 'Nevermind' de Nirvana ?", answer: 1991, points: 100 },
  { id: "date-mu30", type: "date", theme: "Musique", question: "En quelle année Freddie Mercury, leader de Queen, est-il décédé ?", answer: 1991, points: 100 },
  { id: "date-mu31", type: "date", theme: "Musique", question: "En quelle année le format audio MP3 a-t-il été officiellement finalisé ?", answer: 1995, points: 210 },
  { id: "date-mu32", type: "date", theme: "Musique", question: "En quelle année Daft Punk a-t-il sorti son premier album 'Homework' ?", answer: 1997, points: 170 },
  { id: "date-mu33", type: "date", theme: "Musique", question: "En quelle année est sorti le tube '...Baby One More Time' de Britney Spears ?", answer: 1998, points: 80 },
  { id: "date-mu34", type: "date", theme: "Musique", question: "En quelle année le service de partage Napster a-t-il été créé ?", answer: 1999, points: 180 },
  { id: "date-mu35", type: "date", theme: "Musique", question: "En quelle année Apple a-t-il inauguré l'iTunes Store ?", answer: 2003, points: 120 },
  { id: "date-mu36", type: "date", theme: "Musique", question: "En quelle année la plateforme Spotify a-t-elle été lancée ?", answer: 2008, points: 120 },
  { id: "date-mu37", type: "date", theme: "Musique", question: "En quelle année la chanteuse Amy Winehouse est-elle décédée ?", answer: 2011, points: 100 },
  { id: "date-mu38", type: "date", theme: "Musique", question: "En quelle année David Bowie nous a-t-il quittés ?", answer: 2016, points: 100 },
  { id: "date-mu39", type: "date", theme: "Musique", question: "En quelle année Bob Dylan a-t-il reçu le prix Nobel de littérature ?", answer: 2016, points: 150 },
  { id: "date-mu40", type: "date", theme: "Musique", question: "En quelle année Johnny Hallyday est-il décédé ?", answer: 2017, points: 60 }
];