import type { QuizQuestion } from "../quiz-bank";

export const dateQuestions: QuizQuestion[] = [
  { id: "date1", type: "date", theme: "Histoire", question: "En quelle année le Titanic a-t-il coulé ?", answer: 1912, points: 150 },
  { id: "date2", type: "date", theme: "Histoire", question: "En quelle année a eu lieu la Révolution Française ?", answer: 1789, points: 150 },
  { id: "date3", type: "date", theme: "Histoire", question: "En quelle année l'homme a-t-il marché sur la Lune ?", answer: 1969, points: 150 },
  { id: "date4", type: "date", theme: "Culture G", question: "En quelle année est sorti le tout premier iPhone ?", answer: 2007, points: 150 },
  { id: "date5", type: "date", theme: "Histoire", question: "En quelle année s'est terminée la Seconde Guerre mondiale ?", answer: 1945, points: 150 },
  { id: "date6", type: "date", theme: "Histoire", question: "En quelle année a eu lieu la chute du mur de Berlin ?", answer: 1989, points: 150 },
  { id: "date7", type: "date", theme: "Culture G", question: "En quelle année est sorti le premier film Star Wars au cinéma ?", answer: 1977, points: 150 },
  { id: "date8", type: "date", theme: "Histoire", question: "En quelle année Christophe Colomb a-t-il découvert l'Amérique ?", answer: 1492, points: 150 },
  { id: "date9", type: "date", theme: "Culture G", question: "En quelle année la France a-t-elle gagné sa première Coupe du Monde de foot ?", answer: 1998, points: 150 },
  { id: "date10", type: "date", theme: "Culture G", question: "En quelle année a été lancée la console PlayStation 1 en Europe ?", answer: 1995, points: 150 },
  { id: "date11", type: "date", theme: "Histoire", question: "En quelle année l'Euro a-t-il été mis en circulation ?", answer: 2002, points: 150 },
  { id: "date12", type: "date", theme: "Culture G", question: "En quelle année Facebook a-t-il été créé ?", answer: 2004, points: 150 },
  { id: "date13", type: "date", theme: "Histoire", question: "En quelle année a eu lieu l'attentat des tours jumelles (9/11) ?", answer: 2001, points: 120 },
  { id: "date14", type: "date", theme: "Histoire", question: "En quelle année Napoléon Ier est-il mort à Sainte-Hélène ?", answer: 1821, points: 180 },
  { id: "date15", type: "date", theme: "Histoire", question: "En quelle année a été signée la Déclaration d'Indépendance des USA ?", answer: 1776, points: 200 },
  { id: "date16", type: "date", theme: "Histoire", question: "En quelle année a été inaugurée la Tour Eiffel ?", answer: 1889, points: 150 },
  { id: "date17", type: "date", theme: "Culture G", question: "En quelle année a été lancé le premier iPhone ?", answer: 2007, points: 120 },
  { id: "date18", type: "date", theme: "Histoire", question: "En quelle année s'est terminé le règne de Louis XIV ?", answer: 1715, points: 200 },
  { id: "date19", type: "date", theme: "Histoire", question: "En quelle année l'Algérie est-elle devenue indépendante ?", answer: 1962, points: 150 },
  { id: "date20", type: "date", theme: "Culture G", question: "En quelle année est mort Michael Jackson ?", answer: 2009, points: 120 },
  { id: "date21", type: "date", theme: "Culture G", question: "En quelle année a été inventé le World Wide Web (Web) ?", answer: 1989, points: 180 },
  { id: "date22", type: "date", theme: "Histoire", question: "En quelle année l'esclavage a-t-il été définitivement aboli en France ?", answer: 1848, points: 200 },
  { id: "date23", type: "date", theme: "Sciences", question: "En quelle année a été lancé le télescope spatial Hubble ?", answer: 1990, points: 150 },
  { id: "date24", type: "date", theme: "Histoire", question: "En quelle année l'URSS a-t-elle été dissoute ?", answer: 1991, points: 150 },
  { id: "date25", type: "date", theme: "Histoire", question: "En quelle année a eu lieu le premier vol des frères Wright ?", answer: 1903, points: 200 },
  { id: "date26", type: "date", theme: "Histoire", question: "En quelle année Nelson Mandela a-t-il été libéré de prison ?", answer: 1990, points: 180 },
  { id: "date27", type: "date", theme: "Histoire", question: "En quelle année a débuté la guerre du Vietnam ?", answer: 1955, points: 200 },
  { id: "date28", type: "date", theme: "Histoire", question: "En quelle année a été fondé l'empire romain ?", answer: -27, points: 250 },
  { id: "date29", type: "date", theme: "Histoire", question: "En quelle année a commencé la construction de la pyramide de Khéops (environ) ?", answer: -2560, points: 250 },
  { id: "date30", type: "date", theme: "Histoire", question: "En quelle année l'esclavage a-t-il été aboli aux États-Unis ?", answer: 1865, points: 150 },
  { id: "date31", type: "date", theme: "Histoire", question: "En quelle année a été fondée l'ONU ?", answer: 1945, points: 100 },
  { id: "date32", type: "date", theme: "Sciences", question: "En quelle année Einstein a-t-il publié la théorie de la relativité générale ?", answer: 1915, points: 180 },
  { id: "date33", type: "date", theme: "Sciences", question: "En quelle année a eu lieu la première transplantation cardiaque ?", answer: 1967, points: 200 },
  { id: "date34", type: "date", theme: "Histoire", question: "En quelle année s'est terminé l'Empire Romain d'Occident ?", answer: 476, points: 150 },
  { id: "date35", type: "date", theme: "Histoire", question: "En quelle année a été lancé le premier satellite artificiel, Spoutnik ?", answer: 1957, points: 150 },
  { id: "date36", type: "date", theme: "Sciences", question: "En quelle année la structure de l'ADN a-t-elle été découverte ?", answer: 1953, points: 180 },
  { id: "date-sp1", type: "date", theme: "Sport", question: "En quelle année ont eu lieu les Jeux Olympiques d'été à Pékin ?", answer: 2008, points: 180 },
  { id: "date-sp2", type: "date", theme: "Sport", question: "En quelle année l'équipe de France de football a gagné sa deuxième étoile (Coupe du monde) ?", answer: 2018, points: 150 },
  { id: "date-da1", type: "date", theme: "Dessin animé", question: "En quelle année est sorti le tout premier film d'animation 'Toy Story' ?", answer: 1995, points: 200 },
  { id: "date-da2", type: "date", theme: "Dessin animé", question: "En quelle année Mickey Mouse a-t-il fait sa toute première apparition à l'écran ?", answer: 1928, points: 250 },
  { id: "date-sp3", type: "date", theme: "Sport", question: "En quelle année ont eu lieu les premiers Jeux Olympiques de l'ère moderne (à Athènes) ?", answer: 1896, points: 250 },
  { id: "date-sp4", type: "date", theme: "Sport", question: "En quelle année a eu lieu la toute première édition du Tour de France cycliste ?", answer: 1903, points: 200 },
  { id: "date-sp5", type: "date", theme: "Sport", question: "En quelle année l'équipe de France a-t-elle remporté sa PREMIÈRE Coupe du Monde de football ?", answer: 1998, points: 150 },
  { id: "date-sp6", type: "date", theme: "Sport", question: "En quelle année la ligue américaine de basket-ball (NBA) a-t-elle été créée ?", answer: 1946, points: 200 },
  { id: "date-sp7", type: "date", theme: "Sport", question: "En quelle année Usain Bolt a-t-il pulvérisé le record du monde du 100m en 9.58 secondes ?", answer: 2009, points: 180 },
  { id: "date-da3", type: "date", theme: "Dessin animé", question: "En quelle année est sorti 'Blanche-Neige', le tout premier long métrage d'animation Disney ?", answer: 1937, points: 250 },
  { id: "date-da4", type: "date", theme: "Dessin animé", question: "En quelle année a été diffusé le tout premier épisode régulier des Simpson aux États-Unis ?", answer: 1989, points: 200 },
  { id: "date-da5", type: "date", theme: "Dessin animé", question: "En quelle année est sorti au cinéma le premier film 'Shrek' ?", answer: 2001, points: 180 },
  { id: "date-da6", type: "date", theme: "Dessin animé", question: "En quelle année le célèbre manga 'Dragon Ball' a-t-il été publié pour la toute première fois ?", answer: 1984, points: 200 },
  { id: "date-da7", type: "date", theme: "Dessin animé", question: "En quelle année est sorti le magnifique chef-d'œuvre de Ghibli 'Le Voyage de Chihiro' ?", answer: 2001, points: 180 },

];