import type { QuizQuestion } from "../quiz-bank";

export const estimationQuestions: QuizQuestion[] = [
  // --- GÉOGRAPHIE ---
  { id: "est5", type: "estimation", theme: "Géographie", question: "Quelle est la hauteur du Mont Blanc (en mètres, mesure stricte) ?", answer: 4805, points: 150 },
  { id: "est10", type: "estimation", theme: "Géographie", question: "Combien de pays compte l'ONU ?", answer: 193, points: 120 },
  { id: "est15", type: "estimation", theme: "Géographie", question: "Combien de kilomètres fait le fleuve Amazone (environ) ?", answer: 6400, points: 130 },
  { id: "est17", type: "estimation", theme: "Géographie", question: "Quelle est la population mondiale en milliards (2024) ?", answer: 8, points: 80 },
  { id: "est19", type: "estimation", theme: "Géographie", question: "Combien de pays y a-t-il officiellement en Afrique ?", answer: 54, points: 110 },
  { id: "est20", type: "estimation", theme: "Géographie", question: "Quelle est la longueur de la Grande Muraille de Chine en km ?", answer: 21196, points: 250 },
  { id: "est22", type: "estimation", theme: "Géographie", question: "Combien d'États compte les États-Unis d'Amérique ?", answer: 50, points: 60 },
  { id: "est25", type: "estimation", theme: "Géographie", question: "Combien d'États membres compte l'Union Européenne (en 2024) ?", answer: 27, points: 100 },
  { id: "est27", type: "estimation", theme: "Géographie", question: "Quelle est la profondeur moyenne de l'océan (en mètres) ?", answer: 3700, points: 160 },
  { id: "est28", type: "estimation", theme: "Géographie", question: "Combien de pays ont le français comme langue officielle ?", answer: 29, points: 140 },
  { id: "est32", type: "estimation", theme: "Géographie", question: "En kilomètres, quelle est la circonférence de la Terre ?", answer: 40075, points: 180 },
  { id: "est33b", type: "estimation", theme: "Géographie", question: "Combien de continents compte-t-on sur Terre ?", answer: 7, points: 60 },
  { id: "est34b", type: "estimation", theme: "Géographie", question: "Combien de kilomètres mesure l’équateur (environ) ?", answer: 40075, points: 180 },
  { id: "est35b", type: "estimation", theme: "Géographie", question: "Combien de pays composent officiellement l’Amérique du Sud ?", answer: 12, points: 110 },
  { id: "est36b", type: "estimation", theme: "Géographie", question: "Combien de temps (en heures) faut-il environ pour faire le tour de la Terre en avion de ligne sans escale ?", answer: 48, points: 150 },
  { id: "est37b", type: "estimation", theme: "Géographie", question: "À combien de kilomètres environ se situe la Lune de la Terre à son point le plus proche ?", answer: 363000, points: 200 },
  { id: "est38b", type: "estimation", theme: "Géographie", question: "Combien de fuseaux horaires traverse la Russie ?", answer: 11, points: 130 },
  { id: "est39b", type: "estimation", theme: "Géographie", question: "Combien de pays ont une frontière avec la France métropolitaine ?", answer: 8, points: 120 },
  { id: "est40b", type: "estimation", theme: "Géographie", question: "Combien d’habitants compte la France (en millions, ordre de grandeur) ?", answer: 68, points: 90 },
  { id: "est41b", type: "estimation", theme: "Géographie", question: "À combien de mètres culmine le mont Everest (environ) ?", answer: 8849, points: 150 },
  { id: "est42b", type: "estimation", theme: "Géographie", question: "Combien d’îles composent l’archipel du Japon (environ) ?", answer: 6800, points: 220 },
  { id: "est43b", type: "estimation", theme: "Géographie", question: "Combien de kilomètres séparent Paris et New York (en ligne droite, environ) ?", answer: 5850, points: 160 },
  { id: "est44b", type: "estimation", theme: "Géographie", question: "En pourcentage, quelle proportion de la surface de la Terre est recouverte par les océans ?", answer: 71, points: 100 },
  { id: "est45b", type: "estimation", theme: "Géographie", question: "Combien de pays partagent une frontière terrestre avec la Chine ?", answer: 14, points: 170 },
  { id: "est46b", type: "estimation", theme: "Géographie", question: "En kilomètres, quelle est la longueur approximative du Nil ?", answer: 6650, points: 130 },
  { id: "est47b", type: "estimation", theme: "Géographie", question: "À combien de mètres sous le niveau de la mer se situe la mer Morte (environ) ?", answer: -430, points: 180 },
  { id: "est48b", type: "estimation", theme: "Géographie", question: "Combien de pays composent officiellement l’Amérique du Nord ?", answer: 23, points: 140 },

  // --- SCIENCES ---
  { id: "est2", type: "estimation", theme: "Sciences", question: "Combien de jours l'humain a-t-il passé dans l'espace en cumulé ? (à la louche)", answer: 29000, points: 240 },
  { id: "est3", type: "estimation", theme: "Sciences", question: "Combien d'os y a-t-il dans le corps d'un adulte humain ?", answer: 206, points: 110 },
  { id: "est4", type: "estimation", theme: "Sciences", question: "Combien de cœurs possède une pieuvre ?", answer: 3, points: 100 },
  { id: "est8", type: "estimation", theme: "Sciences", question: "Quelle est la distance Terre-Lune (en km, moyenne) ?", answer: 384400, points: 150 },
  { id: "est9", type: "estimation", theme: "Sciences", question: "Combien de pattes a un mille-pattes commun (en moyenne) ?", answer: 300, points: 160 },
  { id: "est13", type: "estimation", theme: "Sciences", question: "Combien de temps (en jours) dure la gestation d'une éléphante ?", answer: 640, points: 150 },
  { id: "est16", type: "estimation", theme: "Sciences", question: "Combien de dents possède un humain adulte (sans dents de sagesse) ?", answer: 28, points: 110 },
  { id: "est21", type: "estimation", theme: "Sciences", question: "Combien de jours dure une année sur Mars ?", answer: 687, points: 170 },
  { id: "est23", type: "estimation", theme: "Sciences", question: "Quelle est la température en surface du Soleil (en degrés Celsius) ?", answer: 5500, points: 180 },
  { id: "est24", type: "estimation", theme: "Sciences", question: "Combien de litres de sang contient le corps d'un adulte (environ) ?", answer: 5, points: 100 },
  { id: "est33", type: "estimation", theme: "Sciences", question: "Combien d'atomes d'oxygène y a-t-il dans une molécule d'eau ?", answer: 1, points: 50 },
  { id: "est34", type: "estimation", theme: "Sciences", question: "Combien d'éléments contient le tableau périodique actuel ?", answer: 118, points: 130 },
  { id: "est35", type: "estimation", theme: "Sciences", question: "Quelle est la distance entre la Terre et Mars (en millions de km, au plus proche) ?", answer: 55, points: 180 },
  { id: "est36", type: "estimation", theme: "Sciences", question: "Combien de muscles possède le corps humain (environ) ?", answer: 650, points: 150 },
  { id: "est37", type: "estimation", theme: "Sciences", question: "Combien de temps met la lumière du Soleil pour atteindre la Terre (en secondes) ?", answer: 499, points: 180 },
  { id: "est38", type: "estimation", theme: "Sciences", question: "Quel est le record du monde de durée de sommeil pour un humain (en heures) ?", answer: 264, points: 200 },
  { id: "est39", type: "estimation", theme: "Sciences", question: "Combien de battements de cœur un humain fait-il en moyenne par minute au repos ?", answer: 70, points: 70 },
  { id: "est40", type: "estimation", theme: "Sciences", question: "Quelle est la température du zéro absolu (en degrés Celsius) ?", answer: -273, points: 140 },
  { id: "est41", type: "estimation", theme: "Sciences", question: "Combien de vertèbres compose la colonne dorsale humaine ?", answer: 33, points: 160 },
  { id: "est48b", type: "estimation", theme: "Sciences", question: "À combien de kilomètres par heure la lumière se déplace-t-elle dans le vide (en millions de km/h, arrondi) ?", answer: 1080, points: 210 },
  { id: "est49b", type: "estimation", theme: "Sciences", question: "Combien de paires de chromosomes possède un humain ?", answer: 23, points: 110 },
  { id: "est50b", type: "estimation", theme: "Sciences", question: "Combien de litres d’air un humain respire-t-il en une journée (environ) ?", answer: 11000, points: 190 },
  { id: "est51b", type: "estimation", theme: "Sciences", question: "Combien de temps (en jours) faut-il pour que la Terre fasse un tour complet autour du Soleil ?", answer: 365, points: 50 },
  { id: "est52b", type: "estimation", theme: "Sciences", question: "Combien de dents de lait un enfant possède-t-il en tout ?", answer: 20, points: 100 },
  { id: "est53b", type: "estimation", theme: "Sciences", question: "Combien de litres d’eau faut-il boire environ par jour pour un adulte (recommandation classique) ?", answer: 2, points: 60 },
  { id: "est54b", type: "estimation", theme: "Sciences", question: "Combien de temps (en minutes) dure une rotation complète de la Terre sur elle-même, en réalité ?", answer: 1440, points: 130 },
  { id: "est55b", type: "estimation", theme: "Sciences", question: "Combien de neurones le cerveau humain contient-il environ (en milliards) ?", answer: 86, points: 210 },
  { id: "est56b", type: "estimation", theme: "Sciences", question: "À quelle température l’eau bout-elle au niveau de la mer (en degrés Celsius) ?", answer: 100, points: 50 },
  { id: "est57b", type: "estimation", theme: "Sciences", question: "Combien de temps (en minutes) met le sang pour faire un tour complet du corps au repos (environ) ?", answer: 1, points: 150 },
  { id: "est58b", type: "estimation", theme: "Sciences", question: "Combien de litres de salive produit un humain par jour (environ) ?", answer: 1, points: 170 },
  { id: "est59b", type: "estimation", theme: "Sciences", question: "Combien de doigts (pouces compris) un humain possède-t-il en tout ?", answer: 10, points: 40 },
  { id: "est60b", type: "estimation", theme: "Sciences", question: "À combien de degrés Celsius commence la fièvre chez l’adulte (température du corps) ?", answer: 38, points: 80 },
  { id: "est61b", type: "estimation", theme: "Sciences", question: "Combien de temps met la lumière de la Lune (réfléchie du Soleil) pour nous parvenir (en secondes, ordre de grandeur) ?", answer: 1, points: 180 },
  { id: "est62b", type: "estimation", theme: "Sciences", question: "Combien de litres d’air peuvent contenir les poumons d’un adulte à pleine inspiration (environ) ?", answer: 6, points: 160 },
  { id: "est63b", type: "estimation", theme: "Sciences", question: "Combien de temps (en minutes) faut-il pour cuire un œuf dur dans l’eau bouillante (environ) ?", answer: 10, points: 70 },
  { id: "est64b", type: "estimation", theme: "Sciences", question: "Combien d’années (en millions) séparent les dinosaures de l’apparition de l’humain moderne (ordre de grandeur) ?", answer: 65, points: 150 },
  { id: "est65b", type: "estimation", theme: "Sciences", question: "Combien de temps (en secondes) met la lumière du Soleil pour atteindre la Terre ?", answer: 500, points: 180 },

  // --- CULTURE G ---
  { id: "est1", type: "estimation", theme: "Culture G", question: "Combien pèse la Tour Eiffel (en tonnes) ?", answer: 10100, points: 170 },
  { id: "est6", type: "estimation", theme: "Culture G", question: "Combien d'épisodes compte la série Les Simpson (environ, fin 2023) ?", answer: 750, points: 130 },
  { id: "est7", type: "estimation", theme: "Culture G", question: "En minutes, combien de temps dure le film Titanic ?", answer: 194, points: 130 },
  { id: "est11", type: "estimation", theme: "Culture G", question: "Quelle est la vitesse maximale enregistrée par Usain Bolt (en km/h) ?", answer: 44, points: 120 },
  { id: "est12", type: "estimation", theme: "Culture G", question: "Combien de touches y a-t-il sur un piano classique ?", answer: 88, points: 150 },
  { id: "est14", type: "estimation", theme: "Culture G", question: "Combien de mètres mesure la plus grande statue du monde (Statue de l'Unité) ?", answer: 182, points: 180 },
  { id: "est18", type: "estimation", theme: "Culture G", question: "Combien de marches compte la Tour Eiffel jusqu'au sommet ?", answer: 1665, points: 210 },
  { id: "est26", type: "estimation", theme: "Culture G", question: "Combien de secondes y a-t-il dans une journée ?", answer: 86400, points: 140 },
  { id: "est29", type: "estimation", theme: "Culture G", question: "Combien d'anneaux compose le logo des Jeux Olympiques ?", answer: 5, points: 50 },
  { id: "est30", type: "estimation", theme: "Culture G", question: "Combien de pièces y a-t-il au début d'une partie d'échecs (total) ?", answer: 32, points: 90 },
  { id: "est31", type: "estimation", theme: "Culture G", question: "Quelle est la longueur de la piscine olympique (en mètres) ?", answer: 50, points: 90 },
  { id: "est65b", type: "estimation", theme: "Culture G", question: "Combien de lettres compte l’alphabet français ?", answer: 26, points: 40 },
  { id: "est66b", type: "estimation", theme: "Culture G", question: "Combien de jours compte une année bissextile ?", answer: 366, points: 70 },
  { id: "est67b", type: "estimation", theme: "Culture G", question: "Combien de jours séparent Noël de Pâques (environ, sur une année classique) ?", answer: 100, points: 130 },
  { id: "est68b", type: "estimation", theme: "Culture G", question: "Combien de saisons compte une année ?", answer: 4, points: 30 },
  { id: "est69b", type: "estimation", theme: "Culture G", question: "Combien d’années séparent l’an 0 de l’an 2024 ?", answer: 2024, points: 40 },
  { id: "est70b", type: "estimation", theme: "Culture G", question: "Combien de personnes siègent à l’Assemblée nationale française (députés) ?", answer: 577, points: 160 },
  { id: "est71b", type: "estimation", theme: "Culture G", question: "Combien d’anneaux doit-on collectionner pour gagner une vie supplémentaire dans Sonic (jeu vidéo classique) ?", answer: 100, points: 110 },
  { id: "est72b", type: "estimation", theme: "Culture G", question: "Combien d’années de mariage fête-t-on pour les noces d’or ?", answer: 50, points: 100 },
  { id: "est73b", type: "estimation", theme: "Culture G", question: "Combien de joueurs composent une équipe de handball sur le terrain ?", answer: 7, points: 110 },
  { id: "est74b", type: "estimation", theme: "Culture G", question: "Combien d’heures de décalage horaire séparent la France de New York (en hiver) ?", answer: 6, points: 100 },
  { id: "est75b", type: "estimation", theme: "Culture G", question: "Combien de cases y a-t-il sur un plateau de jeu de Monopoly classique (France) ?", answer: 40, points: 130 },
  { id: "est76b", type: "estimation", theme: "Culture G", question: "Combien de cartes contient un jeu de cartes classique (sans jokers) ?", answer: 52, points: 80 },
  { id: "est77b", type: "estimation", theme: "Culture G", question: "Combien de films composent la saga principale Harry Potter ?", answer: 8, points: 80 },
  { id: "est78b", type: "estimation", theme: "Culture G", question: "Combien de tomes contient la saga Harry Potter (livres principaux) ?", answer: 7, points: 80 },
  { id: "est79b", type: "estimation", theme: "Culture G", question: "Combien d’étoiles figurent sur le drapeau des États-Unis ?", answer: 50, points: 80 },
  { id: "est80b", type: "estimation", theme: "Culture G", question: "Combien de marches compte l’escalier d’un étage dans un immeuble standard (en moyenne) ?", answer: 15, points: 120 },

  // --- SPORT ---
  { id: "est-sp1", type: "estimation", theme: "Sport", question: "Combien de kilomètres fait un marathon (arrondi à l'entier) ?", answer: 42, points: 100 },
  { id: "est-sp2", type: "estimation", theme: "Sport", question: "Combien de joueurs composent une équipe de rugby à XV sur le terrain ?", answer: 15, points: 100 },
  { id: "est-sp3", type: "estimation", theme: "Sport", question: "Quelle est la hauteur officielle d'un panier de basket en NBA (en centimètres) ?", answer: 305, points: 170 },
  { id: "est-sp4", type: "estimation", theme: "Sport", question: "Combien de trous compte un parcours de golf de compétition complet ?", answer: 18, points: 110 },
  { id: "est-sp5", type: "estimation", theme: "Sport", question: "Combien de quilles doit-on faire tomber au bowling en un seul lancer pour faire un strike ?", answer: 10, points: 80 },
  { id: "est-sp6", type: "estimation", theme: "Sport", question: "En kilomètres, quelle est la distance d'un semi-marathon (arrondi à l'entier) ?", answer: 21, points: 90 },
  { id: "est-sp7", type: "estimation", theme: "Sport", question: "Combien de minutes dure un quart-temps en NBA ?", answer: 12, points: 110 },
  { id: "est-sp8", type: "estimation", theme: "Sport", question: "Combien de joueurs composent une équipe de football américain sur le terrain ?", answer: 11, points: 110 },
  { id: "est-sp9", type: "estimation", theme: "Sport", question: "Combien de sets doit-on gagner pour remporter un match en Grand Chelem masculin (format classique) ?", answer: 3, points: 100 },
  { id: "est-sp10", type: "estimation", theme: "Sport", question: "Combien de minutes dure un match de football (hors prolongations) ?", answer: 90, points: 60 },
  { id: "est-sp11b", type: "estimation", theme: "Sport", question: "Combien de points faut-il marquer pour gagner un set au volley (hors tie-break) ?", answer: 25, points: 110 },
  { id: "est-sp12b", type: "estimation", theme: "Sport", question: "Combien de joueurs une équipe de volley a-t-elle sur le terrain ?", answer: 6, points: 100 },
  { id: "est-sp13b", type: "estimation", theme: "Sport", question: "Combien de tours compte un 100 mètres en athlétisme sur une piste standard ?", answer: 0, points: 200 },
  { id: "est-sp14b", type: "estimation", theme: "Sport", question: "Combien de points vaut un essai transformé au rugby à XV ?", answer: 7, points: 120 },
  { id: "est-sp15b", type: "estimation", theme: "Sport", question: "Combien d’arbitres principaux officiels se trouvent sur le terrain au basket (NBA) ?", answer: 3, points: 150 },
  { id: "est-sp16b", type: "estimation", theme: "Sport", question: "Combien de jeux minimum faut-il gagner pour remporter un set au tennis (sans tie-break) ?", answer: 6, points: 110 },
  { id: "est-sp17b", type: "estimation", theme: "Sport", question: "Combien de périodes compte un match de hockey sur glace ?", answer: 3, points: 120 },
  { id: "est-sp18b", type: "estimation", theme: "Sport", question: "Combien de points vaut un touchdown au football américain ?", answer: 6, points: 120 },
  { id: "est-sp19b", type: "estimation", theme: "Sport", question: "Combien de minutes dure une mi-temps au football ?", answer: 45, points: 60 },

  // --- DESSIN ANIMÉ ---
  { id: "est-da1", type: "estimation", theme: "Dessin animé", question: "Combien y a-t-il de Dalmatiens dans le célèbre dessin animé de Disney ?", answer: 101, points: 50 },
  { id: "est-da2", type: "estimation", theme: "Dessin animé", question: "Combien de boules de cristal magiques faut-il réunir dans Dragon Ball ?", answer: 7, points: 70 },
  { id: "est-da3", type: "estimation", theme: "Dessin animé", question: "Combien d'émotions principales y a-t-il dans la tête de Riley dans le film 'Vice-Versa' (le 1er film) ?", answer: 5, points: 90 },
  { id: "est-da4", type: "estimation", theme: "Dessin animé", question: "Combien de doigts possède un Minion sur une seule main ?", answer: 3, points: 130 },
  { id: "est-da5", type: "estimation", theme: "Dessin animé", question: "Combien de fées marraines se penchent sur le berceau de La Belle au Bois Dormant ?", answer: 3, points: 120 },
  { id: "est-da6", type: "estimation", theme: "Dessin animé", question: "Combien de nains accompagnent Blanche-Neige ?", answer: 7, points: 40 },
  { id: "est-da7", type: "estimation", theme: "Dessin animé", question: "Combien de têtes possède le dragon 'Touffu' dans l'univers de Harry Potter ?", answer: 3, points: 110 },
  { id: "est-da8", type: "estimation", theme: "Dessin animé", question: "Combien de sept nains entourent Blanche-Neige ?", answer: 7, points: 40 },
  { id: "est-da9", type: "estimation", theme: "Dessin animé", question: "Combien de doigts Mickey Mouse montre-t-il en tout (mains visibles) ?", answer: 8, points: 160 },
  { id: "est-da10", type: "estimation", theme: "Dessin animé", question: "Combien de jouets principaux composent le groupe autour de Woody dans Toy Story 1 (ordre de grandeur) ?", answer: 10, points: 140 },
  { id: "est-da11", type: "estimation", theme: "Dessin animé", question: "Combien de louveteaux la mère de Simba a-t-elle dans Le Roi Lion (dans la portée qu’on voit au début) ?", answer: 1, points: 150 },
  { id: "est-da12", type: "estimation", theme: "Dessin animé", question: "Combien de sœurs Ariel la petite sirène possède-t-elle ?", answer: 6, points: 150 },
  { id: "est-da13", type: "estimation", theme: "Dessin animé", question: "Combien de Pokémon existaient dans la première génération de jeux vidéo ?", answer: 151, points: 170 },
  { id: "est-da14b", type: "estimation", theme: "Dessin animé", question: "Combien de dragons principaux la famille de Krokmou affronte-t-elle dans le premier film Dragons ?", answer: 1, points: 160 },
  { id: "est-da15b", type: "estimation", theme: "Dessin animé", question: "Combien de membres compte la famille Parr (Les Indestructibles) ?", answer: 5, points: 80 },

  // --- MYTHOLOGIE ---
  { id: "est-my1", type: "estimation", theme: "Mythologie", question: "Combien de dieux principaux composent l'Olympe grec ?", answer: 12, points: 110 },
  { id: "est-my2", type: "estimation", theme: "Mythologie", question: "Combien de travaux Héraclès (Hercule) a-t-accomplis ?", answer: 12, points: 110 },
  { id: "est-my3", type: "estimation", theme: "Mythologie", question: "Combien de têtes possède l’Hydre de Lerne au minimum selon les récits ?", answer: 9, points: 140 },
  { id: "est-my4", type: "estimation", theme: "Mythologie", question: "Combien de jours a duré le siège de Troie selon la légende (en années) ?", answer: 10, points: 120 },
  { id: "est-my5", type: "estimation", theme: "Mythologie", question: "Combien de Muses existe-t-il dans la mythologie grecque ?", answer: 9, points: 140 },
  { id: "est-my6", type: "estimation", theme: "Mythologie", question: "Combien de royaumes composent l’au-delà dans la mythologie nordique ?", answer: 9, points: 150 },
  { id: "est-my7", type: "estimation", theme: "Mythologie", question: "Combien de pommes d’or devaient être volées par Héraclès ?", answer: 3, points: 130 },
  { id: "est-my8", type: "estimation", theme: "Mythologie", question: "Combien de juges des Enfers existe-t-il dans la mythologie grecque ?", answer: 3, points: 170 },
  { id: "est-my9", type: "estimation", theme: "Mythologie", question: "Combien de têtes possède Cerbère ?", answer: 3, points: 90 },
  { id: "est-my10", type: "estimation", theme: "Mythologie", question: "Combien de géants ont tenté d’envahir l’Olympe lors de la Gigantomachie ?", answer: 24, points: 220 },
  { id: "est-my11", type: "estimation", theme: "Mythologie", question: "Combien de Titans principaux précèdent les dieux de l’Olympe ?", answer: 12, points: 130 },
  { id: "est-my12", type: "estimation", theme: "Mythologie", question: "Combien de cyclopes ont forgé la foudre de Zeus ?", answer: 3, points: 140 },
  { id: "est-my13", type: "estimation", theme: "Mythologie", question: "Combien de niveaux comporte le monde nordique (Yggdrasil) ?", answer: 9, points: 150 },
  { id: "est-my14", type: "estimation", theme: "Mythologie", question: "Combien de jours Ulysse met-il pour rentrer chez lui (en années) ?", answer: 10, points: 120 },
  { id: "est-my15", type: "estimation", theme: "Mythologie", question: "Combien de filles Danaos avait-il ?", answer: 50, points: 210 },
  { id: "est-my16", type: "estimation", theme: "Mythologie", question: "Combien de flèches Apollon utilise-t-il pour déclencher une peste dans l’Iliade ?", answer: 1, points: 230 },
  { id: "est-my17", type: "estimation", theme: "Mythologie", question: "Combien de gardiens surveillent le Tartare ?", answer: 1, points: 190 },
  { id: "est-my18", type: "estimation", theme: "Mythologie", question: "Combien de jours Perséphone passe-t-elle aux Enfers par an ?", answer: 180, points: 200 },
  { id: "est-my19", type: "estimation", theme: "Mythologie", question: "Combien de bras possède le géant Briarée ?", answer: 100, points: 220 },
  { id: "est-my20", type: "estimation", theme: "Mythologie", question: "Combien de dieux composent le panthéon égyptien majeur (approx.) ?", answer: 50, points: 190 },

  // --- MUSIQUE ---
  { id: "est-mu1", type: "estimation", theme: "Musique", question: "Combien de touches compte un piano standard ?", answer: 88, points: 150 },
  { id: "est-mu2", type: "estimation", theme: "Musique", question: "Combien de cordes possède une harpe de concert classique ?", answer: 47, points: 180 },
  { id: "est-mu3", type: "estimation", theme: "Musique", question: "Combien de symphonies achevées Ludwig van Beethoven a-t-il composées ?", answer: 9, points: 110 },
  { id: "est-mu4", type: "estimation", theme: "Musique", question: "Combien de millions d'exemplaires (estimation basse) s'est vendu l'album 'Thriller' de Michael Jackson ?", answer: 66, points: 130 },
  { id: "est-mu5", type: "estimation", theme: "Musique", question: "Combien de cordes possède une guitare électrique standard ?", answer: 6, points: 50 },
  { id: "est-mu6", type: "estimation", theme: "Musique", question: "En hertz (Hz), quelle est la fréquence standard du 'La' de référence ?", answer: 440, points: 160 },
  { id: "est-mu7", type: "estimation", theme: "Musique", question: "Combien de minutes dure environ la chanson 'Bohemian Rhapsody' de Queen ?", answer: 6, points: 110 },
  { id: "est-mu8", type: "estimation", theme: "Musique", question: "Combien de Grammy Awards Beyoncé a-t-elle remportés au cours de sa carrière (record absolu) ?", answer: 32, points: 140 },
  { id: "est-mu9", type: "estimation", theme: "Musique", question: "Combien de tuyaux possède environ le Grand Orgue de la cathédrale Notre-Dame de Paris ?", answer: 8000, points: 230 },
  { id: "est-mu10", type: "estimation", theme: "Musique", question: "Combien de cordes possède une balalaïka russe ?", answer: 3, points: 160 },
  { id: "est-mu11", type: "estimation", theme: "Musique", question: "À combien de personnes estime-t-on la foule présente au festival de Woodstock en 1969 ?", answer: 400000, points: 150 },
  { id: "est-mu12", type: "estimation", theme: "Musique", question: "Combien de morceaux Wolfgang Amadeus Mozart a-t-il répertoriés dans son catalogue (Catalogue Köchel) ?", answer: 626, points: 210 },
  { id: "est-mu13", type: "estimation", theme: "Musique", question: "Combien de pistons possède une trompette classique ?", answer: 3, points: 110 },
  { id: "est-mu14", type: "estimation", theme: "Musique", question: "Combien de cordes possède un violoncelle ?", answer: 4, points: 100 },
  { id: "est-mu15", type: "estimation", theme: "Musique", question: "Quelle était la capacité maximale de stockage d'un CD audio standard en minutes ?", answer: 74, points: 160 },
  { id: "est-mu16", type: "estimation", theme: "Musique", question: "Combien de chansons les Beatles ont-ils classées n°1 au Billboard Hot 100 américain ?", answer: 20, points: 170 },
  { id: "est-mu17", type: "estimation", theme: "Musique", question: "Combien de minutes dure la version studio de 'Echoes' de Pink Floyd ?", answer: 23, points: 180 },
  { id: "est-mu18", type: "estimation", theme: "Musique", question: "Combien d'instruments composent généralement un orchestre symphonique complet ?", answer: 100, points: 130 },
  { id: "est-mu19", type: "estimation", theme: "Musique", question: "Combien de cordes possède un sitar indien (modèle standard) ?", answer: 21, points: 190 },
  { id: "est-mu20", type: "estimation", theme: "Musique", question: "À combien de millions de dollars est estimé le violon Stradivarius le plus cher jamais vendu ?", answer: 16, points: 180 },
  { id: "est-mu21", type: "estimation", theme: "Musique", question: "Combien de notes différentes contient une gamme chromatique ?", answer: 12, points: 140 },
  { id: "est-mu22", type: "estimation", theme: "Musique", question: "Combien d’années se sont écoulées entre les deux derniers albums studio d’ABBA ?", answer: 40, points: 150 },
  { id: "est-mu23", type: "estimation", theme: "Musique", question: "Quel est le poids moyen (en kg) d'un piano à queue de concert ?", answer: 450, points: 160 },
  { id: "est-mu24", type: "estimation", theme: "Musique", question: "Combien d'albums studio Prince a-t-il publiés de son vivant ?", answer: 39, points: 200 },
  { id: "est-mu25", type: "estimation", theme: "Musique", question: "Combien de jours a duré l'enregistrement de l'album 'Please Please Me' des Beatles ?", answer: 1, points: 180 },
  { id: "est-mu26", type: "estimation", theme: "Musique", question: "Combien de musiciens composent un 'Octuor' ?", answer: 8, points: 100 },
  { id: "est-mu27", type: "estimation", theme: "Musique", question: "À combien d'exemplaires le baladeur Walkman s'est-il vendu durant son premier mois (approx.) ?", answer: 30000, points: 240 },
  { id: "est-mu28", type: "estimation", theme: "Musique", question: "Combien de secondes dure le silence dans l'œuvre célèbre '4'33' de John Cage ?", answer: 273, points: 200 },
  { id: "est-mu29", type: "estimation", theme: "Musique", question: "Combien de films Elvis Presley a-t-il tournés en tant qu'acteur ?", answer: 31, points: 180 },
  { id: "est-mu30", type: "estimation", theme: "Musique", question: "Combien de cordes trouve-t-on sur un ukulélé standard ?", answer: 4, points: 100 },
  { id: "est-mu31", type: "estimation", theme: "Musique", question: "Combien de musiciens composent un Big Band de Jazz classique ?", answer: 17, points: 160 },
  { id: "est-mu32", type: "estimation", theme: "Musique", question: "Combien de versions de 'Yesterday' ont été enregistrées par d'autres artistes (reprises) ?", answer: 3000, points: 200 },
  { id: "est-mu33", type: "estimation", theme: "Musique", question: "Combien d'années a-t-il fallu à Richard Wagner pour terminer son cycle de 'L'Anneau du Nibelung' ?", answer: 26, points: 220 },
  { id: "est-mu34", type: "estimation", theme: "Musique", question: "Combien de frette(s) possède un violon ?", answer: 0, points: 200 },
  { id: "est-mu35", type: "estimation", theme: "Musique", question: "Quelle est la durée en minutes du clip 'Thriller' de Michael Jackson ?", answer: 14, points: 120 },
  { id: "est-mu36", type: "estimation", theme: "Musique", question: "Combien de prix Nobel de Littérature ont été décernés à des musiciens ?", answer: 1, points: 150 },
  { id: "est-mu37", type: "estimation", theme: "Musique", question: "Combien de cordes possède une guitare basse standard ?", answer: 4, points: 100 },
  { id: "est-mu38", type: "estimation", theme: "Musique", question: "Combien de 'Chants du Cygne' composent le recueil posthume de Schubert ?", answer: 14, points: 190 },
  { id: "est-mu39", type: "estimation", theme: "Musique", question: "Combien de catégories différentes y a-t-il environ aux Grammy Awards chaque année ?", answer: 94, points: 180 },
  { id: "est-mu40", type: "estimation", theme: "Musique", question: "Combien de temps (en secondes) dure le plus long 'rot' musical enregistré ?", answer: 15, points: 250 }
];