import type { QuizQuestion } from "../quiz-bank";

export const estimationQuestions: QuizQuestion[] = [
  { id: "est1", type: "estimation", theme: "Culture G", question: "Combien pèse la Tour Eiffel (en tonnes) ?", answer: 10100, points: 100 },
  { id: "est2", type: "estimation", theme: "Sciences", question: "Combien de jours l'humain a-t-il passé dans l'espace en cumulé ? (à la louche)", answer: 29000, points: 100 },
  { id: "est3", type: "estimation", theme: "Sciences", question: "Combien d'os y a-t-il dans le corps d'un adulte humain ?", answer: 206, points: 100 },
  { id: "est4", type: "estimation", theme: "Sciences", question: "Combien de cœurs possède une pieuvre ?", answer: 3, points: 100 },
  { id: "est5", type: "estimation", theme: "Géographie", question: "Quelle est la hauteur du Mont Blanc (en mètres, mesure stricte) ?", answer: 4805, points: 100 },
  { id: "est6", type: "estimation", theme: "Culture G", question: "Combien d'épisodes compte la série Les Simpson (environ, fin 2023) ?", answer: 750, points: 100 },
  { id: "est7", type: "estimation", theme: "Culture G", question: "En minutes, combien de temps dure le film Titanic ?", answer: 194, points: 100 },
  { id: "est8", type: "estimation", theme: "Sciences", question: "Quelle est la distance Terre-Lune (en km, moyenne) ?", answer: 384400, points: 100 },
  { id: "est9", type: "estimation", theme: "Sciences", question: "Combien de pattes a un mille-pattes commun (en moyenne) ?", answer: 300, points: 100 },
  { id: "est10", type: "estimation", theme: "Géographie", question: "Combien de pays compte l'ONU ?", answer: 193, points: 100 },
  { id: "est11", type: "estimation", theme: "Culture G", question: "Quelle est la vitesse maximale enregistrée par Usain Bolt (en km/h) ?", answer: 44, points: 100 },
  { id: "est12", type: "estimation", theme: "Culture G", question: "Combien de touches y a-t-il sur un piano classique ?", answer: 88, points: 100 },
  { id: "est13", type: "estimation", theme: "Sciences", question: "Combien de temps (en jours) dure la gestation d'une éléphante ?", answer: 640, points: 100 },
  { id: "est14", type: "estimation", theme: "Culture G", question: "Combien de mètres mesure la plus grande statue du monde (Statue de l'Unité) ?", answer: 182, points: 100 },
  { id: "est15", type: "estimation", theme: "Géographie", question: "Combien de kilomètres fait le fleuve Amazone (environ) ?", answer: 6400, points: 100 },
  { id: "est16", type: "estimation", theme: "Sciences", question: "Combien de dents possède un humain adulte (sans dents de sagesse) ?", answer: 28, points: 100 },
  { id: "est17", type: "estimation", theme: "Géographie", question: "Quelle est la population mondiale en milliards (2024) ?", answer: 8, points: 100 },
  { id: "est18", type: "estimation", theme: "Culture G", question: "Combien de marches compte la Tour Eiffel jusqu'au sommet ?", answer: 1665, points: 150 },
  { id: "est19", type: "estimation", theme: "Géographie", question: "Combien de pays y a-t-il officiellement en Afrique ?", answer: 54, points: 120 },
  { id: "est20", type: "estimation", theme: "Géographie", question: "Quelle est la longueur de la Grande Muraille de Chine en km ?", answer: 21196, points: 200 },
  { id: "est21", type: "estimation", theme: "Sciences", question: "Combien de jours dure une année sur Mars ?", answer: 687, points: 150 },
  { id: "est22", type: "estimation", theme: "Géographie", question: "Combien d'États compte les États-Unis d'Amérique ?", answer: 50, points: 80 },
  { id: "est23", type: "estimation", theme: "Sciences", question: "Quelle est la température en surface du Soleil (en degrés Celsius) ?", answer: 5500, points: 200 },
  { id: "est24", type: "estimation", theme: "Sciences", question: "Combien de litres de sang contient le corps d'un adulte (environ) ?", answer: 5, points: 100 },
  { id: "est25", type: "estimation", theme: "Géographie", question: "Combien d'États membres compte l'Union Européenne (en 2024) ?", answer: 27, points: 100 },
  { id: "est26", type: "estimation", theme: "Culture G", question: "Combien de secondes y a-t-il dans une journée ?", answer: 86400, points: 150 },
  { id: "est27", type: "estimation", theme: "Géographie", question: "Quelle est la profondeur moyenne de l'océan (en mètres) ?", answer: 3700, points: 150 },
  { id: "est28", type: "estimation", theme: "Géographie", question: "Combien de pays ont le français comme langue officielle ?", answer: 29, points: 120 },
  { id: "est29", type: "estimation", theme: "Culture G", question: "Combien d'anneaux compose le logo des Jeux Olympiques ?", answer: 5, points: 50 },
  { id: "est30", type: "estimation", theme: "Culture G", question: "Combien de pièces y a-t-il au début d'une partie d'échecs (total) ?", answer: 32, points: 100 },
  { id: "est31", type: "estimation", theme: "Culture G", question: "Quelle est la longueur de la piscine olympique (en mètres) ?", answer: 50, points: 80 },
  { id: "est32", type: "estimation", theme: "Géographie", question: "En kilomètres, quelle est la circonférence de la Terre ?", answer: 40075, points: 200 },
  { id: "est33", type: "estimation", theme: "Sciences", question: "Combien d'atomes d'oxygène y a-t-il dans une molécule d'eau ?", answer: 1, points: 50 },
  { id: "est34", type: "estimation", theme: "Sciences", question: "Combien d'éléments contient le tableau périodique actuel ?", answer: 118, points: 100 },
  { id: "est35", type: "estimation", theme: "Sciences", question: "Quelle est la distance entre la Terre et Mars (en millions de km, au plus proche) ?", answer: 55, points: 150 },
  { id: "est36", type: "estimation", theme: "Sciences", question: "Combien de muscles possède le corps humain (environ) ?", answer: 650, points: 100 },
  { id: "est37", type: "estimation", theme: "Sciences", question: "Combien de temps met la lumière du Soleil pour atteindre la Terre (en secondes) ?", answer: 499, points: 150 },
  { id: "est38", type: "estimation", theme: "Sciences", question: "Quel est le record du monde de durée de sommeil pour un humain (en heures) ?", answer: 264, points: 200 },
  { id: "est39", type: "estimation", theme: "Sciences", question: "Combien de battements de cœur un humain fait-il en moyenne par minute au repos ?", answer: 70, points: 50 },
  { id: "est40", type: "estimation", theme: "Sciences", question: "Quelle est la température du zéro absolu (en degrés Celsius) ?", answer: -273, points: 150 },
  { id: "est41", type: "estimation", theme: "Sciences", question: "Combien de vertèbres compose la colonne dorsale humaine ?", answer: 33, points: 120 },
  { id: "est-sp1", type: "estimation", theme: "Sport", question: "Combien de kilomètres fait un marathon (arrondi à l'entier) ?", answer: 42, points: 150 },
  { id: "est-sp2", type: "estimation", theme: "Sport", question: "Combien de joueurs composent une équipe de rugby à XV sur le terrain ?", answer: 15, points: 100 },
  { id: "est-da1", type: "estimation", theme: "Dessin animé", question: "Combien y a-t-il de Dalmatiens dans le célèbre dessin animé de Disney ?", answer: 101, points: 100 },
  { id: "est-da2", type: "estimation", theme: "Dessin animé", question: "Combien de boules de cristal magiques faut-il réunir dans Dragon Ball ?", answer: 7, points: 100 },
  { id: "est-sp3", type: "estimation", theme: "Sport", question: "Quelle est la hauteur officielle d'un panier de basket en NBA (en centimètres) ?", answer: 305, points: 150 },
  { id: "est-sp4", type: "estimation", theme: "Sport", question: "Combien de trous compte un parcours de golf de compétition complet ?", answer: 18, points: 100 },
  { id: "est-sp5", type: "estimation", theme: "Sport", question: "Combien de quilles doit-on faire tomber au bowling en un seul lancer pour faire un strike ?", answer: 10, points: 80 },
  { id: "est-sp6", type: "estimation", theme: "Sport", question: "En kilomètres, quelle est la distance d'un semi-marathon (arrondi à l'entier) ?", answer: 21, points: 150 },
  { id: "est-sp7", type: "estimation", theme: "Sport", question: "Combien de minutes dure un quart-temps en NBA ?", answer: 12, points: 120 },
  { id: "est-da3", type: "estimation", theme: "Dessin animé", question: "Combien d'émotions principales y a-t-il dans la tête de Riley dans le film 'Vice-Versa' (le 1er film) ?", answer: 5, points: 100 },
  { id: "est-da4", type: "estimation", theme: "Dessin animé", question: "Combien de doigts possède un Minion sur une seule main ?", answer: 3, points: 120 },
  { id: "est-da5", type: "estimation", theme: "Dessin animé", question: "Combien de fées marraines se penchent sur le berceau de La Belle au Bois Dormant ?", answer: 3, points: 100 },
  { id: "est-da6", type: "estimation", theme: "Dessin animé", question: "Combien de nains accompagnent Blanche-Neige ?", answer: 7, points: 80 },
  { id: "est-da7", type: "estimation", theme: "Dessin animé", question: "Combien de têtes possède le dragon 'Touffu' dans l'univers de Harry Potter ?", answer: 3, points: 100 }, // Clin d'oeil pop culture

];