import type { QuizQuestion } from "../quiz-bank";

export const openQuestions: QuizQuestion[] = [
  // --- GÉOGRAPHIE ---
  { id: "geo-op1", type: "open", theme: "Géographie", question: "Quelle est la capitale de l'Australie ?", answer: "Canberra", points: 130 },
  { id: "geo-op2", type: "open", theme: "Géographie", question: "Quel est le plus grand pays du monde en superficie ?", answer: "Russie", points: 60 },
  { id: "geo-op3", type: "open", theme: "Géographie", question: "Dans quel pays se trouve le mont Kilimandjaro ?", answer: "Tanzanie", points: 140 },
  { id: "geo-op4", type: "open", theme: "Géographie", question: "Quel est le plus grand désert chaud du monde ?", answer: "Sahara", points: 80 },
  { id: "geo-op5", type: "open", theme: "Géographie", question: "Quelle est la capitale de la Suisse ?", answer: "Berne", points: 120 },
  { id: "geo-op6", type: "open", theme: "Géographie", question: "Quel est le plus grand pays d’Afrique en superficie ?", answer: "Algérie", points: 150 },
  { id: "geo-op7", type: "open", theme: "Géographie", question: "Quelle est la capitale du Brésil ?", answer: "Brasilia", points: 120 },
  { id: "geo-op8", type: "open", theme: "Géographie", question: "Quelle est la capitale de l’Indonésie ?", answer: "Jakarta", points: 130 },
  { id: "geo-op9", type: "open", theme: "Géographie", question: "Quel est le plus grand archipel du monde ?", answer: "Indonésie", points: 140 },
  { id: "geo-op10", type: "open", theme: "Géographie", question: "Quel fleuve traverse le plus grand nombre de pays (10 pays) ?", answer: "Danube", points: 180 },
  { id: "geo-op11", type: "open", theme: "Géographie", question: "Quel pays possède le plus d'îles au monde ?", answer: "Suède", points: 190 },
  { id: "geo-op12", type: "open", theme: "Géographie", question: "Quelle est la capitale de la Mongolie ?", answer: "Oulan-Bator", points: 160 },
  { id: "geo-op13", type: "open", theme: "Géographie", question: "Dans quel pays se trouve le désert de l'Atacama ?", answer: "Chili", points: 150 },
  { id: "geo-op14", type: "open", theme: "Géographie", question: "Quelle est la plus haute chute d'eau du monde ?", answer: "Salto Ángel", points: 170 },

  // --- SCIENCES ---
  { id: "sci-op1", type: "open", theme: "Sciences", question: "Quel est le symbole chimique de l'or ?", answer: "Au", points: 90 },
  { id: "sci-op2", type: "open", theme: "Sciences", question: "Quel est l'organe le plus lourd du corps humain ?", answer: "Peau", points: 140 },
  { id: "sci-op3", type: "open", theme: "Sciences", question: "Quel gaz les plantes absorbent-elles pour la photosynthèse ?", answer: "Dioxyde de carbone", points: 100 },
  { id: "sci-op4", type: "open", theme: "Sciences", question: "Qui a découvert la pénicilline ?", answer: "Fleming", points: 160 },
  { id: "sci-op5", type: "open", theme: "Sciences", question: "Quelle est la plus grande glande du corps humain ?", answer: "Foie", points: 130 },
  { id: "sci-op6", type: "open", theme: "Sciences", question: "Quel acide trouve-t-on en abondance dans l'estomac ?", answer: "Chlorhydrique", points: 150 },
  { id: "sci-op7", type: "open", theme: "Sciences", question: "Quelle planète est la plus grande du système solaire ?", answer: "Jupiter", points: 80 },
  { id: "sci-op8", type: "open", theme: "Sciences", question: "Quel métal est liquide à température ambiante ?", answer: "Mercure", points: 130 },
  { id: "sci-op9", type: "open", theme: "Sciences", question: "Quelle est la vitesse de la lumière en km/s (environ) ?", answer: "300000", points: 110 },
  { id: "sci-op10", type: "open", theme: "Sciences", question: "Combien de cœurs possède une pieuvre ?", answer: "3", points: 140 },
  { id: "sci-op11", type: "open", theme: "Sciences", question: "Quel est l'élément chimique le plus abondant dans l'univers ?", answer: "Hydrogène", points: 140 },
  { id: "sci-op12", type: "open", theme: "Sciences", question: "Comment appelle-t-on le passage de l'état solide à l'état gazeux sans passer par l'état liquide ?", answer: "Sublimation", points: 160 },

  // --- CULTURE G ---
  { id: "cg-op1", type: "open", theme: "Culture G", question: "Qui a écrit Les Misérables ?", answer: "Victor Hugo", points: 70 },
  { id: "cg-op2", type: "open", theme: "Culture G", question: "Quel peintre est l'auteur de 'Guernica' ?", answer: "Picasso", points: 100 },
  { id: "cg-op3", type: "open", theme: "Culture G", question: "Quelle langue parle-t-on principalement au Brésil ?", answer: "Portugais", points: 80 },
  { id: "cg-op4", type: "open", theme: "Culture G", question: "Quel écrivain a créé le personnage de Sherlock Holmes ?", answer: "Arthur Conan Doyle", points: 110 },
  { id: "cg-op5", type: "open", theme: "Culture G", question: "Qui a composé 'Les Quatre Saisons' ?", answer: "Vivaldi", points: 100 },
  { id: "cg-op6", type: "open", theme: "Culture G", question: "Quel philosophe grec était le maître d'Alexandre le Grand ?", answer: "Aristote", points: 160 },
  { id: "cg-op7", type: "open", theme: "Culture G", question: "En quelle année a eu lieu la chute du mur de Berlin ?", answer: "1989", points: 80 },
  { id: "cg-op8", type: "open", theme: "Culture G", question: "Quel pays a offert la Statue de la Liberté aux États-Unis ?", answer: "France", points: 80 },
  { id: "cg-op9", type: "open", theme: "Culture G", question: "Qui a peint 'La Jeune Fille à la perle' ?", answer: "Vermeer", points: 150 },
  { id: "cg-op10", type: "open", theme: "Culture G", question: "Quel est le nom de la célèbre école de magie dans Harry Potter ?", answer: "Poudlard", points: 60 },

  // --- SPORT ---
  { id: "sp-op1", type: "open", theme: "Sport", question: "Quelle nation les 'All Blacks' représentent-ils au rugby ?", answer: "Nouvelle-Zélande", points: 80 },
  { id: "sp-op2", type: "open", theme: "Sport", question: "Quel pays organise le tournoi de tennis de Wimbledon ?", answer: "Royaume-Uni", points: 90 },
  { id: "sp-op3", type: "open", theme: "Sport", question: "Quel est le surnom du cycliste français Bernard Hinault ?", answer: "Le Blaireau", points: 180 },
  { id: "sp-op4", type: "open", theme: "Sport", question: "Quelle est la distance exacte d'un marathon en kilomètres ?", answer: "42,195", points: 120 },
  { id: "sp-op5", type: "open", theme: "Sport", question: "Quel pays détient le record du nombre de victoires en Coupe du Monde de football ?", answer: "Brésil", points: 90 },
  { id: "sp-op6", type: "open", theme: "Sport", question: "Quel boxeur était surnommé 'The Greatest' ?", answer: "Mohamed Ali", points: 100 },
  { id: "sp-op7", type: "open", theme: "Sport", question: "Dans quel sport s'illustre la compétition de la 'Ryder Cup' ?", answer: "Golf", points: 160 },
  { id: "sp-op8", type: "open", theme: "Sport", question: "Quel joueur de tennis détient le record de victoires à Roland-Garros ?", answer: "Nadal", points: 70 },

  // --- DESSIN ANIMÉ ---
  { id: "da-op1", type: "open", theme: "Dessin animé", question: "Quel studio a produit les films 'Mon Voisin Totoro' et 'Le Voyage de Chihiro' ?", answer: "Ghibli", points: 130 },
  { id: "da-op2", type: "open", theme: "Dessin animé", question: "Comment s'appelle le dragon violet qui accompagne Mulan ?", answer: "Mushu", points: 110 },
  { id: "da-op3", type: "open", theme: "Dessin animé", question: "Dans 'One Piece', comment s'appelle le sabreur qui utilise trois sabres ?", answer: "Zoro", points: 120 },
  { id: "da-op4", type: "open", theme: "Dessin animé", question: "Quel est le nom du chat bleu robot venu du futur ?", answer: "Doraemon", points: 150 },
  { id: "da-op5", type: "open", theme: "Dessin animé", question: "Comment s'appelle le rat cuisinier dans le film de Pixar ?", answer: "Rémy", points: 80 },
  { id: "da-op6", type: "open", theme: "Dessin animé", question: "Quel est le nom du royaume dans 'La Reine des Neiges' ?", answer: "Arendelle", points: 140 },
  { id: "da-op7", type: "open", theme: "Dessin animé", question: "Comment s'appelle l'avatar dans 'Le dernier maître de l'air' ?", answer: "Aang", points: 110 },

  // --- MYTHOLOGIE ---
  { id: "my-op1", type: "open", theme: "Mythologie", question: "Quel héros de la mythologie grecque a vaincu le Minotaure ?", answer: "Thésée", points: 130 },
  { id: "my-op2", type: "open", theme: "Mythologie", question: "Qui est le père de Zeus ?", answer: "Cronos", points: 150 },
  { id: "my-op3", type: "open", theme: "Mythologie", question: "Quel dieu transporte les âmes des défunts sur le Styx ?", answer: "Charon", points: 160 },
  { id: "my-op4", type: "open", theme: "Mythologie", question: "Comment s'appelle l'arbre monde dans la mythologie nordique ?", answer: "Yggdrasil", points: 180 },
  { id: "my-op5", type: "open", theme: "Mythologie", question: "Quel héros a volé le feu aux dieux pour le donner aux hommes ?", answer: "Prométhée", points: 140 },
  { id: "my-op6", type: "open", theme: "Mythologie", question: "Quel dieu égyptien possède une tête de chacal ?", answer: "Anubis", points: 100 },
  { id: "my-op7", type: "open", theme: "Mythologie", question: "Quel héros grec est célèbre pour son talon vulnérable ?", answer: "Achille", points: 80 },
  { id: "my-op8", type: "open", theme: "Mythologie", question: "Comment s'appelle le chien à trois têtes qui garde les Enfers ?", answer: "Cerbère", points: 100 },
  { id: "my-op9", type: "open", theme: "Mythologie", question: "Qui est la déesse de la discorde chez les Grecs ?", answer: "Éris", points: 170 },
  { id: "my-op10", type: "open", theme: "Mythologie", question: "Comment s'appelle l'épouse d'Odin ?", answer: "Frigg", points: 180 },

  // --- MUSIQUE ---
  { id: "mu-op1", type: "open", theme: "Musique", question: "Quel chanteur américain est mondialement surnommé le 'King of Pop' ?", answer: "Michael Jackson", points: 60 },
  { id: "mu-op2", type: "open", theme: "Musique", question: "Dans quel groupe de rock britannique Freddie Mercury était-il le chanteur principal ?", answer: "Queen", points: 70 },
  { id: "mu-op3", type: "open", theme: "Musique", question: "De quel pays est originaire le genre musical appelé 'Reggae' ?", answer: "Jamaïque", points: 80 },
  { id: "mu-op4", type: "open", theme: "Musique", question: "Quel instrument à cordes est l'emblème national de l'Irlande ?", answer: "Harpe", points: 110 },
  { id: "mu-op5", type: "open", theme: "Musique", question: "Comment appelle-t-on le chanteur principal d'un groupe de rock ?", answer: "Frontman", points: 90 },
  { id: "mu-op6", type: "open", theme: "Musique", question: "Quel était le prénom du célèbre compositeur autrichien Mozart ?", answer: "Wolfgang", points: 80 },
  { id: "mu-op7", type: "open", theme: "Musique", question: "Quel instrument à vent est typiquement associé au jazz et a été inventé par un Belge ?", answer: "Saxophone", points: 90 },
  { id: "mu-op8", type: "open", theme: "Musique", question: "Quel groupe de Liverpool a déclenché la 'Beatlemania' dans les années 60 ?", answer: "The Beatles", points: 60 },
  { id: "mu-op9", type: "open", theme: "Musique", question: "Quel est le vrai nom de la chanteuse américaine Lady Gaga ?", answer: "Stefani Germanotta", points: 140 },
  { id: "mu-op10", type: "open", theme: "Musique", question: "Comment appelle-t-on la distance de huit notes entre deux notes de même nom ?", answer: "Octave", points: 120 },
  { id: "mu-op11", type: "open", theme: "Musique", question: "Quel grand compositeur classique a continué à écrire de la musique bien qu'il soit devenu sourd ?", answer: "Beethoven", points: 90 },
  { id: "mu-op12", type: "open", theme: "Musique", question: "Dans quel pays est né le mouvement musical 'K-pop' ?", answer: "Corée du Sud", points: 80 },
  { id: "mu-op13", type: "open", theme: "Musique", question: "Comment appelle-t-on le bâton utilisé par un chef d'orchestre ?", answer: "Baguette", points: 120 },
  { id: "mu-op14", type: "open", theme: "Musique", question: "Quel musicien de jazz jouait de la trompette et était surnommé 'Satchmo' ?", answer: "Louis Armstrong", points: 150 },
  { id: "mu-op15", type: "open", theme: "Musique", question: "Quel est le terme musical italien pour dire qu'il faut jouer 'fort' ?", answer: "Forte", points: 110 },
  { id: "mu-op16", type: "open", theme: "Musique", question: "Quel guitariste de génie a brûlé sa guitare sur scène au festival de Monterey en 1967 ?", answer: "Jimi Hendrix", points: 140 },
  { id: "mu-op17", type: "open", theme: "Musique", question: "Comment s'appelle l'accessoire qu'un guitariste utilise pour gratter les cordes ?", answer: "Médiator", points: 100 },
  { id: "mu-op18", type: "open", theme: "Musique", question: "Quel chanteur de folk américain a reçu le prix Nobel de littérature en 2016 ?", answer: "Bob Dylan", points: 160 },
  { id: "mu-op19", type: "open", theme: "Musique", question: "Quel groupe d'électro français portait des casques de robots en public ?", answer: "Daft Punk", points: 90 },
  { id: "mu-op20", type: "open", theme: "Musique", question: "Quel instrument à cordes frottées est légèrement plus grand et plus grave qu'un violon ?", answer: "Alto", points: 150 },
  { id: "mu-op21", type: "open", theme: "Musique", question: "Quel est le nom de l'intervalle de trois tons, autrefois appelé 'le Diable dans la musique' ?", answer: "Triton", points: 180 },
  { id: "mu-op22", type: "open", theme: "Musique", question: "Quelle chanteuse de jazz était surnommée 'The First Lady of Song' ?", answer: "Ella Fitzgerald", points: 170 },
  { id: "mu-op23", type: "open", theme: "Musique", question: "Quel terme italien désigne un chant effectué sans accompagnement instrumental ?", answer: "A cappella", points: 130 },
  { id: "mu-op24", type: "open", theme: "Musique", question: "Quel compositeur polonais était surnommé 'le poète du piano' ?", answer: "Frédéric Chopin", points: 160 },
  { id: "mu-op25", type: "open", theme: "Musique", question: "Comment s'appelle la partie en bois sur laquelle on appuie les cordes d'un violon ou d'une guitare ?", answer: "Touche", points: 160 },
  { id: "mu-op26", type: "open", theme: "Musique", question: "Quel rappeur de Détroit a pour alter ego 'Slim Shady' ?", answer: "Eminem", points: 110 },
  { id: "mu-op27", type: "open", theme: "Musique", question: "Quelle ville américaine est considérée comme le berceau du Jazz ?", answer: "La Nouvelle-Orléans", points: 150 },
  { id: "mu-op28", type: "open", theme: "Musique", question: "Quel instrument de percussion est constitué de lames de bois que l'on frappe avec des mailloches ?", answer: "Xylophone", points: 130 },
  { id: "mu-op29", type: "open", theme: "Musique", question: "Quel musicien a fondé le label Motown en 1959 ?", answer: "Berry Gordy", points: 210 },
  { id: "mu-op30", type: "open", theme: "Musique", question: "Quel compositeur baroque est l'auteur du célèbre 'Messie' ?", answer: "Haendel", points: 170 },
  { id: "mu-op31", type: "open", theme: "Musique", question: "Quel est le nom de la guitare fétiche de B.B. King ?", answer: "Lucille", points: 190 },
  { id: "mu-op32", type: "open", theme: "Musique", question: "Quel pianiste de jazz est célèbre pour sa composition 'Take Five' ?", answer: "Dave Brubeck", points: 210 },
  { id: "mu-op33", type: "open", theme: "Musique", question: "Dans un orchestre, quel instrument donne traditionnellement le 'La' pour l'accordage ?", answer: "Hautbois", points: 190 },
  { id: "mu-op34", type: "open", theme: "Musique", question: "Quel chanteur de soul est l'auteur du tube 'Sitting on the Dock of the Bay' ?", answer: "Otis Redding", points: 160 },
  { id: "mu-op35", type: "open", theme: "Musique", question: "Quel groupe de hard rock australien a sorti l'album 'Back in Black' ?", answer: "AC/DC", points: 100 },
  { id: "mu-op36", type: "open", theme: "Musique", question: "Comment appelle-t-on la voix d'homme la plus aiguë ?", answer: "Contre-ténor", points: 180 },
  { id: "mu-op37", type: "open", theme: "Musique", question: "Quel compositeur français a écrit le célèbre 'Boléro' ?", answer: "Maurice Ravel", points: 130 },
  { id: "mu-op38", type: "open", theme: "Musique", question: "Qui est le créateur du festival 'Lollapalooza' ?", answer: "Perry Farrell", points: 220 },
  { id: "mu-op39", type: "open", theme: "Musique", question: "Quel instrument est souvent surnommé 'le roi des instruments' à cause de sa taille et de sa puissance ?", answer: "Orgue", points: 120 },
  { id: "mu-op40", type: "open", theme: "Musique", question: "Quel terme désigne l'accélération progressive du rythme dans un morceau ?", answer: "Accelerando", points: 160 }
];