import type { QuizQuestion } from "../quiz-bank";

export const openQuestions: QuizQuestion[] = [
  { id: "op1", type: "open", theme: "Géographie", question: "Quelle est la capitale du Japon ?", answer: "Tokyo", points: 100 },
  { id: "op2", type: "open", theme: "Sciences", question: "Quel est le symbole chimique de l'or ?", answer: "Au", points: 100 },
  { id: "op3", type: "open", theme: "Sciences", question: "Quelle planète est la plus proche du soleil ?", answer: "Mercure", points: 100 },
  { id: "op4", type: "open", theme: "Culture G", question: "Qui a écrit Les Misérables ?", answer: "Victor Hugo", points: 100 },
  { id: "op5", type: "open", theme: "Sciences", question: "Quel animal miaule ?", answer: "Chat", points: 100 },
  { id: "op6", type: "open", theme: "Culture G", question: "De quelle couleur est le cheval blanc d'Henri IV ?", answer: "Blanc", points: 50 },
  { id: "op7", type: "open", theme: "Géographie", question: "Quel est le plus grand pays du monde en superficie ?", answer: "Russie", points: 100 },
  { id: "op8", type: "open", theme: "Géographie", question: "Quelle est la monnaie utilisée au Royaume-Uni ?", answer: "Livre", points: 100 },
  { id: "op9", type: "open", theme: "Culture G", question: "Quel fruit est le logo de l'entreprise de Steve Jobs ?", answer: "Pomme", points: 50 },
  { id: "op10", type: "open", theme: "Culture G", question: "Comment s'appelle l'éponge jaune qui vit dans un ananas sous la mer ?", answer: "Bob l'Éponge", points: 100 },
  { id: "op11", type: "open", theme: "Sciences", question: "Quel est l'organe le plus lourd du corps humain ?", answer: "Peau", points: 120 },
  { id: "op12", type: "open", theme: "Géographie", question: "Quel pays est surnommé le pays du Soleil Levant ?", answer: "Japon", points: 80 },
  { id: "op13", type: "open", theme: "Sciences", question: "Quel est le métal dont le symbole chimique est Fe ?", answer: "Fer", points: 100 },
  { id: "op14", type: "open", theme: "Géographie", question: "Quelle est la capitale de l'Espagne ?", answer: "Madrid", points: 80 },
  { id: "op15", type: "open", theme: "Culture G", question: "Quel artiste est célèbre pour avoir peint la Joconde ?", answer: "Léonard de Vinci", points: 100 },
  { id: "op16", type: "open", theme: "Sciences", question: "Comment appelle-t-on le bébé du cheval ?", answer: "Poulain", points: 80 },
  { id: "op17", type: "open", theme: "Géographie", question: "Dans quel pays peut-on visiter les pyramides de Gizeh ?", answer: "Égypte", points: 80 },
  { id: "op18", type: "open", theme: "Géographie", question: "Quel est le plus long fleuve du monde ?", answer: "Nil", points: 100 },
  { id: "op19", type: "open", theme: "Géographie", question: "Quelle est la capitale du Portugal ?", answer: "Lisbonne", points: 100 },
  { id: "op20", type: "open", theme: "Sciences", question: "Quel est le nom du scientifique qui a formulé la théorie de la relativité ?", answer: "Einstein", points: 100 },
  { id: "op21", type: "open", theme: "Culture G", question: "De quel pays vient la pizza ?", answer: "Italie", points: 50 },
  { id: "op22", type: "open", theme: "Géographie", question: "Quel est le plus grand continent du monde ?", answer: "Asie", points: 80 },
  { id: "op23", type: "open", theme: "Sciences", question: "Comment s'appelle la peur des araignées ?", answer: "Arachnophobie", points: 120 },
  { id: "op24", type: "open", theme: "Sciences", question: "Quelle planète est surnommée la planète rouge ?", answer: "Mars", points: 80 },
  { id: "op25", type: "open", theme: "Culture G", question: "Quel est le prénom du célèbre sorcier Potter ?", answer: "Harry", points: 50 },
  { id: "op26", type: "open", theme: "Culture G", question: "Dans quel sport utilise-t-on un volant ?", answer: "Badminton", points: 100 },
  { id: "op27", type: "open", theme: "Sciences", question: "Quel est l'animal le plus haut du monde ?", answer: "Girafe", points: 80 },
  { id: "op28", type: "open", theme: "Géographie", question: "Quel océan borde la côte ouest des États-Unis ?", answer: "Pacifique", points: 100 },
  { id: "op29", type: "open", theme: "Sciences", question: "Quel gaz les plantes absorbent-elles pour la photosynthèse ?", answer: "Dioxyde de carbone", points: 100 },
  { id: "op30", type: "open", theme: "Sciences", question: "Comment appelle-t-on la partie colorée de l'œil ?", answer: "Iris", points: 80 },
  { id: "op31", type: "open", theme: "Sciences", question: "Qui a découvert la pénicilline ?", answer: "Fleming", points: 150 },
  { id: "op32", type: "open", theme: "Sciences", question: "Quelle est la plus grande glande du corps humain ?", answer: "Foie", points: 120 },
  { id: "op33", type: "open", theme: "Sciences", question: "Quel instrument utilise un médecin pour écouter le cœur ?", answer: "Stéthoscope", points: 100 },
  { id: "op34", type: "open", theme: "Géographie", question: "Dans quel pays se trouve le mont Kilimandjaro ?", answer: "Tanzanie", points: 120 },
  { id: "op35", type: "open", theme: "Sciences", question: "Quel est le nom du pigment qui donne la couleur à la peau ?", answer: "Mélanine", points: 100 },
  { id: "op36", type: "open", theme: "Sciences", question: "Quel acide trouve-t-on en abondance dans l'estomac ?", answer: "Chlorhydrique", points: 130 },
  { id: "op-sp1", type: "open", theme: "Sport", question: "Quel sport se joue avec un club, une petite balle blanche et des trous ?", answer: "Golf", points: 80 },
  { id: "op-sp2", type: "open", theme: "Sport", question: "Quelle nation les 'All Blacks' représentent-ils au rugby ?", answer: "Nouvelle-Zélande", points: 120 },
  { id: "op-da1", type: "open", theme: "Dessin animé", question: "Comment s'appelle l'ogre vert des studios DreamWorks ?", answer: "Shrek", points: 80 },
  { id: "op-da2", type: "open", theme: "Dessin animé", question: "Quel est le nom du célèbre petit chien blanc de Tintin ?", answer: "Milou", points: 80 },
  { id: "op-sp3", type: "open", theme: "Sport", question: "Comment s'appelle le célèbre footballeur argentin vainqueur de la Coupe du Monde 2022 ?", answer: "Messi", answerAliases: ["Lionel Messi", "Leo Messi"], points: 80 },
  { id: "op-sp4", type: "open", theme: "Sport", question: "Dans quelle ville se déroule le grand tournoi de tennis sur terre battue de Roland-Garros ?", answer: "Paris", points: 80 },
  { id: "op-sp5", type: "open", theme: "Sport", question: "Quel art martial japonais se pratique en saisissant le kimono (judogi) de l'adversaire ?", answer: "Judo", points: 100 },
  { id: "op-sp6", type: "open", theme: "Sport", question: "Quel accessoire tenu à la main utilise-t-on pour frapper le volant au badminton ?", answer: "Raquette", answerAliases: ["Une raquette"], points: 80 },
  { id: "op-sp7", type: "open", theme: "Sport", question: "Quel est le sport pratiqué par la légende américaine Michael Jordan ?", answer: "Basket", answerAliases: ["Basketball", "Basket-ball", "Le basket"], points: 80 },
  { id: "op-da3", type: "open", theme: "Dessin animé", question: "Comment s'appelle le chien de Mickey Mouse ?", answer: "Pluto", points: 80 },
  { id: "op-da4", type: "open", theme: "Dessin animé", question: "Quel aliment mange Popeye pour devenir super fort ?", answer: "Epinards", answerAliases: ["Des épinards", "Épinards"], points: 80 },
  { id: "op-da5", type: "open", theme: "Dessin animé", question: "Comment s'appelle la célèbre souris mâle qui accompagne souvent Jerry ?", answer: "Tom", answerAliases: ["Tom le chat"], points: 80 },
  { id: "op-da6", type: "open", theme: "Dessin animé", question: "Comment s'appelle le meilleur ami (une étoile de mer) de Bob l'éponge ?", answer: "Patrick", answerAliases: ["Patrick l'étoile de mer"], points: 80 },
  { id: "op-da7", type: "open", theme: "Dessin animé", question: "Quel est le prénom de l'héroïne Disney qui a de très longs cheveux magiques ?", answer: "Raiponce", points: 80 },

];

