import type { QuizQuestion } from "../quiz-bank";

export const qcmQuestions: QuizQuestion[] = [
  // --- GÉOGRAPHIE ---
  { id: "qcm1", type: "qcm", theme: "Géographie", question: "Quelle est la capitale de l'Australie ?", answer: "Canberra", options: ["Sydney", "Melbourne", "Canberra", "Perth"], points: 130 },
  { id: "qcm5", type: "qcm", theme: "Géographie", question: "Combien y a-t-il de fuseaux horaires en Russie ?", answer: "11", options: ["7", "9", "11", "13"], points: 140 },
  { id: "qcm6", type: "qcm", theme: "Géographie", question: "Quel est le plus grand océan de la Terre ?", answer: "Océan Pacifique", options: ["Océan Atlantique", "Océan Indien", "Océan Pacifique", "Océan Arctique"], points: 80 },
  { id: "qcm8", type: "qcm", theme: "Géographie", question: "Dans quel pays se trouve la ville de Tombouctou ?", answer: "Mali", options: ["Sénégal", "Niger", "Mali", "Maroc"], points: 120 },
  { id: "qcm12", type: "qcm", theme: "Géographie", question: "Quelle est la monnaie du Japon ?", answer: "Le Yen", options: ["Le Yuan", "Le Won", "Le Yen", "Le Ringgit"], points: 70 },
  { id: "qcm18", type: "qcm", theme: "Géographie", question: "Quelle est la capitale de l'Islande ?", answer: "Reykjavik", options: ["Oslo", "Reykjavik", "Stockholm", "Helsinki"], points: 120 },
  { id: "qcm21", type: "qcm", theme: "Géographie", question: "Quel est le plus grand pays du monde par la taille ?", answer: "Russie", options: ["Canada", "Chine", "États-Unis", "Russie"], points: 60 },
  { id: "qcm22", type: "qcm", theme: "Géographie", question: "Dans quelle ville se trouve le Colisée ?", answer: "Rome", options: ["Athènes", "Rome", "Naples", "Florence"], points: 60 },
  { id: "qcm25", type: "qcm", theme: "Géographie", question: "Dans quelle ville se trouve le siège de l'ONU ?", answer: "New York", options: ["Genève", "Washington", "New York", "Bruxelles"], points: 90 },
  { id: "qcm29", type: "qcm", theme: "Géographie", question: "Quel est le plus petit pays du monde ?", answer: "Vatican", options: ["Monaco", "Saint-Marin", "Vatican", "Andorre"], points: 80 },
  { id: "qcm30", type: "qcm", theme: "Géographie", question: "Quelle est la capitale du Canada ?", answer: "Ottawa", options: ["Toronto", "Montréal", "Ottawa", "Québec"], points: 120 },
  { id: "qcm35", type: "qcm", theme: "Géographie", question: "Quelle est la capitale la plus haute du monde (altitude) ?", answer: "La Paz", options: ["Quito", "La Paz", "Bogota", "Lhassa"], points: 160 },
  { id: "qcm37", type: "qcm", theme: "Géographie", question: "Lequel de ces pays ne possède pas d'accès à la mer ?", answer: "Suisse", options: ["Belgique", "Suisse", "Norvège", "Portugal"], points: 90 },
  { id: "qcm39", type: "qcm", theme: "Géographie", question: "Quel fleuve traverse le plus grand nombre de pays ?", answer: "Le Danube", options: ["Le Nil", "L'Amazone", "Le Danube", "Le Rhin"], points: 170 },
  { id: "qcm41", type: "qcm", theme: "Géographie", question: "Quel pays possède le plus d'îles au monde ?", answer: "La Suède", options: ["L'Indonésie", "La Grèce", "Le Canada", "La Suède"], points: 180 },

  // --- SCIENCES ---
  { id: "qcm2", type: "qcm", theme: "Sciences", question: "Quel est l'animal le plus rapide du monde en piqué ?", answer: "Le faucon pèlerin", options: ["Le guépard", "L'aigle royal", "Le faucon pèlerin", "L'espadon"], points: 120 },
  { id: "qcm3", type: "qcm", theme: "Sciences", question: "Quel est le métal le plus abondant dans la croûte terrestre ?", answer: "L'aluminium", options: ["Le fer", "L'or", "Le cuivre", "L'aluminium"], points: 140 },
  { id: "qcm7", type: "qcm", theme: "Sciences", question: "Quelle planète est surnommée l'étoile du berger ?", answer: "Vénus", options: ["Mars", "Vénus", "Jupiter", "Mercure"], points: 90 },
  { id: "qcm11", type: "qcm", theme: "Sciences", question: "Quel est le plus grand os du corps humain ?", answer: "Le fémur", options: ["Le tibia", "Le fémur", "L'humérus", "Le péroné"], points: 80 },
  { id: "qcm15", type: "qcm", theme: "Sciences", question: "En informatique, que signifie 'RAM' ?", answer: "Random Access Memory", options: ["Read Access Memory", "Random Access Memory", "Run All Memory", "Real Allocation Mode"], points: 90 },
  { id: "qcm16", type: "qcm", theme: "Sciences", question: "Quel gaz compose majoritairement l' air que nous respirons ?", answer: "Azote", options: ["Oxygène", "Azote", "Gaz carbonique", "Hydrogène"], points: 110 },
  { id: "qcm20", type: "qcm", theme: "Sciences", question: "Quelle est la vitesse de la lumière (environ) ?", answer: "300 000 km/s", options: ["150 000 km/s", "300 000 km/s", "1 000 000 km/s", "300 000 km/h"], points: 100 },
  { id: "qcm23", type: "qcm", theme: "Sciences", question: "Quel est le nom de la galaxie dans laquelle nous vivons ?", answer: "La Voie Lactée", options: ["Andromède", "La Voie Lactée", "La Grande Ourse", "Orion"], points: 70 },
  { id: "qcm24", type: "qcm", theme: "Sciences", question: "Quel est l'oiseau qui pond les plus gros œufs ?", answer: "L'autruche", options: ["L'aigle", "L'autruche", "Le condor", "L'émeu"], points: 90 },
  { id: "qcm26", type: "qcm", theme: "Sciences", question: "Quel est l'élément chimique le plus léger ?", answer: "Hydrogène", options: ["Hélium", "Oxygène", "Azote", "Hydrogène"], points: 100 },
  { id: "qcm31", type: "qcm", theme: "Sciences", question: "Quel organe produit l'insuline ?", answer: "Le pancréas", options: ["Le foie", "Le pancréas", "La rate", "Les reins"], points: 130 },
  { id: "qcm33", type: "qcm", theme: "Sciences", question: "Quel est le plus grand mammifère terrestre ?", answer: "L'éléphant d'Afrique", options: ["Le rhinocéros", "L'éléphant d'Afrique", "La girafe", "L'hippopotame"], points: 70 },

  // --- HISTOIRE ---
  { id: "qcm34", type: "qcm", theme: "Histoire", question: "Quel empire était dirigé par Soliman le Magnifique ?", answer: "L'Empire Ottoman", options: ["L'Empire Perse", "L'Empire Ottoman", "L'Empire Moghol", "L'Empire Romain"], points: 130 },
  { id: "qcm36", type: "qcm", theme: "Histoire", question: "En quelle année a été découvert le tombeau de Toutânkhamon ?", answer: "1922", options: ["1898", "1912", "1922", "1936"], points: 140 },
  { id: "qcm38", type: "qcm", theme: "Histoire", question: "Qui était le président des USA durant la Guerre de Sécession ?", answer: "Abraham Lincoln", options: ["George Washington", "Andrew Jackson", "Abraham Lincoln", "Ulysses S. Grant"], points: 110 },
  { id: "qcm40", type: "qcm", theme: "Histoire", question: "Quelle était la capitale de l'Empire Inca ?", answer: "Cuzco", options: ["Machu Picchu", "Lima", "Quito", "Cuzco"], points: 130 },
  { id: "qcm-hist41", type: "qcm", theme: "Histoire", question: "Quel traité met officiellement fin à la Première Guerre mondiale ?", answer: "Traité de Versailles", options: ["Traité de Vienne", "Traité de Versailles", "Traité de Tordesillas", "Traité de Paris"], points: 100 },
  { id: "qcm-hist42", type: "qcm", theme: "Histoire", question: "En quelle année Constantinople est-elle tombée aux mains des Ottomans ?", answer: "1453", options: ["1492", "1453", "1517", "1396"], points: 170 },
  { id: "qcm-hist43", type: "qcm", theme: "Histoire", question: "Qui a dirigé l’URSS pendant la Seconde Guerre mondiale ?", answer: "Staline", options: ["Lénine", "Staline", "Trotski", "Khrouchtchev"], points: 100 },
  { id: "qcm-hist44", type: "qcm", theme: "Histoire", question: "Quel événement marque le début de la Révolution française ?", answer: "La prise de la Bastille", options: ["La fuite à Varennes", "La prise de la Bastille", "Le sacre de Napoléon", "La Terreur"], points: 70 },
  { id: "qcm-hist45", type: "qcm", theme: "Histoire", question: "Qui était le chef des forces alliées en Europe pendant la Seconde Guerre mondiale ?", answer: "Dwight D. Eisenhower", options: ["George Patton", "Dwight D. Eisenhower", "Douglas MacArthur", "Bernard Montgomery"], points: 180 },
  { id: "qcm-hist46", type: "qcm", theme: "Histoire", question: "Quel empire était dirigé par Gengis Khan ?", answer: "L’Empire Mongol", options: ["Empire Ottoman", "Empire Mongol", "Empire Perse", "Empire Romain"], points: 110 },
  { id: "qcm-hist47", type: "qcm", theme: "Histoire", question: "En quelle année a eu lieu la chute du mur de Berlin ?", answer: "1989", options: ["1987", "1989", "1991", "1993"], points: 80 },
  { id: "qcm-hist48", type: "qcm", theme: "Histoire", question: "Quel roi de France a été exécuté pendant la Révolution française ?", answer: "Louis XVI", options: ["Louis XIV", "Louis XV", "Louis XVI", "Louis XVIII"], points: 80 },
  { id: "qcm-hist49", type: "qcm", theme: "Histoire", question: "Quel est le nom de la bataille où Napoléon a subi sa défaite finale ?", answer: "Waterloo", options: ["Austerlitz", "Iéna", "Waterloo", "Trafalgar"], points: 90 },
  { id: "qcm-hist50", type: "qcm", theme: "Histoire", question: "Quel peuple antique a construit Machu Picchu ?", answer: "Les Incas", options: ["Les Mayas", "Les Aztèques", "Les Incas", "Les Olmèques"], points: 110 },
  { id: "qcm-hist51", type: "qcm", theme: "Histoire", question: "Qui était le premier empereur romain ?", answer: "Auguste", options: ["Jules César", "Néron", "Auguste", "Trajan"], points: 160 },
  { id: "qcm-hist52", type: "qcm", theme: "Histoire", question: "Quel événement a déclenché la Première Guerre mondiale ?", answer: "L’assassinat de l’archiduc François-Ferdinand", options: ["La crise de Cuba", "L’assassinat de l’archiduc François-Ferdinand", "La guerre franco-prussienne", "La chute de l’Empire ottoman"], points: 120 },
  { id: "qcm-hist53", type: "qcm", theme: "Histoire", question: "Quel pays a été dirigé par Mao Zedong ?", answer: "Chine", options: ["Japon", "Chine", "Corée", "Vietnam"], points: 90 },
  { id: "qcm-hist54", type: "qcm", theme: "Histoire", question: "Quel traité a partagé le Nouveau Monde entre l’Espagne et le Portugal ?", answer: "Traité de Tordesillas", options: ["Traité de Versailles", "Traité de Tordesillas", "Traité de Vienne", "Traité de Rome"], points: 180 },
  { id: "qcm-hist55", type: "qcm", theme: "Histoire", question: "Qui a mené les troupes françaises à Orléans pendant la guerre de Cent Ans ?", answer: "Jeanne d’Arc", options: ["Aliénor d’Aquitaine", "Jeanne d’Arc", "Catherine de Médicis", "Anne de Bretagne"], points: 80 },

  // --- CULTURE G ---
  { id: "qcm4", type: "qcm", theme: "Culture G", question: "Qui a peint La Jeune Fille à la perle ?", answer: "Johannes Vermeer", options: ["Vincent van Gogh", "Johannes Vermeer", "Rembrandt", "Claude Monet"], points: 140 },
  { id: "qcm9", type: "qcm", theme: "Culture G", question: "Quel est le nom du bateau dans Le Vieil Homme et la Mer ?", answer: "Il n'a pas de nom", options: ["L'Orca", "Le Pilar", "Le Pequod", "Il n'a pas de nom"], points: 190 },
  { id: "qcm10", type: "qcm", theme: "Culture G", question: "Quel ingrédient principal compose le guacamole ?", answer: "Avocat", options: ["Tomate", "Avocat", "Piment", "Citron vert"], points: 60 },
  { id: "qcm13", type: "qcm", theme: "Culture G", question: "Qui est le dieu grec des enfers ?", answer: "Hadès", options: ["Ares", "Apollon", "Poséidon", "Hadès"], points: 90 },
  { id: "qcm14", type: "qcm", theme: "Culture G", question: "Quelle série met en scène Walter White ?", answer: "Breaking Bad", options: ["Prison Break", "Dexter", "Breaking Bad", "The Wire"], points: 80 },
  { id: "qcm17", type: "qcm", theme: "Culture G", question: "Quel pays a remporté le plus de Coupes du Monde de football ?", answer: "Brésil", options: ["Allemagne", "Italie", "France", "Brésil"], points: 80 },
  { id: "qcm19", type: "qcm", theme: "Culture G", question: "Qui a écrit le roman '1984' ?", answer: "George Orwell", options: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "Ernest Hemingway"], points: 100 },
  { id: "qcm27", type: "qcm", theme: "Culture G", question: "Qui a écrit 'Les Fleurs du Mal' ?", answer: "Charles Baudelaire", options: ["Victor Hugo", "Charles Baudelaire", "Arthur Rimbaud", "Paul Verlaine"], points: 120 },
  { id: "qcm28", type: "qcm", theme: "Culture G", question: "Combien de cordes possède une guitare classique ?", answer: "6", options: ["4", "5", "6", "12"], points: 60 },
  { id: "qcm32", type: "qcm", theme: "Culture G", question: "Qui a réalisé le film 'Inception' ?", answer: "Christopher Nolan", options: ["Steven Spielberg", "Christopher Nolan", "Quentin Tarantino", "Martin Scorsese"], points: 110 },

  // --- SPORT ---
  { id: "qcm-sp1", type: "qcm", theme: "Sport", question: "Dans quel sport s'illustre Rafael Nadal ?", answer: "Tennis", options: ["Football", "Tennis", "Golf", "Basket-ball"], points: 60 },
  { id: "qcm-sp2", type: "qcm", theme: "Sport", question: "Quelle est la durée réglementaire d'un match de football (sans prolongations) ?", answer: "90 minutes", options: ["60 minutes", "80 minutes", "90 minutes", "120 minutes"], points: 60 },
  { id: "qcm-sp3", type: "qcm", theme: "Sport", question: "Quel pays a remporté la Coupe du Monde de football 2022 ?", answer: "Argentine", options: ["France", "Brésil", "Croatie", "Argentine"], points: 70 },
  { id: "qcm-sp4", type: "qcm", theme: "Sport", question: "Combien de joueurs composent une équipe de volley-ball sur le terrain ?", answer: "6", options: ["5", "6", "7", "11"], points: 90 },
  { id: "qcm-sp5", type: "qcm", theme: "Sport", question: "De quelle couleur est le maillot du leader du classement général sur le Tour de France ?", answer: "Jaune", options: ["Vert", "Jaune", "Blanc à pois rouges", "Rose"], points: 80 },
  { id: "qcm-sp6", type: "qcm", theme: "Sport", question: "Dans quel sport utilise-t-on le terme 'Home Run' ?", answer: "Baseball", options: ["Cricket", "Football Américain", "Baseball", "Hockey"], points: 90 },
  { id: "qcm-sp7", type: "qcm", theme: "Sport", question: "Quelle est la discipline de Teddy Riner ?", answer: "Judo", options: ["Karaté", "Boxe", "Lutte", "Judo"], points: 70 },
  { id: "qcm-sp11", type: "qcm", theme: "Sport", question: "Combien de sets maximum sont joués lors d’un match masculin en Grand Chelem (tennis) ?", answer: "5", options: ["3", "4", "5", "7"], points: 150 },
  { id: "qcm-sp12", type: "qcm", theme: "Sport", question: "En Formule 1, combien de points rapporte une victoire (format actuel) ?", answer: "25", options: ["20", "25", "30", "15"], points: 160 },
  { id: "qcm-sp13", type: "qcm", theme: "Sport", question: "Combien de joueurs une équipe de football américain aligne-t-elle sur le terrain ?", answer: "11", options: ["9", "10", "11", "12"], points: 160 },
  { id: "qcm-sp14", type: "qcm", theme: "Sport", question: "Au rugby à XV, combien de points vaut un drop ?", answer: "3", options: ["2", "3", "4", "5"], points: 130 },
  { id: "qcm-sp15", type: "qcm", theme: "Sport", question: "Dans quel sport trouve-t-on la règle du hors-jeu la plus complexe ?", answer: "Football", options: ["Rugby", "Football", "Hockey", "Handball"], points: 110 },
  { id: "qcm-sp16", type: "qcm", theme: "Sport", question: "Quel est le nombre de joueurs sur le terrain par équipe au handball ?", answer: "7", options: ["5", "6", "7", "8"], points: 120 },
  { id: "qcm-sp17", type: "qcm", theme: "Sport", question: "En NBA, combien de fautes personnelles entraînent une exclusion ?", answer: "6", options: ["5", "6", "7", "4"], points: 150 },
  { id: "qcm-sp18", type: "qcm", theme: "Sport", question: "Quelle est la distance officielle d’un marathon ?", answer: "42,195 km", options: ["42,167 km", "42,143 km", "42,195 km", "42,205 km"], points: 110 },
  { id: "qcm-sp19", type: "qcm", theme: "Sport", question: "Dans quel sport utilise-t-on le terme 'ace' ?", answer: "Tennis", options: ["Baseball", "Tennis", "Golf", "Volley"], points: 80 },
  { id: "qcm-sp20", type: "qcm", theme: "Sport", question: "Quel pays a inventé le football moderne ?", answer: "Angleterre", options: ["Brésil", "France", "Angleterre", "Italie"], points: 120 },
  { id: "qcm-sp21", type: "qcm", theme: "Sport", question: "Combien de trous compte un parcours de golf standard ?", answer: "18", options: ["9", "12", "18", "24"], points: 100 },
  { id: "qcm-sp22", type: "qcm", theme: "Sport", question: "Combien de points vaut un panier à trois points au basket ?", answer: "3", options: ["2", "3", "4", "5"], points: 70 },
  { id: "qcm-sp23", type: "qcm", theme: "Sport", question: "Quel est le sport de Lionel Messi ?", answer: "Football", options: ["Basket", "Football", "Tennis", "Rugby"], points: 60 },
  { id: "qcm-sp24", type: "qcm", theme: "Sport", question: "Quel sport se joue avec une raquette et un volant ?", answer: "Badminton", options: ["Tennis", "Squash", "Badminton", "Ping-pong"], points: 60 },
  { id: "qcm-sp25", type: "qcm", theme: "Sport", question: "Combien de joueurs composent une équipe de football sur le terrain ?", answer: "11", options: ["9", "10", "11", "12"], points: 60 },

  // --- DESSIN ANIMÉ / MANGA ---
  { id: "qcm-da1", type: "qcm", theme: "Dessin animé", question: "Comment s'appelle le lionceau héros du film 'Le Roi Lion' ?", answer: "Simba", options: ["Mufasa", "Scar", "Kovu", "Simba"], points: 60 },
  { id: "qcm-da2", type: "qcm", theme: "Dessin animé", question: "Dans le manga 'Naruto', quel est le rêve du personnage principal ?", answer: "Devenir Hokage", options: ["Devenir pirate", "Trouver les boules de cristal", "Devenir Hokage", "Devenir un super saiyan"], points: 80 },
  { id: "qcm-da3", type: "qcm", theme: "Dessin animé", question: "Quel animal est le maître Shifu dans Kung Fu Panda ?", answer: "Un panda roux", options: ["Un panda roux", "Un raton laveur", "Un renard", "Un lémurien"], points: 130 },
  { id: "qcm-da4", type: "qcm", theme: "Dessin animé", question: "Quel est le nom de la méchante dans 'La Petite Sirène' ?", answer: "Ursula", options: ["Maléfique", "Cruella", "Ursula", "Gothel"], points: 90 },
  { id: "qcm-da5", type: "qcm", theme: "Dessin animé", question: "Dans quel village ninja vit Naruto ?", answer: "Konoha", options: ["Suna", "Kiri", "Konoha", "Iwa"], points: 70 },
  { id: "qcm-da6", type: "qcm", theme: "Dessin animé", question: "De quel pays vient le célèbre studio d'animation Ghibli ?", answer: "Japon", options: ["Corée du Sud", "Chine", "Japon", "États-Unis"], points: 80 },
  { id: "qcm-da7", type: "qcm", theme: "Dessin animé", question: "Comment s'appellent les petites créatures jaunes dans 'Moi, moche et méchant' ?", answer: "Les Minions", options: ["Les Rabbids", "Les Minions", "Les Tic-Tacs", "Les Oompa Loompas"], points: 60 },
  { id: "qcm-da11", type: "qcm", theme: "Dessin animé", question: "Dans 'Attack on Titan', quel est le nom du Titan originel possédé par Eren ?", answer: "Titan Assaillant", options: ["Titan Colossal", "Titan Assaillant", "Titan Bestial", "Titan Cuirassé"], points: 160 },
  { id: "qcm-da12", type: "qcm", theme: "Dessin animé", question: "Dans 'Death Note', combien de règles contient initialement le Death Note ?", answer: "5", options: ["3", "5", "10", "13"], points: 190 },
  { id: "qcm-da13", type: "qcm", theme: "Dessin animé", question: "Dans 'One Piece', quel est le vrai nom du fruit du démon de Luffy ?", answer: "Hito Hito no Mi", options: ["Gomu Gomu no Mi", "Mera Mera no Mi", "Hito Hito no Mi", "Gura Gura no Mi"], points: 230 },
  { id: "qcm-da14", type: "qcm", theme: "Dessin animé", question: "Dans 'Fullmetal Alchemist', quel est le principe fondamental de l’alchimie ?", answer: "L’échange équivalent", options: ["La transmutation libre", "L’échange équivalent", "La magie noire", "La fusion spirituelle"], points: 150 },
  { id: "qcm-da15", type: "qcm", theme: "Dessin animé", question: "Dans 'Naruto', qui est le premier Hokage ?", answer: "Hashirama Senju", options: ["Tobirama Senju", "Hiruzen Sarutobi", "Hashirama Senju", "Minato Namikaze"], points: 180 },
  { id: "qcm-da16", type: "qcm", theme: "Dessin animé", question: "Dans 'Dragon Ball Z', qui est le premier à atteindre le Super Saiyan ?", answer: "Goku", options: ["Vegeta", "Gohan", "Goku", "Trunks"], points: 100 },
  { id: "qcm-da17", type: "qcm", theme: "Dessin animé", question: "Dans 'Rick et Morty', que signifie le 'C-137' ?", answer: "L’univers d’origine de Rick", options: ["Un code secret", "L’univers d’origine de Rick", "Une arme", "Un laboratoire"], points: 170 },
  { id: "qcm-da18", type: "qcm", theme: "Dessin animé", question: "Dans 'Arcane', quelle est la relation entre Vi et Jinx ?", answer: "Sœurs", options: ["Amies", "Sœurs", "Ennemies jurées", "Cousines"], points: 100 },
  { id: "qcm-da19", type: "qcm", theme: "Dessin animé", question: "Dans 'Le Voyage de Chihiro', quel est le vrai nom de Haku ?", answer: "Nigihayami Kohakunushi", options: ["Yubaba", "Nigihayami Kohakunushi", "Zeniba", "Kamaji"], points: 230 },
  { id: "qcm-da20", type: "qcm", theme: "Dessin animé", question: "Dans 'Avatar : Le dernier maître de l’air', quel élément Aang maîtrise-t-il en dernier ?", answer: "Feu", options: ["Eau", "Terre", "Feu", "Air"], points: 140 },
  { id: "qcm-da21", type: "qcm", theme: "Dessin animé", question: "Dans 'Les Simpsons', quel est le prénom du voisin Flanders ?", answer: "Ned", options: ["Todd", "Ned", "Rod", "Homer"], points: 90 },
  { id: "qcm-da22", type: "qcm", theme: "Dessin animé", question: "Dans 'Toy Story', comment s'appelle le voisin d’Andy ?", answer: "Sid", options: ["Andy", "Sid", "Woody", "Buzz"], points: 100 },
  { id: "qcm-da23", type: "qcm", theme: "Dessin animé", question: "Dans 'Shrek', quel animal est l’ami principal de Shrek ?", answer: "Un âne", options: ["Un chat", "Un âne", "Un dragon", "Un cheval"], points: 60 },
  { id: "qcm-da24", type: "qcm", theme: "Dessin animé", question: "Dans 'Pokémon', quel est le premier Pokémon du Pokédex ?", answer: "Bulbizarre", options: ["Pikachu", "Bulbizarre", "Salamèche", "Carapuce"], points: 80 },
  { id: "qcm-da25", type: "qcm", theme: "Dessin animé", question: "Dans 'Le Roi Lion', qui tue Mufasa ?", answer: "Scar", options: ["Simba", "Scar", "Hyènes", "Personne"], points: 60 },
  
  // --- MYTHOLOGIE ---
  { id: "qcm-my1", type: "qcm", theme: "Mythologie", question: "Qui est le roi des dieux grecs ?", answer: "Zeus", options: ["Hadès", "Poséidon", "Zeus", "Apollon"], points: 70 },
  { id: "qcm-my2", type: "qcm", theme: "Mythologie", question: "Quel animal accompagne souvent Athéna ?", answer: "La chouette", options: ["Le lion", "La chouette", "Le serpent", "L’aigle"], points: 110 },
  { id: "qcm-my3", type: "qcm", theme: "Mythologie", question: "Qui est le dieu nordique de la ruse ?", answer: "Loki", options: ["Thor", "Odin", "Loki", "Baldr"], points: 100 },
  { id: "qcm-my4", type: "qcm", theme: "Mythologie", question: "Quel héros grec est connu pour avoir été invincible sauf au talon ?", answer: "Achille", options: ["Hector", "Achille", "Ulysse", "Persée"], points: 90 },
  { id: "qcm-my5", type: "qcm", theme: "Mythologie", question: "Quel monstre garde l'entrée des Enfers ?", answer: "Cerbère", options: ["Hydre", "Cerbère", "Cyclope", "Sphinx"], points: 90 },
  { id: "qcm-my6", type: "qcm", theme: "Mythologie", question: "Qui est le dieu du soleil ?", answer: "Apollon", options: ["Hermès", "Apollon", "Arès", "Dionysos"], points: 90 },
  { id: "qcm-my7", type: "qcm", theme: "Mythologie", question: "Quel héros a tué Méduse ?", answer: "Persée", options: ["Thésée", "Persée", "Jason", "Achille"], points: 120 },
  { id: "qcm-my8", type: "qcm", theme: "Mythologie", question: "Quel dieu possède un trident ?", answer: "Poséidon", options: ["Zeus", "Poséidon", "Hadès", "Hermès"], points: 80 },
  { id: "qcm-my9", type: "qcm", theme: "Mythologie", question: "Quelle créature est moitié femme moitié oiseau ?", answer: "Sirène", options: ["Sphinx", "Sirène", "Gorgone", "Nymphe"], points: 150 },
  { id: "qcm-my10", type: "qcm", theme: "Mythologie", question: "Qui est le chef des dieux nordiques ?", answer: "Odin", options: ["Thor", "Odin", "Loki", "Heimdall"], points: 110 },
  { id: "qcm-my11", type: "qcm", theme: "Mythologie", question: "Qui est la femme de Zeus ?", answer: "Héra", options: ["Athéna", "Héra", "Artémis", "Déméter"], points: 100 },
  { id: "qcm-my12", type: "qcm", theme: "Mythologie", question: "Quel dieu est messager des dieux ?", answer: "Hermès", options: ["Apollon", "Hermès", "Arès", "Hadès"], points: 90 },
  { id: "qcm-my13", type: "qcm", theme: "Mythologie", question: "Quel héros a combattu l’Hydre ?", answer: "Hercule", options: ["Achille", "Persée", "Hercule", "Ulysse"], points: 110 },
  { id: "qcm-my14", type: "qcm", theme: "Mythologie", question: "Quel dieu est associé au vin ?", answer: "Dionysos", options: ["Apollon", "Hermès", "Dionysos", "Arès"], points: 110 },
  { id: "qcm-my15", type: "qcm", theme: "Mythologie", question: "Qui est le dieu du soleil en Égypte ?", answer: "Râ", options: ["Osiris", "Anubis", "Râ", "Horus"], points: 110 },
  { id: "qcm-my16", type: "qcm", theme: "Mythologie", question: "Quel monstre a un corps de lion et une tête humaine ?", answer: "Sphinx", options: ["Hydre", "Sphinx", "Cerbère", "Chimère"], points: 100 },
  { id: "qcm-my17", type: "qcm", theme: "Mythologie", question: "Qui a tué Hector ?", answer: "Achille", options: ["Ulysse", "Achille", "Ajax", "Persée"], points: 130 },
  { id: "qcm-my18", type: "qcm", theme: "Mythologie", question: "Quel dieu romain correspond à Zeus ?", answer: "Jupiter", options: ["Mars", "Jupiter", "Neptune", "Saturne"], points: 90 },
  { id: "qcm-my19", type: "qcm", theme: "Mythologie", question: "Quel dieu nordique est le dieu du tonnerre ?", answer: "Thor", options: ["Odin", "Thor", "Loki", "Baldr"], points: 80 },
  { id: "qcm-my20", type: "qcm", theme: "Mythologie", question: "Quel fleuve sépare les vivants des morts ?", answer: "Styx", options: ["Nil", "Styx", "Danube", "Tibre"], points: 120 },

  // --- MUSIQUE ---
  { id: "qcm-mu1", type: "qcm", theme: "Musique", question: "Combien y avait-il de membres officiels dans le groupe 'The Beatles' ?", answer: "4", options: ["3", "4", "5", "6"], points: 70 },
  { id: "qcm-mu2", type: "qcm", theme: "Musique", question: "Quel instrument est principalement utilisé par Slash (Guns N' Roses) ?", answer: "Guitare", options: ["Basse", "Batterie", "Guitare", "Piano"], points: 70 },
  { id: "qcm-mu3", type: "qcm", theme: "Musique", question: "Qui est surnommé 'The King' dans l'histoire du Rock'n'Roll ?", answer: "Elvis Presley", options: ["Chuck Berry", "Elvis Presley", "Little Richard", "Jerry Lee Lewis"], points: 70 },
  { id: "qcm-mu4", type: "qcm", theme: "Musique", question: "De quel pays est originaire le groupe ABBA ?", answer: "Suède", options: ["Norvège", "Danemark", "Suède", "Finlande"], points: 90 },
  { id: "qcm-mu5", type: "qcm", theme: "Musique", question: "Quel genre musical est né dans les années 70 à New York avec des DJ comme Kool Herc ?", answer: "Hip-hop", options: ["Disco", "Hip-hop", "Punk", "Jazz"], points: 100 },
  { id: "qcm-mu6", type: "qcm", theme: "Musique", question: "Quel instrument utilise un archet pour produire du son ?", answer: "Violon", options: ["Guitare", "Violon", "Harpe", "Luth"], points: 70 },
  { id: "qcm-mu7", type: "qcm", theme: "Musique", question: "Quel chanteur est l'interprète du tube 'Purple Rain' ?", answer: "Prince", points: 100, options: ["Michael Jackson", "Prince", "David Bowie", "George Michael"] },
  { id: "qcm-mu8", type: "qcm", theme: "Musique", question: "Dans quel groupe Kurt Cobain était-il le chanteur ?", answer: "Nirvana", options: ["Pearl Jam", "Soundgarden", "Nirvana", "Alice in Chains"], points: 80 },
  { id: "qcm-mu9", type: "qcm", theme: "Musique", question: "Quel célèbre compositeur a écrit 'Les Quatre Saisons' ?", answer: "Antonio Vivaldi", options: ["Johann Sebastian Bach", "Antonio Vivaldi", "Arcangelo Corelli", "Claudio Monteverdi"], points: 120 },
  { id: "qcm-mu10", type: "qcm", theme: "Musique", question: "Quelle était la particularité physique de Ray Charles et Stevie Wonder ?", answer: "Aveugles", options: ["Sourds", "Aveugles", "Muets", "Paralysés"], points: 90 },
  { id: "qcm-mu11", type: "qcm", theme: "Musique", question: "Qui est le chanteur principal du groupe d'heavy metal Iron Maiden ?", answer: "Bruce Dickinson", options: ["Ozzy Osbourne", "Bruce Dickinson", "James Hetfield", "Rob Halford"], points: 160 },
  { id: "qcm-mu12", type: "qcm", theme: "Musique", question: "Quel album de Pink Floyd est célèbre pour sa pochette représentant un prisme ?", answer: "The Dark Side of the Moon", options: ["The Wall", "Wish You Were Here", "The Dark Side of the Moon", "Animals"], points: 110 },
  { id: "qcm-mu13", type: "qcm", theme: "Musique", question: "En musique, que signifie l'indication 'Andante' ?", answer: "À une allure modérée", options: ["Très rapide", "Très lent", "À une allure modérée", "En augmentant le volume"], points: 140 },
  { id: "qcm-mu14", type: "qcm", theme: "Musique", question: "Quel instrument de la famille des cuivres possède le son le plus grave ?", answer: "Le tuba", options: ["Le trombone", "Le tuba", "Le cor d'harmonie", "La trompette"], points: 130 },
  { id: "qcm-mu15", type: "qcm", theme: "Musique", question: "Quel festival mythique s'est déroulé en 1969 avec pour slogan '3 jours de paix et de musique' ?", answer: "Woodstock", options: ["Coachella", "Lollapalooza", "Woodstock", "Glastonbury"], points: 110 },
  { id: "qcm-mu16", type: "qcm", theme: "Musique", question: "Comment s'appelle le premier clip diffusé sur la chaîne MTV en 1981 ?", answer: "Video Killed the Radio Star", options: ["Thriller", "Video Killed the Radio Star", "Like a Virgin", "Bohemian Rhapsody"], points: 180 },
  { id: "qcm-mu17", type: "qcm", theme: "Musique", question: "Qui est considéré comme le 'Père de la Soul' ?", answer: "Ray Charles", options: ["James Brown", "Otis Redding", "Ray Charles", "Marvin Gaye"], points: 160 },
  { id: "qcm-mu18", type: "qcm", theme: "Musique", question: "Quelle clé est généralement utilisée pour les instruments graves comme la basse ou le violoncelle ?", answer: "Clé de Fa", options: ["Clé de Sol", "Clé d'Ut", "Clé de Fa", "Clé de Ré"], points: 130 },
  { id: "qcm-mu19", type: "qcm", theme: "Musique", question: "Quel est le surnom donné à Antonio Vivaldi en raison de sa chevelure ?", answer: "Le Prêtre Roux", options: ["Le Lion de Venise", "Le Prêtre Roux", "L'Archange Italien", "Le Maestro de Glace"], points: 210 },
  { id: "qcm-mu20", type: "qcm", theme: "Musique", question: "Quel instrument électronique joue-t-on sans jamais le toucher physiquement ?", answer: "Le Thérémine", options: ["L'Onde Martenot", "Le Moog", "Le Thérémine", "Le Vocoder"], points: 230 },
  { id: "qcm-mu21", type: "qcm", theme: "Musique", question: "Quel compositeur est l'auteur des 'Variations Goldberg' ?", answer: "Johann Sebastian Bach", options: ["Ludwig van Beethoven", "Johann Sebastian Bach", "Johannes Brahms", "Franz Liszt"], points: 190 },
  { id: "qcm-mu22", type: "qcm", theme: "Musique", question: "Dans quel opéra de Wagner entend-on la célèbre 'Chevauchée des Walkyries' ?", answer: "La Walkyrie", options: ["Siegfried", "La Walkyrie", "L'Or du Rhin", "Le Crépuscule des dieux"], points: 160 },
  { id: "qcm-mu23", type: "qcm", theme: "Musique", question: "Quel était le prénom d'origine de Jimi Hendrix ?", answer: "Johnny", options: ["James", "Robert", "Johnny", "William"], points: 180 },
  { id: "qcm-mu24", type: "qcm", theme: "Musique", question: "Lequel de ces artistes n'est PAS membre du 'Club des 27' ?", answer: "Sid Vicious", options: ["Jim Morrison", "Sid Vicious", "Janis Joplin", "Brian Jones"], points: 170 },
  { id: "qcm-mu25", type: "qcm", theme: "Musique", question: "Quelle est la nationalité du compositeur Jean Sibelius ?", answer: "Finlandaise", options: ["Suédoise", "Finlandaise", "Norvégienne", "Russe"], points: 190 },
  { id: "qcm-mu26", type: "qcm", theme: "Musique", question: "Quel pianiste de Jazz est l'auteur de l'album 'Kind of Blue' ?", answer: "Miles Davis", options: ["John Coltrane", "Miles Davis", "Thelonious Monk", "Bill Evans"], points: 190 },
  { id: "qcm-mu27", type: "qcm", theme: "Musique", question: "Quel est l'intervalle exact entre la note Do et la note Sol ?", answer: "Quinte juste", options: ["Quarte juste", "Quinte juste", "Sixte majeure", "Tierce mineure"], points: 200 },
  { id: "qcm-mu28", type: "qcm", theme: "Musique", question: "Qui a écrit l'hymne de la joie (le poème) utilisé par Beethoven dans sa 9ème symphonie ?", answer: "Friedrich von Schiller", options: ["Johann Wolfgang von Goethe", "Friedrich von Schiller", "Heinrich Heine", "Arthur Schopenhauer"], points: 220 },
  { id: "qcm-mu29", type: "qcm", theme: "Musique", question: "Quelle ville est considérée comme le berceau de la techno ?", answer: "Détroit", options: ["Berlin", "Chicago", "Détroit", "Londres"], points: 170 },
  { id: "qcm-mu30", type: "qcm", theme: "Musique", question: "Quel groupe de rock a sorti l'album 'Physical Graffiti' ?", answer: "Led Zeppelin", options: ["The Who", "Led Zeppelin", "Deep Purple", "Black Sabbath"], points: 170 },
  { id: "qcm-mu31", type: "qcm", theme: "Musique", question: "Combien de cordes possède traditionnellement un violoncelle ?", answer: "4", options: ["3", "4", "5", "6"], points: 110 },
  { id: "qcm-mu32", type: "qcm", theme: "Musique", question: "Quel artiste a enregistré l'album 'At Folsom Prison' ?", answer: "Johnny Cash", options: ["Willie Nelson", "Johnny Cash", "Waylon Jennings", "Kris Kristofferson"], points: 160 },
  { id: "qcm-mu33", type: "qcm", theme: "Musique", question: "Quel est le vrai nom de scène de Marshall Mathers ?", answer: "Eminem", options: ["Snoop Dogg", "Eminem", "Dr. Dre", "Jay-Z"], points: 100 },
  { id: "qcm-mu34", type: "qcm", theme: "Musique", question: "Quelle chanteuse est surnommée 'The Queen of Soul' ?", answer: "Aretha Franklin", options: ["Diana Ross", "Aretha Franklin", "Etta James", "Tina Turner"], points: 130 },
  { id: "qcm-mu35", type: "qcm", theme: "Musique", question: "Dans quel groupe jouait Eric Clapton avant sa carrière solo (avec Ginger Baker) ?", answer: "Cream", options: ["The Yardbirds", "Cream", "The Animals", "Fleetwood Mac"], points: 180 },
  { id: "qcm-mu36", type: "qcm", theme: "Musique", question: "Comment appelle-t-on le registre vocal de femme le plus aigu ?", answer: "Soprano", options: ["Mezzo-soprano", "Contralto", "Soprano", "Alto"], points: 120 },
  { id: "qcm-mu37", type: "qcm", theme: "Musique", question: "Quelle chanson de Luis Fonsi détient l'un des plus gros records de vues sur YouTube ?", answer: "Despacito", options: ["Despacito", "Gasolina", "Bailando", "Mi Gente"], points: 70 },
  { id: "qcm-mu38", type: "qcm", theme: "Musique", question: "Quel est l'instrument de prédilection de Ian Anderson (Jethro Tull) ?", answer: "La flûte traversière", options: ["La guitare", "Le violon", "La flûte traversière", "L'orgue"], points: 210 },
  { id: "qcm-mu39", type: "qcm", theme: "Musique", question: "Quel compositeur est célèbre pour son 'Boléro' ?", answer: "Maurice Ravel", options: ["Claude Debussy", "Maurice Ravel", "Erik Satie", "Gabriel Fauré"], points: 130 },
  { id: "qcm-mu40", type: "qcm", theme: "Musique", question: "Quel groupe britannique a sorti l'album 'London Calling' ?", answer: "The Clash", options: ["The Sex Pistols", "The Clash", "The Jam", "Ramones"], points: 160 }
];