import type { QuizQuestion } from "../quiz-bank";

export const qcmQuestions: QuizQuestion[] = [
  { id: "qcm1", type: "qcm", theme: "Géographie", question: "Quelle est la capitale de l'Australie ?", answer: "Canberra", options: ["Sydney", "Melbourne", "Canberra", "Perth"], points: 100 },
  { id: "qcm2", type: "qcm", theme: "Sciences", question: "Quel est l'animal le plus rapide du monde en piqué ?", answer: "Le faucon pèlerin", options: ["Le guépard", "L'aigle royal", "Le faucon pèlerin", "L'espadon"], points: 100 },
  { id: "qcm3", type: "qcm", theme: "Sciences", question: "Quel est le métal le plus abondant dans la croûte terrestre ?", answer: "L'aluminium", options: ["Le fer", "L'or", "Le cuivre", "L'aluminium"], points: 100 },
  { id: "qcm4", type: "qcm", theme: "Culture G", question: "Qui a peint La Jeune Fille à la perle ?", answer: "Johannes Vermeer", options: ["Vincent van Gogh", "Johannes Vermeer", "Rembrandt", "Claude Monet"], points: 100 },
  { id: "qcm5", type: "qcm", theme: "Géographie", question: "Combien y a-t-il de fuseaux horaires en Russie ?", answer: "11", options: ["7", "9", "11", "13"], points: 100 },
  { id: "qcm6", type: "qcm", theme: "Géographie", question: "Quel est le plus grand océan de la Terre ?", answer: "Océan Pacifique", options: ["Océan Atlantique", "Océan Indien", "Océan Pacifique", "Océan Arctique"], points: 100 },
  { id: "qcm7", type: "qcm", theme: "Sciences", question: "Quelle planète est surnommée l'étoile du berger ?", answer: "Vénus", options: ["Mars", "Vénus", "Jupiter", "Mercure"], points: 100 },
  { id: "qcm8", type: "qcm", theme: "Géographie", question: "Dans quel pays se trouve la ville de Tombouctou ?", answer: "Mali", options: ["Sénégal", "Niger", "Mali", "Maroc"], points: 100 },
  { id: "qcm9", type: "qcm", theme: "Culture G", question: "Quel est le nom du bateau dans Le Vieil Homme et la Mer ?", answer: "Il n'a pas de nom", options: ["L'Orca", "Le Pilar", "Le Pequod", "Il n'a pas de nom"], points: 100 },
  { id: "qcm10", type: "qcm", theme: "Culture G", question: "Quel ingrédient principal compose le guacamole ?", answer: "Avocat", options: ["Tomate", "Avocat", "Piment", "Citron vert"], points: 100 },
  { id: "qcm11", type: "qcm", theme: "Sciences", question: "Quel est le plus grand os du corps humain ?", answer: "Le fémur", options: ["Le tibia", "Le fémur", "L'humérus", "Le péroné"], points: 100 },
  { id: "qcm12", type: "qcm", theme: "Géographie", question: "Quelle est la monnaie du Japon ?", answer: "Le Yen", options: ["Le Yuan", "Le Won", "Le Yen", "Le Ringgit"], points: 100 },
  { id: "qcm13", type: "qcm", theme: "Culture G", question: "Qui est le dieu grec des enfers ?", answer: "Hadès", options: ["Ares", "Apollon", "Poséidon", "Hadès"], points: 100 },
  { id: "qcm14", type: "qcm", theme: "Culture G", question: "Quelle série met en scène Walter White ?", answer: "Breaking Bad", options: ["Prison Break", "Dexter", "Breaking Bad", "The Wire"], points: 100 },
  { id: "qcm15", type: "qcm", theme: "Sciences", question: "En informatique, que signifie 'RAM' ?", answer: "Random Access Memory", options: ["Read Access Memory", "Random Access Memory", "Run All Memory", "Real Allocation Mode"], points: 100 },
  { id: "qcm16", type: "qcm", theme: "Sciences", question: "Quel gaz compose majoritairement l'air que nous respirons ?", answer: "Azote", options: ["Oxygène", "Azote", "Gaz carbonique", "Hydrogène"], points: 100 },
  { id: "qcm17", type: "qcm", theme: "Culture G", question: "Quel pays a remporté le plus de Coupes du Monde de football ?", answer: "Brésil", options: ["Allemagne", "Italie", "France", "Brésil"], points: 100 },
  { id: "qcm18", type: "qcm", theme: "Géographie", question: "Quelle est la capitale de l'Islande ?", answer: "Reykjavik", options: ["Oslo", "Reykjavik", "Stockholm", "Helsinki"], points: 100 },
  { id: "qcm19", type: "qcm", theme: "Culture G", question: "Qui a écrit le roman '1984' ?", answer: "George Orwell", options: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "Ernest Hemingway"], points: 100 },
  { id: "qcm20", type: "qcm", theme: "Sciences", question: "Quelle est la vitesse de la lumière (environ) ?", answer: "300 000 km/s", options: ["150 000 km/s", "300 000 km/s", "1 000 000 km/s", "300 000 km/h"], points: 120 },
  { id: "qcm21", type: "qcm", theme: "Géographie", question: "Quel est le plus grand pays du monde par la taille ?", answer: "Russie", options: ["Canada", "Chine", "États-Unis", "Russie"], points: 80 },
  { id: "qcm22", type: "qcm", theme: "Géographie", question: "Dans quelle ville se trouve le Colisée ?", answer: "Rome", options: ["Athènes", "Rome", "Naples", "Florence"], points: 80 },
  { id: "qcm23", type: "qcm", theme: "Sciences", question: "Quel est le nom de la galaxie dans laquelle nous vivons ?", answer: "La Voie Lactée", options: ["Andromède", "La Voie Lactée", "La Grande Ourse", "Orion"], points: 100 },
  { id: "qcm24", type: "qcm", theme: "Sciences", question: "Quel est l'oiseau qui pond les plus gros œufs ?", answer: "L'autruche", options: ["L'aigle", "L'autruche", "Le condor", "L'émeu"], points: 100 },
  { id: "qcm25", type: "qcm", theme: "Géographie", question: "Dans quelle ville se trouve le siège de l'ONU ?", answer: "New York", options: ["Genève", "Washington", "New York", "Bruxelles"], points: 100 },
  { id: "qcm26", type: "qcm", theme: "Sciences", question: "Quel est l'élément chimique le plus léger ?", answer: "Hydrogène", options: ["Hélium", "Oxygène", "Azote", "Hydrogène"], points: 100 },
  { id: "qcm27", type: "qcm", theme: "Culture G", question: "Qui a écrit 'Les Fleurs du Mal' ?", answer: "Charles Baudelaire", options: ["Victor Hugo", "Charles Baudelaire", "Arthur Rimbaud", "Paul Verlaine"], points: 100 },
  { id: "qcm28", type: "qcm", theme: "Culture G", question: "Combien de cordes possède une guitare classique ?", answer: "6", options: ["4", "5", "6", "12"], points: 80 },
  { id: "qcm29", type: "qcm", theme: "Géographie", question: "Quel est le plus petit pays du monde ?", answer: "Vatican", options: ["Monaco", "Saint-Marin", "Vatican", "Andorre"], points: 100 },
  { id: "qcm30", type: "qcm", theme: "Géographie", question: "Quelle est la capitale du Canada ?", answer: "Ottawa", options: ["Toronto", "Montréal", "Ottawa", "Québec"], points: 100 },
  { id: "qcm31", type: "qcm", theme: "Sciences", question: "Quel organe produit l'insuline ?", answer: "Le pancréas", options: ["Le foie", "Le pancréas", "La rate", "Les reins"], points: 120 },
  { id: "qcm32", type: "qcm", theme: "Culture G", question: "Qui a réalisé le film 'Inception' ?", answer: "Christopher Nolan", options: ["Steven Spielberg", "Christopher Nolan", "Quentin Tarantino", "Martin Scorsese"], points: 100 },
  { id: "qcm33", type: "qcm", theme: "Sciences", question: "Quel est le plus grand mammifère terrestre ?", answer: "L'éléphant d'Afrique", options: ["Le rhinocéros", "L'éléphant d'Afrique", "La girafe", "L'hippopotame"], points: 80 },
  { id: "qcm34", type: "qcm", theme: "Histoire", question: "Quel empire était dirigé par Soliman le Magnifique ?", answer: "L'Empire Ottoman", options: ["L'Empire Perse", "L'Empire Ottoman", "L'Empire Moghol", "L'Empire Romain"], points: 100 },
  { id: "qcm35", type: "qcm", theme: "Géographie", question: "Quelle est la capitale la plus haute du monde (altitude) ?", answer: "La Paz", options: ["Quito", "La Paz", "Bogota", "Lhassa"], points: 120 },
  { id: "qcm36", type: "qcm", theme: "Histoire", question: "En quelle année a été découvert le tombeau de Toutânkhamon ?", answer: "1922", options: ["1898", "1912", "1922", "1936"], points: 100 },
  { id: "qcm37", type: "qcm", theme: "Géographie", question: "Lequel de ces pays ne possède pas d'accès à la mer ?", answer: "Suisse", options: ["Belgique", "Suisse", "Norvège", "Portugal"], points: 80 },
  { id: "qcm38", type: "qcm", theme: "Histoire", question: "Qui était le président des USA durant la Guerre de Sécession ?", answer: "Abraham Lincoln", options: ["George Washington", "Andrew Jackson", "Abraham Lincoln", "Ulysses S. Grant"], points: 100 },
  { id: "qcm39", type: "qcm", theme: "Géographie", question: "Quel fleuve traverse le plus grand nombre de pays ?", answer: "Le Danube", options: ["Le Nil", "L'Amazone", "Le Danube", "Le Rhin"], points: 120 },
  { id: "qcm40", type: "qcm", theme: "Histoire", question: "Quelle était la capitale de l'Empire Inca ?", answer: "Cuzco", options: ["Machu Picchu", "Lima", "Quito", "Cuzco"], points: 100 },
  { id: "qcm41", type: "qcm", theme: "Géographie", question: "Quel pays possède le plus d'îles au monde ?", answer: "La Suède", options: ["L'Indonésie", "La Grèce", "Le Canada", "La Suède"], points: 150 },
  { id: "qcm-sp1", type: "qcm", theme: "Sport", question: "Dans quel sport s'illustre Rafael Nadal ?", answer: "Tennis", options: ["Football", "Tennis", "Golf", "Basket-ball"], points: 100 },
  { id: "qcm-sp2", type: "qcm", theme: "Sport", question: "Quelle est la durée réglementaire d'un match de football (sans prolongations) ?", answer: "90 minutes", options: ["60 minutes", "80 minutes", "90 minutes", "120 minutes"], points: 100 },
  { id: "qcm-da1", type: "qcm", theme: "Dessin animé", question: "Comment s'appelle le lionceau héros du film 'Le Roi Lion' ?", answer: "Simba", options: ["Mufasa", "Scar", "Kovu", "Simba"], points: 100 },
  { id: "qcm-da2", type: "qcm", theme: "Dessin animé", question: "Dans le manga 'Naruto', quel est le rêve du personnage principal ?", answer: "Devenir Hokage", options: ["Devenir pirate", "Trouver les boules de cristal", "Devenir Hokage", "Devenir un super saiyan"], points: 100 },
  { id: "qcm-sp3", type: "qcm", theme: "Sport", question: "Quel pays a remporté la Coupe du Monde de football 2022 ?", answer: "Argentine", options: ["France", "Brésil", "Croatie", "Argentine"], points: 80 },
  { id: "qcm-sp4", type: "qcm", theme: "Sport", question: "Combien de joueurs composent une équipe de volley-ball sur le terrain ?", answer: "6", options: ["5", "6", "7", "11"], points: 100 },
  { id: "qcm-sp5", type: "qcm", theme: "Sport", question: "De quelle couleur est le maillot du leader du classement général sur le Tour de France ?", answer: "Jaune", options: ["Vert", "Jaune", "Blanc à pois rouges", "Rose"], points: 80 },
  { id: "qcm-sp6", type: "qcm", theme: "Sport", question: "Dans quel sport utilise-t-on le terme 'Home Run' ?", answer: "Baseball", options: ["Cricket", "Football Américain", "Baseball", "Hockey"], points: 100 },
  { id: "qcm-sp7", type: "qcm", theme: "Sport", question: "Quelle est la discipline de Teddy Riner ?", answer: "Judo", options: ["Karaté", "Boxe", "Lutte", "Judo"], points: 80 },
  { id: "qcm-da3", type: "qcm", theme: "Dessin animé", question: "Quel animal est le maître Shifu dans Kung Fu Panda ?", answer: "Un panda roux", options: ["Un panda roux", "Un raton laveur", "Un renard", "Un lémurien"], points: 120 },
  { id: "qcm-da4", type: "qcm", theme: "Dessin animé", question: "Quel est le nom de la méchante dans 'La Petite Sirène' ?", answer: "Ursula", options: ["Maléfique", "Cruella", "Ursula", "Gothel"], points: 100 },
  { id: "qcm-da5", type: "qcm", theme: "Dessin animé", question: "Dans quel village ninja vit Naruto ?", answer: "Konoha", options: ["Suna", "Kiri", "Konoha", "Iwa"], points: 100 },
  { id: "qcm-da6", type: "qcm", theme: "Dessin animé", question: "De quel pays vient le célèbre studio d'animation Ghibli ?", answer: "Japon", options: ["Corée du Sud", "Chine", "Japon", "États-Unis"], points: 80 },
  { id: "qcm-da7", type: "qcm", theme: "Dessin animé", question: "Comment s'appellent les petites créatures jaunes dans 'Moi, moche et méchant' ?", answer: "Les Minions", options: ["Les Rabbids", "Les Minions", "Les Tic-Tacs", "Les Oompa Loompas"], points: 80 },

];