import type { QuizQuestion } from "../quiz-bank";

export const trueFalseQuestions: QuizQuestion[] = [
  { id: "tf1", type: "true_false", theme: "Géographie", question: "La Grande Muraille de Chine est visible depuis la Lune à l'œil nu.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf2", type: "true_false", theme: "Sciences", question: "La tomate est botaniquement un fruit.", answer: "Vrai", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf3", type: "true_false", theme: "Sciences", question: "Les chauves-souris sont aveugles.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf4", type: "true_false", theme: "Sciences", question: "L'eau chaude gèle plus vite que l'eau froide.", answer: "Vrai", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf5", type: "true_false", theme: "Sciences", question: "Les humains n'utilisent que 10% de leur cerveau.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf6", type: "true_false", theme: "Géographie", question: "Le Sahara est le plus grand désert du monde.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf7", type: "true_false", theme: "Sciences", question: "Les poissons rouges ont une mémoire de 3 secondes.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf8", type: "true_false", theme: "Sciences", question: "Le miel ne se périme jamais.", answer: "Vrai", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf9", type: "true_false", theme: "Sciences", question: "La foudre ne tombe jamais deux fois au même endroit.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf10", type: "true_false", theme: "Histoire", question: "Napoléon Bonaparte était anormalement petit pour son époque.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf11", type: "true_false", theme: "Sciences", question: "Les autruches enfouissent leur tête dans le sable quand elles ont peur.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf12", type: "true_false", theme: "Sciences", question: "Un an sur Vénus est plus court qu'un jour sur Vénus.", answer: "Vrai", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf13", type: "true_false", theme: "Sciences", question: "Le sang des homards est bleu.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf14", type: "true_false", theme: "Sciences", question: "La langue est le muscle le plus fort du corps humain.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf15", type: "true_false", theme: "Sciences", question: "Les requins sont des mammifères.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf16", type: "true_false", theme: "Géographie", question: "Le drapeau du Népal est le seul au monde à ne pas être rectangulaire.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf17", type: "true_false", theme: "Culture G", question: "Walt Disney detient le record du plus grand nombre d'Oscars remportés.", answer: "Vrai", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf18", type: "true_false", theme: "Culture G", question: "L'inventeur de la machine à barbe à papa était un dentiste.", answer: "Vrai", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf19", type: "true_false", theme: "Sciences", question: "Le cri du canard ne produit pas d'écho.", answer: "Faux", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf20", type: "true_false", theme: "Sciences", question: "Il y a plus d'étoiles dans l'univers que de grains de sable sur Terre.", answer: "Vrai", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf21", type: "true_false", theme: "Géographie", question: "La lune est plus grande que l'Australie.", answer: "Faux", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf22", type: "true_false", theme: "Sciences", question: "Les pieuvres ont trois cœurs.", answer: "Vrai", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf23", type: "true_false", theme: "Sciences", question: "Le record de survie d'un poulet sans tête est de 18 mois.", answer: "Vrai", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf24", type: "true_false", theme: "Géographie", question: "L'Everest est la montagne la plus proche de l'espace.", answer: "Faux", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf25", type: "true_false", theme: "Sciences", question: "Un hippopotame peut courir plus vite qu'un humain.", answer: "Vrai", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf26", type: "true_false", theme: "Géographie", question: "La France est le pays avec le plus de fuseaux horaires au monde.", answer: "Vrai", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf27", type: "true_false", theme: "Sciences", question: "Les bananes poussent sur des arbres.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf28", type: "true_false", theme: "Sciences", question: "Le son voyage plus vite dans l'eau que dans l'air.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf29", type: "true_false", theme: "Sciences", question: "L'ADN humain est identique à 50% à celui d'une banane.", answer: "Vrai", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf30", type: "true_false", theme: "Sciences", question: "Le cœur d'une crevette se situe dans sa tête.", answer: "Vrai", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf31", type: "true_false", theme: "Sciences", question: "Les antibiotiques sont efficaces contre les virus.", answer: "Faux", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf32", type: "true_false", theme: "Sciences", question: "Le fémur est l'os le plus solide du corps humain.", answer: "Vrai", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf33", type: "true_false", theme: "Sciences", question: "Le son peut se propager dans le vide spatial.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf34", type: "true_false", theme: "Sciences", question: "Les neurones sont les seules cellules du corps qui ne se divisent jamais.", answer: "Faux", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf35", type: "true_false", theme: "Sciences", question: "Un éclair est cinq fois plus chaud que la surface du Soleil.", answer: "Vrai", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf36", type: "true_false", theme: "Sciences", question: "Les veines transportent toujours du sang pauvre en oxygène.", answer: "Faux", options: ["Vrai", "Faux"], points: 100 },
  { id: "tf-sp1", type: "true_false", theme: "Sport", question: "Le tennis de table est un sport olympique.", answer: "Vrai", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf-sp2", type: "true_false", theme: "Sport", question: "Au tennis, le point qui vient après 30 est 45.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf-sp3", type: "true_false", theme: "Sport", question: "Un match de rugby à XV dure 80 minutes.", answer: "Vrai", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf-da1", type: "true_false", theme: "Dessin animé", question: "Pikachu est un Pokémon de type Électrik.", answer: "Vrai", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf-da2", type: "true_false", theme: "Dessin animé", question: "Dans 'Toy Story', le dinosaure vert s'appelle Woody.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf-sp4", type: "true_false", theme: "Sport", question: "Usain Bolt détient le record du monde du 100m.", answer: "Vrai", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf-sp5", type: "true_false", theme: "Sport", question: "Au basket-ball, un tir réussi de très loin vaut 4 points.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf-sp6", type: "true_false", theme: "Sport", question: "Le Tour de France est la compétition cycliste la plus suivie au monde.", answer: "Vrai", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf-sp7", type: "true_false", theme: "Sport", question: "Une partie de bowling se compose de 15 manches (frames).", answer: "Faux", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-sp8", type: "true_false", theme: "Sport", question: "La ceinture noire est la ceinture la plus élevée que l'on puisse atteindre au judo.", answer: "Faux", options: ["Vrai", "Faux"], points: 80 }, // C'est la rouge (largement méconnu !)
  { id: "tf-da3", type: "true_false", theme: "Dessin animé", question: "Homer Simpson travaille dans une centrale nucléaire.", answer: "Vrai", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf-da4", type: "true_false", theme: "Dessin animé", question: "Mickey Mouse devait initialement s'appeler Mortimer.", answer: "Vrai", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf-da5", type: "true_false", theme: "Dessin animé", question: "Dans 'La Reine des Neiges', le bonhomme de neige s'appelle Sven.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 }, // Sven c'est le renne, Olaf le bonhomme de neige
  { id: "tf-da6", type: "true_false", theme: "Dessin animé", question: "Shrek est un ogre de couleur bleue.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf-da7", type: "true_false", theme: "Dessin animé", question: "Bob l'éponge travaille au Crabe Croustillant.", answer: "Vrai", options: ["Vrai", "Faux"], points: 50 },

];