import type { QuizQuestion } from "../quiz-bank";

export const trueFalseQuestions: QuizQuestion[] = [
  // --- GÉOGRAPHIE ---
  { id: "tf1", type: "true_false", theme: "Géographie", question: "La Grande Muraille de Chine est visible depuis la Lune à l'œil nu.", answer: "Faux", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf6", type: "true_false", theme: "Géographie", question: "Le Sahara est le plus grand désert du monde.", answer: "Faux", options: ["Vrai", "Faux"], points: 130 },
  { id: "tf16", type: "true_false", theme: "Géographie", question: "Le drapeau du Népal est le seul au monde à ne pas être rectangulaire.", answer: "Vrai", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf21", type: "true_false", theme: "Géographie", question: "La lune est plus grande que l'Australie.", answer: "Faux", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf24", type: "true_false", theme: "Géographie", question: "L'Everest est la montagne la plus proche de l'espace.", answer: "Faux", options: ["Vrai", "Faux"], points: 140 },
  { id: "tf26", type: "true_false", theme: "Géographie", question: "La France est le pays avec le plus de fuseaux horaires au monde.", answer: "Vrai", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf40", type: "true_false", theme: "Géographie", question: "L'Australie est plus grande en superficie que l'Europe.", answer: "Vrai", options: ["Vrai", "Faux"], points: 110 },
  { id: "tf41", type: "true_false", theme: "Géographie", question: "La Russie est à cheval sur deux continents : l'Europe et l'Asie.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf42", type: "true_false", theme: "Géographie", question: "L'Équateur traverse uniquement l'Afrique.", answer: "Faux", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf43", type: "true_false", theme: "Géographie", question: "La capitale de la Suisse est Zurich.", answer: "Faux", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf44", type: "true_false", theme: "Géographie", question: "Le Nil se jette dans la mer Méditerranée.", answer: "Vrai", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf45", type: "true_false", theme: "Géographie", question: "L’Antarctique est considéré comme un désert.", answer: "Vrai", options: ["Vrai", "Faux"], points: 110 },

  // --- SCIENCES ---
  { id: "tf2", type: "true_false", theme: "Sciences", question: "La tomate est botaniquement un fruit.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf3", type: "true_false", theme: "Sciences", question: "Les chauves-souris sont aveugles.", answer: "Faux", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf4", type: "true_false", theme: "Sciences", question: "L'eau chaude gèle plus vite que l'eau froide.", answer: "Vrai", options: ["Vrai", "Faux"], points: 160 },
  { id: "tf5", type: "true_false", theme: "Sciences", question: "Les humains n'utilisent que 10% de leur cerveau.", answer: "Faux", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf7", type: "true_false", theme: "Sciences", question: "Les poissons rouges ont une mémoire de 3 secondes.", answer: "Faux", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf8", type: "true_false", theme: "Sciences", question: "Le miel ne se périme jamais.", answer: "Vrai", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf9", type: "true_false", theme: "Sciences", question: "La foudre ne tombe jamais deux fois au même endroit.", answer: "Faux", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf11", type: "true_false", theme: "Sciences", question: "Les autruches enfouissent leur tête dans le sable quand elles ont peur.", answer: "Faux", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf12", type: "true_false", theme: "Sciences", question: "Un an sur Vénus est plus court qu'un jour sur Vénus.", answer: "Vrai", options: ["Vrai", "Faux"], points: 150 },
  { id: "tf13", type: "true_false", theme: "Sciences", question: "Le sang des homards est bleu.", answer: "Vrai", options: ["Vrai", "Faux"], points: 130 },
  { id: "tf14", type: "true_false", theme: "Sciences", question: "La langue est le muscle le plus fort du corps humain.", answer: "Faux", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf15", type: "true_false", theme: "Sciences", question: "Les requins sont des mammifères.", answer: "Faux", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf19", type: "true_false", theme: "Sciences", question: "Le cri du canard ne produit pas d'écho.", answer: "Faux", options: ["Vrai", "Faux"], points: 110 },
  { id: "tf20", type: "true_false", theme: "Sciences", question: "Il y a plus d'étoiles dans l'univers que de grains de sable sur Terre.", answer: "Vrai", options: ["Vrai", "Faux"], points: 100 },
  { id: "tf22", type: "true_false", theme: "Sciences", question: "Les pieuvres ont trois cœurs.", answer: "Vrai", options: ["Vrai", "Faux"], points: 110 },
  { id: "tf23", type: "true_false", theme: "Sciences", question: "Le record de survie d'un poulet sans tête est de 18 mois.", answer: "Vrai", options: ["Vrai", "Faux"], points: 170 },
  { id: "tf25", type: "true_false", theme: "Sciences", question: "Un hippopotame peut courir plus vite qu'un humain.", answer: "Vrai", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf27", type: "true_false", theme: "Sciences", question: "Les bananes poussent sur des arbres.", answer: "Faux", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf28", type: "true_false", theme: "Sciences", question: "Le son voyage plus vite dans l'eau que dans l'air.", answer: "Vrai", options: ["Vrai", "Faux"], points: 130 },
  { id: "tf29", type: "true_false", theme: "Sciences", question: "L'ADN humain est identique à 50% à celui d'une banane.", answer: "Vrai", options: ["Vrai", "Faux"], points: 150 },
  { id: "tf30", type: "true_false", theme: "Sciences", question: "Le cœur d'une crevette se situe dans sa tête.", answer: "Vrai", options: ["Vrai", "Faux"], points: 160 },
  { id: "tf31", type: "true_false", theme: "Sciences", question: "Les antibiotiques sont efficaces contre les virus.", answer: "Faux", options: ["Vrai", "Faux"], points: 100 },
  { id: "tf32", type: "true_false", theme: "Sciences", question: "Le fémur est l'os le plus solide du corps humain.", answer: "Vrai", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf33", type: "true_false", theme: "Sciences", question: "Le son peut se propager dans le vide spatial.", answer: "Faux", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf34", type: "true_false", theme: "Sciences", question: "Les neurones sont les seules cellules du corps qui ne se divisent jamais.", answer: "Faux", options: ["Vrai", "Faux"], points: 180 },
  { id: "tf35", type: "true_false", theme: "Sciences", question: "Un éclair est cinq fois plus chaud que la surface du Soleil.", answer: "Vrai", options: ["Vrai", "Faux"], points: 150 },
  { id: "tf36", type: "true_false", theme: "Sciences", question: "Les veines transportent toujours du sang pauvre en oxygène.", answer: "Faux", options: ["Vrai", "Faux"], points: 170 },
  { id: "tf46", type: "true_false", theme: "Sciences", question: "Les ongles des mains poussent plus vite que ceux des pieds.", answer: "Vrai", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf47", type: "true_false", theme: "Sciences", question: "Tous les serpents sont venimeux.", answer: "Faux", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf48", type: "true_false", theme: "Sciences", question: "Une année sur Terre dure exactement 365 jours.", answer: "Faux", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf49", type: "true_false", theme: "Sciences", question: "Le cerveau humain ne ressent pas directement la douleur.", answer: "Vrai", options: ["Vrai", "Faux"], points: 140 },
  { id: "tf50", type: "true_false", theme: "Sciences", question: "Les cheveux et les ongles continuent de pousser après la mort.", answer: "Faux", options: ["Vrai", "Faux"], points: 110 },
  { id: "tf51", type: "true_false", theme: "Sciences", question: "L’homme partage environ 98% de son ADN avec le chimpanzé.", answer: "Vrai", options: ["Vrai", "Faux"], points: 100 },
  { id: "tf52", type: "true_false", theme: "Sciences", question: "Les plantes respirent uniquement la nuit.", answer: "Faux", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf53", type: "true_false", theme: "Sciences", question: "Les baleines sont des poissons.", answer: "Faux", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf54", type: "true_false", theme: "Sciences", question: "La lumière peut être déviée par la gravité.", answer: "Vrai", options: ["Vrai", "Faux"], points: 190 },
  { id: "tf55", type: "true_false", theme: "Sciences", question: "Un humain adulte possède plus de 500 os.", answer: "Faux", options: ["Vrai", "Faux"], points: 70 },

  // --- HISTOIRE ---
  { id: "tf10", type: "true_false", theme: "Histoire", question: "Napoléon Bonaparte était anormalement petit pour son époque.", answer: "Faux", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf56", type: "true_false", theme: "Histoire", question: "Jules César a été empereur de Rome.", answer: "Faux", options: ["Vrai", "Faux"], points: 130 },
  { id: "tf57", type: "true_false", theme: "Histoire", question: "La Révolution française a commencé en 1789.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf58", type: "true_false", theme: "Histoire", question: "L’URSS a cessé d’exister dans les années 1990.", answer: "Vrai", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf59", type: "true_false", theme: "Histoire", question: "La guerre de Cent Ans a duré exactement 100 ans.", answer: "Faux", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf60", type: "true_false", theme: "Histoire", question: "Les pyramides de Gizeh ont été construites avant l’Empire romain.", answer: "Vrai", options: ["Vrai", "Faux"], points: 100 },
  { id: "tf-hist11", type: "true_false", theme: "Histoire", question: "Napoléon a vendu la Louisiane aux États-Unis.", answer: "Vrai", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf-hist12", type: "true_false", theme: "Histoire", question: "Cléopâtre était d’origine égyptienne.", answer: "Faux", options: ["Vrai", "Faux"], points: 150 },
  { id: "tf-hist13", type: "true_false", theme: "Histoire", question: "L’Empire romain d’Orient est tombé avant celui d’Occident.", answer: "Faux", options: ["Vrai", "Faux"], points: 160 },
  { id: "tf-hist14", type: "true_false", theme: "Histoire", question: "Christophe Colomb pensait avoir atteint l’Asie en arrivant en Amérique.", answer: "Vrai", options: ["Vrai", "Faux"], points: 100 },
  { id: "tf-hist15", type: "true_false", theme: "Histoire", question: "La Première Guerre mondiale a commencé en 1914.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-hist16", type: "true_false", theme: "Histoire", question: "Hitler a été élu démocratiquement chancelier d’Allemagne.", answer: "Vrai", options: ["Vrai", "Faux"], points: 140 },
  { id: "tf-hist17", type: "true_false", theme: "Histoire", question: "La Bastille était une prison politique importante lors de sa prise.", answer: "Faux", options: ["Vrai", "Faux"], points: 170 },
  { id: "tf-hist18", type: "true_false", theme: "Histoire", question: "Louis XVI a été guillotiné avant Marie-Antoinette.", answer: "Vrai", options: ["Vrai", "Faux"], points: 130 },
  { id: "tf-hist19", type: "true_false", theme: "Histoire", question: "La guerre froide a opposé directement les États-Unis et l’URSS sur le champ de bataille.", answer: "Faux", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-hist20", type: "true_false", theme: "Histoire", question: "Le mur de Berlin a été construit en 1961.", answer: "Vrai", options: ["Vrai", "Faux"], points: 110 },
  { id: "tf-hist21", type: "true_false", theme: "Histoire", question: "Les Vikings portaient des casques à cornes.", answer: "Faux", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-hist22", type: "true_false", theme: "Histoire", question: "Jules César a été assassiné par plusieurs sénateurs.", answer: "Vrai", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf-hist23", type: "true_false", theme: "Histoire", question: "Alexandre le Grand n’a jamais perdu une bataille.", answer: "Vrai", options: ["Vrai", "Faux"], points: 150 },
  { id: "tf-hist24", type: "true_false", theme: "Histoire", question: "La Renaissance a débuté en Italie.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-hist25", type: "true_false", theme: "Histoire", question: "L’imprimerie a été inventée par Gutenberg au XVe siècle.", answer: "Vrai", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-hist26", type: "true_false", theme: "Histoire", question: "Le Code Napoléon a influencé de nombreux systèmes juridiques dans le monde.", answer: "Vrai", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf-hist27", type: "true_false", theme: "Histoire", question: "La Chine a construit la Grande Muraille en une seule fois.", answer: "Faux", options: ["Vrai", "Faux"], points: 110 },
  { id: "tf-hist28", type: "true_false", theme: "Histoire", question: "La guerre de Sécession a opposé le nord et le sud des États-Unis.", answer: "Vrai", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf-hist29", type: "true_false", theme: "Histoire", question: "Le Titanic a coulé lors de son premier voyage.", answer: "Vrai", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf-hist30", type: "true_false", theme: "Histoire", question: "Le Japon a été le premier pays à utiliser l’arme nucléaire en guerre.", answer: "Faux", options: ["Vrai", "Faux"], points: 130 },

  // --- CULTURE G ---
  { id: "tf17", type: "true_false", theme: "Culture G", question: "Walt Disney detient le record du plus grand nombre d'Oscars remportés.", answer: "Vrai", options: ["Vrai", "Faux"], points: 100 },
  { id: "tf18", type: "true_false", theme: "Culture G", question: "L'inventeur de la machine à barbe à papa était un dentiste.", answer: "Vrai", options: ["Vrai", "Faux"], points: 170 },
  { id: "tf61", type: "true_false", theme: "Culture G", question: "Le roman 'Les Misérables' a été écrit par Victor Hugo.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf62", type: "true_false", theme: "Culture G", question: "La Joconde se trouve au musée du Louvre.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf63", type: "true_false", theme: "Culture G", question: "Le symbole chimique de l’or est Ag.", answer: "Faux", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf64", type: "true_false", theme: "Culture G", question: "Le football a été inventé au Brésil.", answer: "Faux", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf65", type: "true_false", theme: "Culture G", question: "Le drapeau français est composé de trois bandes verticales.", answer: "Vrai", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf66", type: "true_false", theme: "Culture G", question: "La bande dessinée 'Tintin' est d’origine belge.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf67", type: "true_false", theme: "Culture G", question: "Le jeu vidéo 'Minecraft' est sorti en 2009.", answer: "Faux", options: ["Vrai", "Faux"], points: 130 },
  { id: "tf68", type: "true_false", theme: "Culture G", question: "Le Mont Everest est situé dans l’Himalaya.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-cg11", type: "true_false", theme: "Culture G", question: "Le symbole chimique du sodium est Na.", answer: "Vrai", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-cg12", type: "true_false", theme: "Culture G", question: "Un octogone possède 10 côtés.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf-cg13", type: "true_false", theme: "Culture G", question: "La planète Mars est plus grande que la Terre.", answer: "Faux", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf-cg14", type: "true_false", theme: "Culture G", question: "Le plus grand océan du monde est l’océan Pacifique.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-cg15", type: "true_false", theme: "Culture G", question: "Un palindrome est un mot qui se lit de la même manière dans les deux sens.", answer: "Vrai", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf-cg16", type: "true_false", theme: "Culture G", question: "La vitesse du son est plus rapide que celle de la lumière.", answer: "Faux", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-cg17", type: "true_false", theme: "Culture G", question: "Il existe plus de galaxies que d’étoiles dans l’univers.", answer: "Faux", options: ["Vrai", "Faux"], points: 160 },
  { id: "tf-cg18", type: "true_false", theme: "Culture G", question: "Le cerveau humain consomme environ 20% de l’énergie du corps.", answer: "Vrai", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf-cg19", type: "true_false", theme: "Culture G", question: "Un kilomètre carré équivaut à 1 000 000 de mètres carrés.", answer: "Vrai", options: ["Vrai", "Faux"], points: 110 },
  { id: "tf-cg20", type: "true_false", theme: "Culture G", question: "La lettre 'J' n’apparaît pas dans le tableau périodique des éléments.", answer: "Vrai", options: ["Vrai", "Faux"], points: 190 },
  { id: "tf-cg21", type: "true_false", theme: "Culture G", question: "La langue la plus parlée au monde est l’anglais.", answer: "Faux", options: ["Vrai", "Faux"], points: 110 },
  { id: "tf-cg22", type: "true_false", theme: "Culture G", question: "Les requins existent depuis avant les arbres.", answer: "Vrai", options: ["Vrai", "Faux"], points: 200 },
  { id: "tf-cg23", type: "true_false", theme: "Culture G", question: "Un nuage peut peser plusieurs tonnes.", answer: "Vrai", options: ["Vrai", "Faux"], points: 150 },
  { id: "tf-cg24", type: "true_false", theme: "Culture G", question: "Le Mont Everest grandit encore chaque année.", answer: "Vrai", options: ["Vrai", "Faux"], points: 140 },
  { id: "tf-cg25", type: "true_false", theme: "Culture G", question: "Les humains partagent plus de 90% de leur ADN avec les chats.", answer: "Vrai", options: ["Vrai", "Faux"], points: 180 },
  { id: "tf-cg26", type: "true_false", theme: "Culture G", question: "Le mot 'OK' vient de l’anglais 'All Correct'.", answer: "Faux", options: ["Vrai", "Faux"], points: 190 },
  { id: "tf-cg27", type: "true_false", theme: "Culture G", question: "Il est possible de plier une feuille de papier plus de 7 fois.", answer: "Vrai", options: ["Vrai", "Faux"], points: 160 },
  { id: "tf-cg28", type: "true_false", theme: "Culture G", question: "La Terre est parfaitement ronde.", answer: "Faux", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-cg29", type: "true_false", theme: "Culture G", question: "Le miel est le seul aliment qui ne se périme jamais.", answer: "Vrai", options: ["Vrai", "Faux"], points: 100 },
  { id: "tf-cg30", type: "true_false", theme: "Culture G", question: "Un humain peut survivre plus longtemps sans manger que sans dormir.", answer: "Vrai", options: ["Vrai", "Faux"], points: 150 },

  // --- SPORT ---
  { id: "tf-sp1", type: "true_false", theme: "Sport", question: "Le tennis de table est un sport olympique.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-sp2", type: "true_false", theme: "Sport", question: "Au tennis, le point qui vient après 30 est 45.", answer: "Faux", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf-sp3", type: "true_false", theme: "Sport", question: "Un match de rugby à XV dure 80 minutes.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-sp4", type: "true_false", theme: "Sport", question: "Usain Bolt détient le record du monde du 100m.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-sp5", type: "true_false", theme: "Sport", question: "Au basket-ball, un tir réussi de très loin vaut 4 points.", answer: "Faux", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-sp6", type: "true_false", theme: "Sport", question: "Le Tour de France est la compétition cycliste la plus suivie au monde.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-sp7", type: "true_false", theme: "Sport", question: "Une partie de bowling se compose de 15 manches (frames).", answer: "Faux", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-sp8", type: "true_false", theme: "Sport", question: "La ceinture noire est la ceinture la plus élevée que l'on puisse atteindre au judo.", answer: "Faux", options: ["Vrai", "Faux"], points: 130 },
  { id: "tf-sp11", type: "true_false", theme: "Sport", question: "Au football, un gardien peut marquer un but sans que personne ne touche le ballon après son dégagement.", answer: "Vrai", options: ["Vrai", "Faux"], points: 140 },
  { id: "tf-sp12", type: "true_false", theme: "Sport", question: "En NBA, un joueur peut revenir sur le terrain après avoir fait 6 fautes personnelles.", answer: "Faux", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf-sp13", type: "true_false", theme: "Sport", question: "Au tennis, un tie-break se joue toujours en 7 points gagnants.", answer: "Faux", options: ["Vrai", "Faux"], points: 160 },
  { id: "tf-sp14", type: "true_false", theme: "Sport", question: "En Formule 1, un pilote peut changer de pneus sans obligation de changer de type de gomme.", answer: "Faux", options: ["Vrai", "Faux"], points: 150 },
  { id: "tf-sp15", type: "true_false", theme: "Sport", question: "Au rugby, un essai vaut 5 points.", answer: "Vrai", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf-sp16", type: "true_false", theme: "Sport", question: "Au basket, un lancer franc vaut 2 points.", answer: "Faux", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf-sp17", type: "true_false", theme: "Sport", question: "En football, un match peut se terminer sans aucun tir cadré.", answer: "Vrai", options: ["Vrai", "Faux"], points: 110 },
  { id: "tf-sp18", type: "true_false", theme: "Sport", question: "Au handball, un joueur peut rester plus de 3 secondes sans dribbler.", answer: "Faux", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf-sp19", type: "true_false", theme: "Sport", question: "En boxe professionnelle, un combat peut durer 15 rounds.", answer: "Faux", options: ["Vrai", "Faux"], points: 140 },
  { id: "tf-sp20", type: "true_false", theme: "Sport", question: "Au golf, le terme 'birdie' signifie un coup au-dessus du par.", answer: "Faux", options: ["Vrai", "Faux"], points: 100 },
  { id: "tf-sp21", type: "true_false", theme: "Sport", question: "En volley-ball, un joueur peut toucher deux fois de suite le ballon.", answer: "Faux", options: ["Vrai", "Faux"], points: 110 },
  { id: "tf-sp22", type: "true_false", theme: "Sport", question: "Au football, un carton jaune entraîne toujours une expulsion.", answer: "Faux", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-sp23", type: "true_false", theme: "Sport", question: "En tennis, il est possible de gagner un match sans gagner un seul point.", answer: "Vrai", options: ["Vrai", "Faux"], points: 250 },
  { id: "tf-sp24", type: "true_false", theme: "Sport", question: "Au rugby, une transformation vaut 2 points.", answer: "Vrai", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf-sp25", type: "true_false", theme: "Sport", question: "En Formule 1, tous les circuits se courent dans le sens des aiguilles d'une montre.", answer: "Faux", options: ["Vrai", "Faux"], points: 150 },
  { id: "tf-sp26", type: "true_false", theme: "Sport", question: "Au basket, un joueur peut rester indéfiniment dans la raquette en défense.", answer: "Vrai", options: ["Vrai", "Faux"], points: 160 },
  { id: "tf-sp27", type: "true_false", theme: "Sport", question: "Au football, un joueur peut être hors-jeu sur une touche.", answer: "Faux", options: ["Vrai", "Faux"], points: 140 },
  { id: "tf-sp28", type: "true_false", theme: "Sport", question: "En MMA, il est interdit de donner des coups de tête.", answer: "Vrai", options: ["Vrai", "Faux"], points: 100 },
  { id: "tf-sp29", type: "true_false", theme: "Sport", question: "Au tennis, la balle peut toucher le filet au service et être valide.", answer: "Vrai", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf-sp30", type: "true_false", theme: "Sport", question: "En football, un penalty peut être tiré en arrière.", answer: "Faux", options: ["Vrai", "Faux"], points: 190 },

  // --- DESSIN ANIMÉ / MANGA ---
  { id: "tf-da1", type: "true_false", theme: "Dessin animé", question: "Pikachu est un Pokémon de type Électrik.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-da2", type: "true_false", theme: "Dessin animé", question: "Dans 'Toy Story', le dinosaure vert s'appelle Woody.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf-da3", type: "true_false", theme: "Dessin animé", question: "Homer Simpson travaille dans une centrale nucléaire.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-da4", type: "true_false", theme: "Dessin animé", question: "Mickey Mouse devait initialement s'appeler Mortimer.", answer: "Vrai", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf-da5", type: "true_false", theme: "Dessin animé", question: "Dans 'La Reine des Neiges', le bonhomme de neige s'appelle Sven.", answer: "Faux", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf-da6", type: "true_false", theme: "Dessin animé", question: "Shrek est un ogre de couleur bleue.", answer: "Faux", options: ["Vrai", "Faux"], points: 50 },
  { id: "tf-da7", type: "true_false", theme: "Dessin animé", question: "Bob l'éponge travaille au Crabe Croustillant.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-da11", type: "true_false", theme: "Dessin animé", question: "Dans 'Le Roi Lion', Scar est le frère biologique de Mufasa.", answer: "Faux", options: ["Vrai", "Faux"], points: 130 },
  { id: "tf-da12", type: "true_false", theme: "Dessin animé", question: "Dans 'Avatar : Le dernier maître de l’air', Aang est le seul maître de l’air encore en vie au début de la série.", answer: "Vrai", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-da13", type: "true_false", theme: "Dessin animé", question: "Dans 'Naruto', Kakashi possède le Sharingan dès sa naissance.", answer: "Faux", options: ["Vrai", "Faux"], points: 100 },
  { id: "tf-da14", type: "true_false", theme: "Dessin animé", question: "Dans 'Dragon Ball Z', Vegeta n’a jamais vaincu Goku en combat officiel.", answer: "Vrai", options: ["Vrai", "Faux"], points: 150 },
  { id: "tf-da15", type: "true_false", theme: "Dessin animé", question: "Dans 'One Piece', Luffy a mangé le fruit du démon du feu.", answer: "Faux", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-da16", type: "true_false", theme: "Dessin animé", question: "Dans 'Les Simpsons', Bart a déjà obtenu un A à un examen.", answer: "Vrai", options: ["Vrai", "Faux"], points: 140 },
  { id: "tf-da17", type: "true_false", theme: "Dessin animé", question: "Dans 'Rick et Morty', Rick est la personne la plus intelligente de tous les univers.", answer: "Faux", options: ["Vrai", "Faux"], points: 180 },
  { id: "tf-da18", type: "true_false", theme: "Dessin animé", question: "Dans 'Death Note', Light Yagami meurt à la fin de l’histoire.", answer: "Vrai", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf-da19", type: "true_false", theme: "Dessin animé", question: "Dans 'Fullmetal Alchemist', Edward Elric perd son bras et sa jambe.", answer: "Vrai", options: ["Vrai", "Faux"], points: 100 },
  { id: "tf-da20", type: "true_false", theme: "Dessin animé", question: "Dans 'Attack on Titan', Eren possède le pouvoir de plusieurs Titans.", answer: "Vrai", options: ["Vrai", "Faux"], points: 130 },
  { id: "tf-da21", type: "true_false", theme: "Dessin animé", question: "Dans 'Toy Story', Buzz l’Éclair croit être un vrai ranger de l’espace au début.", answer: "Vrai", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-da22", type: "true_false", theme: "Dessin animé", question: "Dans 'Shrek', Fiona est une princesse humaine tout au long de la saga.", answer: "Faux", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf-da23", type: "true_false", theme: "Dessin animé", question: "Dans 'Les Indestructibles', Violet peut devenir invisible et créer des champs de force.", answer: "Vrai", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-da24", type: "true_false", theme: "Dessin animé", question: "Dans 'Gravity Falls', Dipper et Mabel sont jumeaux.", answer: "Vrai", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf-da25", type: "true_false", theme: "Dessin animé", question: "Dans 'Adventure Time', Finn est le seul humain encore en vie.", answer: "Faux", options: ["Vrai", "Faux"], points: 130 },
  { id: "tf-da26", type: "true_false", theme: "Dessin animé", question: "Dans 'Pokémon', Sacha gagne finalement la Ligue Pokémon dans la série principale.", answer: "Vrai", options: ["Vrai", "Faux"], points: 130 },
  { id: "tf-da27", type: "true_false", theme: "Dessin animé", question: "Dans 'Demon Slayer', Tanjiro devient un démon à un moment de l’histoire.", answer: "Vrai", options: ["Vrai", "Faux"], points: 190 },
  { id: "tf-da28", type: "true_false", theme: "Dessin animé", question: "Dans 'Spider-Man: Into the Spider-Verse', Miles Morales est le premier Spider-Man.", answer: "Faux", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-da29", type: "true_false", theme: "Dessin animé", question: "Dans 'Arcane', Jinx et Vi sont sœurs.", answer: "Vrai", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf-da30", type: "true_false", theme: "Dessin animé", question: "Dans 'Les Simpsons', Maggie a déjà tiré avec une arme à feu.", answer: "Vrai", options: ["Vrai", "Faux"], points: 150 },

  // --- MYTHOLOGIE ---
  { id: "tf-my1", type: "true_false", theme: "Mythologie", question: "Zeus est le dieu des mers.", answer: "Faux", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-my2", type: "true_false", theme: "Mythologie", question: "Thor est un dieu de la mythologie nordique.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-my3", type: "true_false", theme: "Mythologie", question: "Hercule a accompli 10 travaux.", answer: "Faux", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-my4", type: "true_false", theme: "Mythologie", question: "Hadès est le dieu des Enfers.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-my5", type: "true_false", theme: "Mythologie", question: "Le Minotaure vit dans un labyrinthe.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-my6", type: "true_false", theme: "Mythologie", question: "Athéna est la déesse de la guerre et de la sagesse.", answer: "Vrai", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf-my7", type: "true_false", theme: "Mythologie", question: "Loki est un dieu grec.", answer: "Faux", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-my8", type: "true_false", theme: "Mythologie", question: "Cerbère possède trois têtes.", answer: "Vrai", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf-my9", type: "true_false", theme: "Mythologie", question: "Apollon est le dieu du soleil.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-my10", type: "true_false", theme: "Mythologie", question: "Odin est le fils de Zeus.", answer: "Faux", options: ["Vrai", "Faux"], points: 110 },
  { id: "tf-my11", type: "true_false", theme: "Mythologie", question: "Zeus est le frère de Poséidon.", answer: "Vrai", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-my12", type: "true_false", theme: "Mythologie", question: "Hadès vit sur l’Olympe.", answer: "Faux", options: ["Vrai", "Faux"], points: 100 },
  { id: "tf-my13", type: "true_false", theme: "Mythologie", question: "Thor est le fils d’Odin.", answer: "Vrai", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf-my14", type: "true_false", theme: "Mythologie", question: "Les sirènes attirent les marins avec leur chant.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-my15", type: "true_false", theme: "Mythologie", question: "Prométhée a volé l’eau aux dieux.", answer: "Faux", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf-my16", type: "true_false", theme: "Mythologie", question: "Anubis est un dieu égyptien.", answer: "Vrai", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf-my17", type: "true_false", theme: "Mythologie", question: "Achille était invulnérable partout.", answer: "Faux", options: ["Vrai", "Faux"], points: 100 },
  { id: "tf-my18", type: "true_false", theme: "Mythologie", question: "Odin possède deux corbeaux.", answer: "Vrai", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf-my19", type: "true_false", theme: "Mythologie", question: "Cerbère garde l’entrée des Enfers.", answer: "Vrai", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf-my20", type: "true_false", theme: "Mythologie", question: "Le Ragnarök est une fête des dieux.", answer: "Faux", options: ["Vrai", "Faux"], points: 110 },

  // --- MUSIQUE ---
  { id: "tf-mu1", type: "true_false", theme: "Musique", question: "Ludwig van Beethoven était complètement sourd à la fin de sa vie.", answer: "Vrai", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-mu2", type: "true_false", theme: "Musique", question: "Le groupe 'The Beatles' comptait 5 membres officiels.", answer: "Faux", options: ["Vrai", "Faux"], points: 70 },
  { id: "tf-mu3", type: "true_false", theme: "Musique", question: "Le saxophone a été inventé par un homme nommé Adolphe Sax.", answer: "Vrai", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-mu4", type: "true_false", theme: "Musique", question: "Une guitare électrique standard possède généralement 6 cordes.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-mu5", type: "true_false", theme: "Musique", question: "Michael Jackson était surnommé le 'King of Rock'.", answer: "Faux", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf-mu6", type: "true_false", theme: "Musique", question: "Le violon est l'instrument le plus grave de la famille des cordes frottées.", answer: "Faux", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-mu7", type: "true_false", theme: "Musique", question: "Bob Marley était de nationalité jamaïcaine.", answer: "Vrai", options: ["Vrai", "Faux"], points: 60 },
  { id: "tf-mu8", type: "true_false", theme: "Musique", question: "Justin Bieber a été découvert grâce à des vidéos sur YouTube.", answer: "Vrai", options: ["Vrai", "Faux"], points: 80 },
  { id: "tf-mu9", type: "true_false", theme: "Musique", question: "Le piano possède exactement 88 touches.", answer: "Vrai", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf-mu10", type: "true_false", theme: "Musique", question: "La chanson 'My Way' de Frank Sinatra est à l'origine une chanson française.", answer: "Vrai", options: ["Vrai", "Faux"], points: 140 },
  { id: "tf-mu11", type: "true_false", theme: "Musique", question: "Elvis Presley a écrit la quasi-totalité de ses tubes.", answer: "Faux", options: ["Vrai", "Faux"], points: 130 },
  { id: "tf-mu12", type: "true_false", theme: "Musique", question: "Daft Punk a annoncé sa séparation officielle en 2021.", answer: "Vrai", options: ["Vrai", "Faux"], points: 110 },
  { id: "tf-mu13", type: "true_false", theme: "Musique", question: "Frédéric Chopin était de nationalité française de naissance.", answer: "Faux", options: ["Vrai", "Faux"], points: 130 },
  { id: "tf-mu14", type: "true_false", theme: "Musique", question: "AC/DC est un groupe de rock originaire des États-Unis.", answer: "Faux", options: ["Vrai", "Faux"], points: 100 },
  { id: "tf-mu15", type: "true_false", theme: "Musique", question: "Le métronome sert à mesurer l'intensité sonore d'un morceau.", answer: "Faux", options: ["Vrai", "Faux"], points: 110 },
  { id: "tf-mu16", type: "true_false", theme: "Musique", question: "Une noire vaut deux temps dans une mesure en 4/4.", answer: "Faux", options: ["Vrai", "Faux"], points: 110 },
  { id: "tf-mu17", type: "true_false", theme: "Musique", question: "Le nom du groupe ABBA est formé par les initiales des prénoms de ses membres.", answer: "Vrai", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf-mu18", type: "true_false", theme: "Musique", question: "Les cordes d'un violon sont : Sol, Ré, La, Mi.", answer: "Vrai", options: ["Vrai", "Faux"], points: 130 },
  { id: "tf-mu19", type: "true_false", theme: "Musique", question: "Madonna est née et a grandi en Italie.", answer: "Faux", options: ["Vrai", "Faux"], points: 110 },
  { id: "tf-mu20", type: "true_false", theme: "Musique", question: "Mozart a composé sa première œuvre à l'âge de 5 ans.", answer: "Vrai", options: ["Vrai", "Faux"], points: 130 },
  { id: "tf-mu21", type: "true_false", theme: "Musique", question: "Johann Sebastian Bach a eu un total de 20 enfants.", answer: "Vrai", options: ["Vrai", "Faux"], points: 180 },
  { id: "tf-mu22", type: "true_false", theme: "Musique", question: "Le premier disque compact (CD) commercialisé au monde était un album de Michael Jackson.", answer: "Faux", options: ["Vrai", "Faux"], points: 190 },
  { id: "tf-mu23", type: "true_false", theme: "Musique", question: "Jimi Hendrix jouait sur une guitare pour droitier alors qu'il était gaucher.", answer: "Vrai", options: ["Vrai", "Faux"], points: 160 },
  { id: "tf-mu24", type: "true_false", theme: "Musique", question: "Antonio Vivaldi était surnommé 'Le Prêtre Roux'.", answer: "Vrai", options: ["Vrai", "Faux"], points: 150 },
  { id: "tf-mu25", type: "true_false", theme: "Musique", question: "Un piano de concert contient plus de 10 000 pièces mobiles.", answer: "Vrai", options: ["Vrai", "Faux"], points: 200 },
  { id: "tf-mu26", type: "true_false", theme: "Musique", question: "Le chanteur de Queen, Freddie Mercury, est né à Londres.", answer: "Faux", options: ["Vrai", "Faux"], points: 150 },
  { id: "tf-mu27", type: "true_false", theme: "Musique", question: "La plateforme Spotify a été créée en Suède.", answer: "Vrai", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf-mu28", type: "true_false", theme: "Musique", question: "Le terme 'A cappella' signifie littéralement 'Comme à la chapelle'.", answer: "Vrai", options: ["Vrai", "Faux"], points: 140 },
  { id: "tf-mu29", type: "true_false", theme: "Musique", question: "L'hymne national des Pays-Bas est le plus vieux du monde.", answer: "Vrai", options: ["Vrai", "Faux"], points: 190 },
  { id: "tf-mu30", type: "true_false", theme: "Musique", question: "Le groupe Pink Floyd tire son nom de deux musiciens de blues : Pink Anderson et Floyd Council.", answer: "Vrai", options: ["Vrai", "Faux"], points: 180 },
  { id: "tf-mu31", type: "true_false", theme: "Musique", question: "Une contrebasse est plus petite qu'un violoncelle.", answer: "Faux", options: ["Vrai", "Faux"], points: 90 },
  { id: "tf-mu32", type: "true_false", theme: "Musique", question: "Le Thérémine est le seul instrument dont on joue sans contact physique.", answer: "Vrai", options: ["Vrai", "Faux"], points: 140 },
  { id: "tf-mu33", type: "true_false", theme: "Musique", question: "Les Rolling Stones ont sorti leur premier album avant les Beatles.", answer: "Faux", options: ["Vrai", "Faux"], points: 150 },
  { id: "tf-mu34", type: "true_false", theme: "Musique", question: "Le clavecin possède des cordes frappées comme le piano.", answer: "Faux", options: ["Vrai", "Faux"], points: 160 },
  { id: "tf-mu35", type: "true_false", theme: "Musique", question: "La fréquence du 'La' de référence est de 440 Hz.", answer: "Vrai", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf-mu36", type: "true_false", theme: "Musique", question: "Eminem a remporté un Oscar pour la meilleure chanson originale.", answer: "Vrai", options: ["Vrai", "Faux"], points: 130 },
  { id: "tf-mu37", type: "true_false", theme: "Musique", question: "La flûte traversière fait partie de la famille des bois.", answer: "Vrai", options: ["Vrai", "Faux"], points: 140 },
  { id: "tf-mu38", type: "true_false", theme: "Musique", question: "Pavarotti était un célèbre baryton.", answer: "Faux", options: ["Vrai", "Faux"], points: 120 },
  { id: "tf-mu39", type: "true_false", theme: "Musique", question: "Une symphonie classique comporte généralement 4 mouvements.", answer: "Vrai", options: ["Vrai", "Faux"], points: 110 },
  { id: "tf-mu40", type: "true_false", theme: "Musique", question: "Le ukulélé est originaire d'Hawaii, mais a été inspiré par des instruments portugais.", answer: "Vrai", options: ["Vrai", "Faux"], points: 160 }
];