/**
 * Données pour questions géo (drapeaux / silhouettes).
 * `code` = ISO 3166-1 alpha-2 (flagcdn + mapsicon `all/{code}/128.png`).
 */
export type GeoRow = {
  code: string;
  answer: string;
  aliases?: string[];
};

/** ~100 drapeaux — noms en français */
export const GEO_FLAG_ROWS: GeoRow[] = [
  { code: "fr", answer: "France" },
  { code: "de", answer: "Allemagne" },
  { code: "it", answer: "Italie" },
  { code: "es", answer: "Espagne" },
  { code: "pt", answer: "Portugal" },
  { code: "nl", answer: "Pays-Bas" },
  { code: "be", answer: "Belgique" },
  { code: "ch", answer: "Suisse" },
  { code: "at", answer: "Autriche" },
  { code: "se", answer: "Suède" },
  { code: "no", answer: "Norvège" },
  { code: "dk", answer: "Danemark" },
  { code: "fi", answer: "Finlande" },
  { code: "pl", answer: "Pologne" },
  { code: "cz", answer: "Tchéquie", aliases: ["République tchèque", "Republique tcheque"] },
  { code: "hu", answer: "Hongrie" },
  { code: "ro", answer: "Roumanie" },
  { code: "ie", answer: "Irlande" },
  { code: "is", answer: "Islande" },
  { code: "hr", answer: "Croatie" },
  { code: "sk", answer: "Slovaquie" },
  { code: "si", answer: "Slovénie" },
  { code: "bg", answer: "Bulgarie" },
  { code: "lt", answer: "Lituanie" },
  { code: "lv", answer: "Lettonie" },
  { code: "ee", answer: "Estonie" },
  { code: "lu", answer: "Luxembourg" },
  { code: "mt", answer: "Malte" },
  { code: "cy", answer: "Chypre" },
  { code: "gr", answer: "Grèce" },
  { code: "gb", answer: "Royaume-Uni", aliases: ["UK", "Angleterre", "Grande-Bretagne"] },
  { code: "ua", answer: "Ukraine" },
  { code: "md", answer: "Moldavie" },
  { code: "al", answer: "Albanie" },
  { code: "mk", answer: "Macédoine du Nord", aliases: ["Macedoine du Nord", "Macédoine"] },
  { code: "ba", answer: "Bosnie-Herzégovine", aliases: ["Bosnie"] },
  { code: "rs", answer: "Serbie" },
  { code: "me", answer: "Monténégro", aliases: ["Montenegro"] },
  { code: "ad", answer: "Andorre" },
  { code: "mc", answer: "Monaco" },
  { code: "sm", answer: "Saint-Marin" },
  { code: "va", answer: "Vatican" },
  { code: "li", answer: "Liechtenstein" },
  { code: "us", answer: "États-Unis", aliases: ["USA", "Etats-Unis", "United States"] },
  { code: "ca", answer: "Canada" },
  { code: "mx", answer: "Mexique" },
  { code: "br", answer: "Brésil" },
  { code: "ar", answer: "Argentine" },
  { code: "cl", answer: "Chili" },
  { code: "co", answer: "Colombie" },
  { code: "pe", answer: "Pérou", aliases: ["Perou"] },
  { code: "ve", answer: "Venezuela" },
  { code: "ec", answer: "Équateur", aliases: ["Equateur"] },
  { code: "uy", answer: "Uruguay" },
  { code: "py", answer: "Paraguay" },
  { code: "bo", answer: "Bolivie" },
  { code: "cr", answer: "Costa Rica" },
  { code: "pa", answer: "Panama" },
  { code: "cu", answer: "Cuba" },
  { code: "jm", answer: "Jamaïque", aliases: ["Jamaique"] },
  { code: "ht", answer: "Haïti", aliases: ["Haiti"] },
  { code: "do", answer: "République dominicaine", aliases: ["Rep. dominicaine", "Dominicaine"] },
  { code: "gt", answer: "Guatemala" },
  { code: "hn", answer: "Honduras" },
  { code: "ni", answer: "Nicaragua" },
  { code: "sv", answer: "Salvador" },
  { code: "tt", answer: "Trinité-et-Tobago", aliases: ["Trinite-et-Tobago"] },
  { code: "gy", answer: "Guyana" },
  { code: "sr", answer: "Suriname" },
  { code: "eg", answer: "Égypte", aliases: ["Egypte"] },
  { code: "ma", answer: "Maroc" },
  { code: "dz", answer: "Algérie", aliases: ["Algerie"] },
  { code: "tn", answer: "Tunisie" },
  { code: "ly", answer: "Libye" },
  { code: "za", answer: "Afrique du Sud" },
  { code: "ng", answer: "Nigeria" },
  { code: "ke", answer: "Kenya" },
  { code: "et", answer: "Éthiopie", aliases: ["Ethiopie"] },
  { code: "gh", answer: "Ghana" },
  { code: "sn", answer: "Sénégal", aliases: ["Senegal"] },
  { code: "ci", answer: "Côte d'Ivoire", aliases: ["Cote d'Ivoire", "Ivory Coast"] },
  { code: "cm", answer: "Cameroun" },
  { code: "ao", answer: "Angola" },
  { code: "mz", answer: "Mozambique" },
  { code: "ug", answer: "Ouganda" },
  { code: "tz", answer: "Tanzanie" },
  { code: "rw", answer: "Rwanda" },
  { code: "mg", answer: "Madagascar" },
  { code: "na", answer: "Namibie" },
  { code: "bw", answer: "Botswana" },
  { code: "zw", answer: "Zimbabwe" },
  { code: "zm", answer: "Zambie" },
  { code: "cd", answer: "RD Congo", aliases: ["RDC", "Congo-Kinshasa", "République démocratique du Congo"] },
  { code: "cg", answer: "Congo", aliases: ["Congo-Brazzaville", "République du Congo"] },
  { code: "jp", answer: "Japon" },
  { code: "cn", answer: "Chine" },
  { code: "kr", answer: "Corée du Sud", aliases: ["Coree du Sud", "Corée"] },
  { code: "kp", answer: "Corée du Nord", aliases: ["Coree du Nord"] },
  { code: "tw", answer: "Taïwan", aliases: ["Taiwan"] },
  { code: "in", answer: "Inde" },
  { code: "th", answer: "Thaïlande", aliases: ["Thailande"] },
  { code: "vn", answer: "Vietnam" },
  { code: "id", answer: "Indonésie", aliases: ["Indonesie"] },
  { code: "my", answer: "Malaisie" },
  { code: "sg", answer: "Singapour" },
  { code: "ph", answer: "Philippines" },
  { code: "bd", answer: "Bangladesh" },
  { code: "pk", answer: "Pakistan" },
  { code: "lk", answer: "Sri Lanka" },
  { code: "np", answer: "Népal", aliases: ["Nepal"] },
  { code: "mm", answer: "Myanmar", aliases: ["Birmanie"] },
  { code: "kh", answer: "Cambodge" },
  { code: "la", answer: "Laos" },
  { code: "bn", answer: "Brunei" },
  { code: "mn", answer: "Mongolie" },
  { code: "kz", answer: "Kazakhstan" },
  { code: "uz", answer: "Ouzbékistan", aliases: ["Ouzbekistan"] },
  { code: "ge", answer: "Géorgie", aliases: ["Georgie"] },
  { code: "am", answer: "Arménie", aliases: ["Armenie"] },
  { code: "az", answer: "Azerbaïdjan", aliases: ["Azerbaidjan"] },
  { code: "ir", answer: "Iran" },
  { code: "iq", answer: "Irak" },
  { code: "sa", answer: "Arabie saoudite", aliases: ["Arabie Saoudite"] },
  { code: "ae", answer: "Émirats arabes unis", aliases: ["Emirats arabes unis", "EAU", "Dubaï", "Dubai"] },
  { code: "il", answer: "Israël", aliases: ["Israel"] },
  { code: "jo", answer: "Jordanie" },
  { code: "lb", answer: "Liban" },
  { code: "sy", answer: "Syrie" },
  { code: "ye", answer: "Yémen", aliases: ["Yemen"] },
  { code: "om", answer: "Oman" },
  { code: "qa", answer: "Qatar" },
  { code: "kw", answer: "Koweït", aliases: ["Koweit"] },
  { code: "bh", answer: "Bahreïn", aliases: ["Bahrein"] },
  { code: "au", answer: "Australie" },
  { code: "nz", answer: "Nouvelle-Zélande", aliases: ["Nouvelle-Zelande"] },
  { code: "fj", answer: "Fidji", aliases: ["Fiji"] },
  { code: "pg", answer: "Papouasie-Nouvelle-Guinée", aliases: ["Papouasie-Nouvelle-Guinee"] },
];

/** Silhouettes — pays reconnaissables (mapsicon) */
export const GEO_SHAPE_ROWS: GeoRow[] = [
  { code: "fr", answer: "France" },
  { code: "it", answer: "Italie" },
  { code: "es", answer: "Espagne" },
  { code: "de", answer: "Allemagne" },
  { code: "gr", answer: "Grèce" },
  { code: "no", answer: "Norvège", aliases: ["Norvege"] },
  { code: "jp", answer: "Japon" },
  { code: "cl", answer: "Chili" },
  { code: "vn", answer: "Vietnam" },
  { code: "hr", answer: "Croatie" },
  { code: "is", answer: "Islande" },
  { code: "mg", answer: "Madagascar" },
  { code: "us", answer: "États-Unis", aliases: ["USA", "Etats-Unis"] },
  { code: "br", answer: "Brésil" },
  { code: "au", answer: "Australie" },
  { code: "in", answer: "Inde" },
  { code: "mx", answer: "Mexique" },
  { code: "za", answer: "Afrique du Sud" },
  { code: "eg", answer: "Égypte", aliases: ["Egypte"] },
  { code: "tr", answer: "Turquie" },
  { code: "id", answer: "Indonésie", aliases: ["Indonesie"] },
  { code: "th", answer: "Thaïlande", aliases: ["Thailande"] },
  { code: "my", answer: "Malaisie" },
  { code: "ph", answer: "Philippines" },
  { code: "ar", answer: "Argentine" },
  { code: "co", answer: "Colombie" },
  { code: "pe", answer: "Pérou", aliases: ["Perou"] },
  { code: "ng", answer: "Nigeria" },
  { code: "ke", answer: "Kenya" },
  { code: "ma", answer: "Maroc" },
  { code: "dz", answer: "Algérie", aliases: ["Algerie"] },
  { code: "tn", answer: "Tunisie" },
  { code: "fi", answer: "Finlande" },
  { code: "se", answer: "Suède", aliases: ["Suede"] },
  { code: "pl", answer: "Pologne" },
  { code: "ua", answer: "Ukraine" },
  { code: "gb", answer: "Royaume-Uni", aliases: ["UK"] },
  { code: "ca", answer: "Canada" },
  { code: "cn", answer: "Chine" },
  { code: "kr", answer: "Corée du Sud", aliases: ["Coree du Sud"] },
  { code: "pt", answer: "Portugal" },
  { code: "nl", answer: "Pays-Bas" },
  { code: "be", answer: "Belgique" },
  { code: "ch", answer: "Suisse" },
  { code: "at", answer: "Autriche" },
  { code: "cz", answer: "Tchéquie", aliases: ["République tchèque"] },
  { code: "hu", answer: "Hongrie" },
  { code: "ro", answer: "Roumanie" },
  { code: "ie", answer: "Irlande" },
  { code: "nz", answer: "Nouvelle-Zélande", aliases: ["Nouvelle-Zelande"] },
];
